// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module predecoder_kernel_conv3d_hidden_layer_1_Pipeline_VITIS_LOOP_89_1_VITIS_LOOP_90_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        zext_ln43,
        window_0_address0,
        window_0_ce0,
        window_0_we0,
        window_0_d0,
        window_0_1_address0,
        window_0_1_ce0,
        window_0_1_we0,
        window_0_1_d0,
        window_0_2_address0,
        window_0_2_ce0,
        window_0_2_we0,
        window_0_2_d0,
        zext_ln62,
        cmp8_i_i,
        fb_0_address0,
        fb_0_ce0,
        fb_0_q0,
        fb_0_1_address0,
        fb_0_1_ce0,
        fb_0_1_q0,
        fb_0_2_address0,
        fb_0_2_ce0,
        fb_0_2_q0,
        fb_0_3_address0,
        fb_0_3_ce0,
        fb_0_3_q0,
        fb_0_4_address0,
        fb_0_4_ce0,
        fb_0_4_q0,
        fb_0_6_address0,
        fb_0_6_ce0,
        fb_0_6_q0,
        fb_0_7_address0,
        fb_0_7_ce0,
        fb_0_7_q0,
        fb_0_8_address0,
        fb_0_8_ce0,
        fb_0_8_q0,
        fb_0_9_address0,
        fb_0_9_ce0,
        fb_0_9_q0,
        fb_0_10_address0,
        fb_0_10_ce0,
        fb_0_10_q0,
        fb_0_12_address0,
        fb_0_12_ce0,
        fb_0_12_q0,
        fb_0_13_address0,
        fb_0_13_ce0,
        fb_0_13_q0,
        fb_0_14_address0,
        fb_0_14_ce0,
        fb_0_14_q0,
        fb_0_15_address0,
        fb_0_15_ce0,
        fb_0_15_q0,
        fb_0_16_address0,
        fb_0_16_ce0,
        fb_0_16_q0,
        select_ln62,
        fb_0_5_address0,
        fb_0_5_ce0,
        fb_0_5_q0,
        fb_0_11_address0,
        fb_0_11_ce0,
        fb_0_11_q0,
        fb_0_17_address0,
        fb_0_17_ce0,
        fb_0_17_q0,
        cmp9_i_i_2
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [2:0] zext_ln43;
output  [3:0] window_0_address0;
output   window_0_ce0;
output   window_0_we0;
output  [7:0] window_0_d0;
output  [3:0] window_0_1_address0;
output   window_0_1_ce0;
output   window_0_1_we0;
output  [7:0] window_0_1_d0;
output  [3:0] window_0_2_address0;
output   window_0_2_ce0;
output   window_0_2_we0;
output  [7:0] window_0_2_d0;
input  [2:0] zext_ln62;
input  [0:0] cmp8_i_i;
output  [2:0] fb_0_address0;
output   fb_0_ce0;
input  [7:0] fb_0_q0;
output  [2:0] fb_0_1_address0;
output   fb_0_1_ce0;
input  [7:0] fb_0_1_q0;
output  [2:0] fb_0_2_address0;
output   fb_0_2_ce0;
input  [7:0] fb_0_2_q0;
output  [2:0] fb_0_3_address0;
output   fb_0_3_ce0;
input  [7:0] fb_0_3_q0;
output  [2:0] fb_0_4_address0;
output   fb_0_4_ce0;
input  [7:0] fb_0_4_q0;
output  [2:0] fb_0_6_address0;
output   fb_0_6_ce0;
input  [7:0] fb_0_6_q0;
output  [2:0] fb_0_7_address0;
output   fb_0_7_ce0;
input  [7:0] fb_0_7_q0;
output  [2:0] fb_0_8_address0;
output   fb_0_8_ce0;
input  [7:0] fb_0_8_q0;
output  [2:0] fb_0_9_address0;
output   fb_0_9_ce0;
input  [7:0] fb_0_9_q0;
output  [2:0] fb_0_10_address0;
output   fb_0_10_ce0;
input  [7:0] fb_0_10_q0;
output  [2:0] fb_0_12_address0;
output   fb_0_12_ce0;
input  [7:0] fb_0_12_q0;
output  [2:0] fb_0_13_address0;
output   fb_0_13_ce0;
input  [7:0] fb_0_13_q0;
output  [2:0] fb_0_14_address0;
output   fb_0_14_ce0;
input  [7:0] fb_0_14_q0;
output  [2:0] fb_0_15_address0;
output   fb_0_15_ce0;
input  [7:0] fb_0_15_q0;
output  [2:0] fb_0_16_address0;
output   fb_0_16_ce0;
input  [7:0] fb_0_16_q0;
input  [2:0] select_ln62;
output  [2:0] fb_0_5_address0;
output   fb_0_5_ce0;
input  [7:0] fb_0_5_q0;
output  [2:0] fb_0_11_address0;
output   fb_0_11_ce0;
input  [7:0] fb_0_11_q0;
output  [2:0] fb_0_17_address0;
output   fb_0_17_ce0;
input  [7:0] fb_0_17_q0;
input  [0:0] cmp9_i_i_2;

reg ap_idle;
reg window_0_ce0;
reg window_0_we0;
reg window_0_1_ce0;
reg window_0_1_we0;
reg window_0_2_ce0;
reg window_0_2_we0;
reg fb_0_ce0;
reg fb_0_1_ce0;
reg fb_0_2_ce0;
reg fb_0_3_ce0;
reg fb_0_4_ce0;
reg fb_0_6_ce0;
reg fb_0_7_ce0;
reg fb_0_8_ce0;
reg fb_0_9_ce0;
reg fb_0_10_ce0;
reg fb_0_12_ce0;
reg fb_0_13_ce0;
reg fb_0_14_ce0;
reg fb_0_15_ce0;
reg fb_0_16_ce0;
reg fb_0_5_ce0;
reg fb_0_11_ce0;
reg fb_0_17_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln89_fu_467_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] zext_ln62_cast_fu_441_p1;
reg   [3:0] zext_ln62_cast_reg_1102;
wire   [3:0] zext_ln43_cast_fu_445_p1;
reg   [3:0] zext_ln43_cast_reg_1107;
wire   [1:0] select_ln89_fu_497_p3;
reg   [1:0] select_ln89_reg_1116;
reg   [1:0] select_ln89_reg_1116_pp0_iter1_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter2_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter3_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter4_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter5_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter6_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter7_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter8_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter9_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter10_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter11_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter12_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter13_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter14_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter15_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter16_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter17_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter18_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter19_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter20_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter21_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter22_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter23_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter24_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter25_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter26_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter27_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter28_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter29_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter30_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter31_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter32_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter33_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter34_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter35_reg;
reg   [1:0] select_ln89_reg_1116_pp0_iter36_reg;
wire   [1:0] select_ln89_1_fu_505_p3;
reg   [1:0] select_ln89_1_reg_1122;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter1_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter2_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter3_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter4_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter5_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter6_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter7_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter8_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter9_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter10_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter11_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter12_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter13_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter14_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter15_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter16_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter17_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter18_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter19_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter20_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter21_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter22_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter23_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter24_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter25_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter26_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter27_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter28_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter29_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter30_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter31_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter32_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter33_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter34_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter35_reg;
reg   [1:0] select_ln89_1_reg_1122_pp0_iter36_reg;
wire   [0:0] tmp_358_fu_548_p3;
reg   [0:0] tmp_358_reg_1129;
reg   [0:0] tmp_358_reg_1129_pp0_iter2_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter3_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter4_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter5_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter6_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter7_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter8_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter9_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter10_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter11_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter12_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter13_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter14_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter15_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter16_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter17_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter18_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter19_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter20_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter21_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter22_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter23_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter24_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter25_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter26_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter27_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter28_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter29_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter30_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter31_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter32_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter33_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter34_reg;
reg   [0:0] tmp_358_reg_1129_pp0_iter35_reg;
wire   [0:0] cmp2_i_i_not_fu_580_p2;
reg   [0:0] cmp2_i_i_not_reg_1140;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter2_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter3_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter4_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter5_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter6_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter7_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter8_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter9_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter10_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter11_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter12_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter13_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter14_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter15_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter16_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter17_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter18_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter19_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter20_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter21_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter22_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter23_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter24_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter25_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter26_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter27_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter28_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter29_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter30_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter31_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter32_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter33_reg;
reg   [0:0] cmp2_i_i_not_reg_1140_pp0_iter34_reg;
wire   [0:0] or_ln65_1_fu_650_p2;
reg   [0:0] or_ln65_1_reg_1145;
reg   [0:0] or_ln65_1_reg_1145_pp0_iter36_reg;
wire   [7:0] tmp_374_fu_754_p9;
reg   [7:0] tmp_374_reg_1241;
wire   [7:0] tmp_378_fu_867_p9;
reg   [7:0] tmp_378_reg_1246;
wire   [7:0] tmp_382_fu_968_p9;
reg   [7:0] tmp_382_reg_1251;
wire   [63:0] zext_ln65_fu_604_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln97_2_fu_1013_p1;
reg   [1:0] dy_fu_126;
wire   [1:0] add_ln90_fu_513_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_dy_load;
reg   [1:0] dz_fu_130;
reg   [1:0] ap_sig_allocacmp_dz_load;
reg   [3:0] indvar_flatten25_fu_134;
wire   [3:0] add_ln89_1_fu_473_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten25_load;
wire   [0:0] icmp_ln90_fu_491_p2;
wire   [1:0] add_ln89_fu_485_p2;
wire   [1:0] tmp_fu_534_p2;
wire  signed [3:0] tmp_cast_fu_539_p1;
wire   [3:0] empty_fu_543_p2;
wire   [3:0] p_cast119_fu_556_p3;
wire   [3:0] p_smodpre16_fu_564_p2;
wire  signed [31:0] grp_fu_574_p0;
wire   [2:0] grp_fu_574_p1;
wire   [2:0] zext_ln90_fu_586_p1;
wire   [2:0] tmp1_fu_589_p2;
wire  signed [3:0] tmp1_cast_fu_595_p1;
wire   [3:0] empty_60_fu_599_p2;
wire   [0:0] tmp_359_fu_626_p3;
wire   [0:0] icmp_ln65_fu_634_p2;
wire   [0:0] or_ln65_2_fu_645_p2;
wire   [0:0] or_ln65_fu_640_p2;
wire   [1:0] grp_fu_574_p2;
wire   [1:0] empty_58_fu_656_p1;
wire   [1:0] empty_59_fu_660_p2;
wire   [7:0] tmp_s_fu_673_p11;
wire   [7:0] tmp_372_fu_700_p11;
wire   [7:0] tmp_373_fu_727_p11;
wire   [7:0] tmp_s_fu_673_p13;
wire   [7:0] tmp_372_fu_700_p13;
wire   [7:0] tmp_373_fu_727_p13;
wire   [7:0] tmp_374_fu_754_p7;
wire   [1:0] p_smodpost17_fu_666_p3;
wire   [7:0] tmp_375_fu_774_p13;
wire   [7:0] tmp_376_fu_805_p13;
wire   [7:0] tmp_377_fu_836_p13;
wire   [7:0] tmp_375_fu_774_p15;
wire   [7:0] tmp_376_fu_805_p15;
wire   [7:0] tmp_377_fu_836_p15;
wire   [7:0] tmp_378_fu_867_p7;
wire   [7:0] tmp_379_fu_887_p11;
wire   [7:0] tmp_380_fu_914_p11;
wire   [7:0] tmp_381_fu_941_p11;
wire   [7:0] tmp_379_fu_887_p13;
wire   [7:0] tmp_380_fu_914_p13;
wire   [7:0] tmp_381_fu_941_p13;
wire   [7:0] tmp_382_fu_968_p7;
wire   [3:0] tmp_3_fu_991_p3;
wire   [3:0] zext_ln97_fu_988_p1;
wire   [3:0] sub_ln97_fu_998_p2;
wire   [3:0] zext_ln97_1_fu_1004_p1;
wire   [3:0] add_ln97_fu_1007_p2;
wire   [0:0] xor_ln65_fu_1020_p2;
wire   [0:0] in_bounds_fu_1025_p2;
wire   [0:0] in_bounds_1_fu_1045_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [2:0] tmp_s_fu_673_p1;
wire   [2:0] tmp_s_fu_673_p3;
wire   [2:0] tmp_s_fu_673_p5;
wire  signed [2:0] tmp_s_fu_673_p7;
wire  signed [2:0] tmp_s_fu_673_p9;
wire   [2:0] tmp_372_fu_700_p1;
wire   [2:0] tmp_372_fu_700_p3;
wire   [2:0] tmp_372_fu_700_p5;
wire  signed [2:0] tmp_372_fu_700_p7;
wire  signed [2:0] tmp_372_fu_700_p9;
wire   [2:0] tmp_373_fu_727_p1;
wire   [2:0] tmp_373_fu_727_p3;
wire   [2:0] tmp_373_fu_727_p5;
wire  signed [2:0] tmp_373_fu_727_p7;
wire  signed [2:0] tmp_373_fu_727_p9;
wire   [1:0] tmp_374_fu_754_p1;
wire   [1:0] tmp_374_fu_754_p3;
wire  signed [1:0] tmp_374_fu_754_p5;
wire   [2:0] tmp_375_fu_774_p1;
wire   [2:0] tmp_375_fu_774_p3;
wire   [2:0] tmp_375_fu_774_p5;
wire   [2:0] tmp_375_fu_774_p7;
wire  signed [2:0] tmp_375_fu_774_p9;
wire  signed [2:0] tmp_375_fu_774_p11;
wire   [2:0] tmp_376_fu_805_p1;
wire   [2:0] tmp_376_fu_805_p3;
wire   [2:0] tmp_376_fu_805_p5;
wire   [2:0] tmp_376_fu_805_p7;
wire  signed [2:0] tmp_376_fu_805_p9;
wire  signed [2:0] tmp_376_fu_805_p11;
wire   [2:0] tmp_377_fu_836_p1;
wire   [2:0] tmp_377_fu_836_p3;
wire   [2:0] tmp_377_fu_836_p5;
wire   [2:0] tmp_377_fu_836_p7;
wire  signed [2:0] tmp_377_fu_836_p9;
wire  signed [2:0] tmp_377_fu_836_p11;
wire   [1:0] tmp_378_fu_867_p1;
wire   [1:0] tmp_378_fu_867_p3;
wire  signed [1:0] tmp_378_fu_867_p5;
wire   [2:0] tmp_379_fu_887_p1;
wire   [2:0] tmp_379_fu_887_p3;
wire   [2:0] tmp_379_fu_887_p5;
wire   [2:0] tmp_379_fu_887_p7;
wire  signed [2:0] tmp_379_fu_887_p9;
wire   [2:0] tmp_380_fu_914_p1;
wire   [2:0] tmp_380_fu_914_p3;
wire   [2:0] tmp_380_fu_914_p5;
wire   [2:0] tmp_380_fu_914_p7;
wire  signed [2:0] tmp_380_fu_914_p9;
wire   [2:0] tmp_381_fu_941_p1;
wire   [2:0] tmp_381_fu_941_p3;
wire   [2:0] tmp_381_fu_941_p5;
wire   [2:0] tmp_381_fu_941_p7;
wire  signed [2:0] tmp_381_fu_941_p9;
wire   [1:0] tmp_382_fu_968_p1;
wire   [1:0] tmp_382_fu_968_p3;
wire  signed [1:0] tmp_382_fu_968_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 dy_fu_126 = 2'd0;
#0 dz_fu_130 = 2'd0;
#0 indvar_flatten25_fu_134 = 4'd0;
#0 ap_done_reg = 1'b0;
end

predecoder_kernel_urem_32s_3ns_2_36_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_32s_3ns_2_36_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_574_p0),
    .din1(grp_fu_574_p1),
    .ce(1'b1),
    .dout(grp_fu_574_p2)
);

predecoder_kernel_sparsemux_11_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h1 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h3 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h4 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h5 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_11_3_8_1_1_U46(
    .din0(fb_0_q0),
    .din1(fb_0_1_q0),
    .din2(fb_0_2_q0),
    .din3(fb_0_3_q0),
    .din4(fb_0_4_q0),
    .def(tmp_s_fu_673_p11),
    .sel(select_ln62),
    .dout(tmp_s_fu_673_p13)
);

predecoder_kernel_sparsemux_11_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h1 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h3 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h4 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h5 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_11_3_8_1_1_U47(
    .din0(fb_0_6_q0),
    .din1(fb_0_7_q0),
    .din2(fb_0_8_q0),
    .din3(fb_0_9_q0),
    .din4(fb_0_10_q0),
    .def(tmp_372_fu_700_p11),
    .sel(select_ln62),
    .dout(tmp_372_fu_700_p13)
);

predecoder_kernel_sparsemux_11_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h1 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h3 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h4 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h5 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_11_3_8_1_1_U48(
    .din0(fb_0_12_q0),
    .din1(fb_0_13_q0),
    .din2(fb_0_14_q0),
    .din3(fb_0_15_q0),
    .din4(fb_0_16_q0),
    .def(tmp_373_fu_727_p11),
    .sel(select_ln62),
    .dout(tmp_373_fu_727_p13)
);

predecoder_kernel_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U49(
    .din0(tmp_s_fu_673_p13),
    .din1(tmp_372_fu_700_p13),
    .din2(tmp_373_fu_727_p13),
    .def(tmp_374_fu_754_p7),
    .sel(p_smodpost17_fu_666_p3),
    .dout(tmp_374_fu_754_p9)
);

predecoder_kernel_sparsemux_13_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_13_3_8_1_1_U50(
    .din0(fb_0_q0),
    .din1(fb_0_1_q0),
    .din2(fb_0_2_q0),
    .din3(fb_0_3_q0),
    .din4(fb_0_4_q0),
    .din5(fb_0_5_q0),
    .def(tmp_375_fu_774_p13),
    .sel(select_ln62),
    .dout(tmp_375_fu_774_p15)
);

predecoder_kernel_sparsemux_13_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_13_3_8_1_1_U51(
    .din0(fb_0_6_q0),
    .din1(fb_0_7_q0),
    .din2(fb_0_8_q0),
    .din3(fb_0_9_q0),
    .din4(fb_0_10_q0),
    .din5(fb_0_11_q0),
    .def(tmp_376_fu_805_p13),
    .sel(select_ln62),
    .dout(tmp_376_fu_805_p15)
);

predecoder_kernel_sparsemux_13_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_13_3_8_1_1_U52(
    .din0(fb_0_12_q0),
    .din1(fb_0_13_q0),
    .din2(fb_0_14_q0),
    .din3(fb_0_15_q0),
    .din4(fb_0_16_q0),
    .din5(fb_0_17_q0),
    .def(tmp_377_fu_836_p13),
    .sel(select_ln62),
    .dout(tmp_377_fu_836_p15)
);

predecoder_kernel_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U53(
    .din0(tmp_375_fu_774_p15),
    .din1(tmp_376_fu_805_p15),
    .din2(tmp_377_fu_836_p15),
    .def(tmp_378_fu_867_p7),
    .sel(p_smodpost17_fu_666_p3),
    .dout(tmp_378_fu_867_p9)
);

predecoder_kernel_sparsemux_11_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_11_3_8_1_1_U54(
    .din0(fb_0_1_q0),
    .din1(fb_0_2_q0),
    .din2(fb_0_3_q0),
    .din3(fb_0_4_q0),
    .din4(fb_0_5_q0),
    .def(tmp_379_fu_887_p11),
    .sel(select_ln62),
    .dout(tmp_379_fu_887_p13)
);

predecoder_kernel_sparsemux_11_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_11_3_8_1_1_U55(
    .din0(fb_0_7_q0),
    .din1(fb_0_8_q0),
    .din2(fb_0_9_q0),
    .din3(fb_0_10_q0),
    .din4(fb_0_11_q0),
    .def(tmp_380_fu_914_p11),
    .sel(select_ln62),
    .dout(tmp_380_fu_914_p13)
);

predecoder_kernel_sparsemux_11_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_11_3_8_1_1_U56(
    .din0(fb_0_13_q0),
    .din1(fb_0_14_q0),
    .din2(fb_0_15_q0),
    .din3(fb_0_16_q0),
    .din4(fb_0_17_q0),
    .def(tmp_381_fu_941_p11),
    .sel(select_ln62),
    .dout(tmp_381_fu_941_p13)
);

predecoder_kernel_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U57(
    .din0(tmp_379_fu_887_p13),
    .din1(tmp_380_fu_914_p13),
    .din2(tmp_381_fu_941_p13),
    .def(tmp_382_fu_968_p7),
    .sel(p_smodpost17_fu_666_p3),
    .dout(tmp_382_fu_968_p9)
);

predecoder_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter36_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln89_fu_467_p2 == 1'd0))) begin
            dy_fu_126 <= add_ln90_fu_513_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            dy_fu_126 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln89_fu_467_p2 == 1'd0))) begin
            dz_fu_130 <= select_ln89_1_fu_505_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            dz_fu_130 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln89_fu_467_p2 == 1'd0))) begin
            indvar_flatten25_fu_134 <= add_ln89_1_fu_473_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten25_fu_134 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        cmp2_i_i_not_reg_1140_pp0_iter10_reg <= cmp2_i_i_not_reg_1140_pp0_iter9_reg;
        cmp2_i_i_not_reg_1140_pp0_iter11_reg <= cmp2_i_i_not_reg_1140_pp0_iter10_reg;
        cmp2_i_i_not_reg_1140_pp0_iter12_reg <= cmp2_i_i_not_reg_1140_pp0_iter11_reg;
        cmp2_i_i_not_reg_1140_pp0_iter13_reg <= cmp2_i_i_not_reg_1140_pp0_iter12_reg;
        cmp2_i_i_not_reg_1140_pp0_iter14_reg <= cmp2_i_i_not_reg_1140_pp0_iter13_reg;
        cmp2_i_i_not_reg_1140_pp0_iter15_reg <= cmp2_i_i_not_reg_1140_pp0_iter14_reg;
        cmp2_i_i_not_reg_1140_pp0_iter16_reg <= cmp2_i_i_not_reg_1140_pp0_iter15_reg;
        cmp2_i_i_not_reg_1140_pp0_iter17_reg <= cmp2_i_i_not_reg_1140_pp0_iter16_reg;
        cmp2_i_i_not_reg_1140_pp0_iter18_reg <= cmp2_i_i_not_reg_1140_pp0_iter17_reg;
        cmp2_i_i_not_reg_1140_pp0_iter19_reg <= cmp2_i_i_not_reg_1140_pp0_iter18_reg;
        cmp2_i_i_not_reg_1140_pp0_iter20_reg <= cmp2_i_i_not_reg_1140_pp0_iter19_reg;
        cmp2_i_i_not_reg_1140_pp0_iter21_reg <= cmp2_i_i_not_reg_1140_pp0_iter20_reg;
        cmp2_i_i_not_reg_1140_pp0_iter22_reg <= cmp2_i_i_not_reg_1140_pp0_iter21_reg;
        cmp2_i_i_not_reg_1140_pp0_iter23_reg <= cmp2_i_i_not_reg_1140_pp0_iter22_reg;
        cmp2_i_i_not_reg_1140_pp0_iter24_reg <= cmp2_i_i_not_reg_1140_pp0_iter23_reg;
        cmp2_i_i_not_reg_1140_pp0_iter25_reg <= cmp2_i_i_not_reg_1140_pp0_iter24_reg;
        cmp2_i_i_not_reg_1140_pp0_iter26_reg <= cmp2_i_i_not_reg_1140_pp0_iter25_reg;
        cmp2_i_i_not_reg_1140_pp0_iter27_reg <= cmp2_i_i_not_reg_1140_pp0_iter26_reg;
        cmp2_i_i_not_reg_1140_pp0_iter28_reg <= cmp2_i_i_not_reg_1140_pp0_iter27_reg;
        cmp2_i_i_not_reg_1140_pp0_iter29_reg <= cmp2_i_i_not_reg_1140_pp0_iter28_reg;
        cmp2_i_i_not_reg_1140_pp0_iter2_reg <= cmp2_i_i_not_reg_1140;
        cmp2_i_i_not_reg_1140_pp0_iter30_reg <= cmp2_i_i_not_reg_1140_pp0_iter29_reg;
        cmp2_i_i_not_reg_1140_pp0_iter31_reg <= cmp2_i_i_not_reg_1140_pp0_iter30_reg;
        cmp2_i_i_not_reg_1140_pp0_iter32_reg <= cmp2_i_i_not_reg_1140_pp0_iter31_reg;
        cmp2_i_i_not_reg_1140_pp0_iter33_reg <= cmp2_i_i_not_reg_1140_pp0_iter32_reg;
        cmp2_i_i_not_reg_1140_pp0_iter34_reg <= cmp2_i_i_not_reg_1140_pp0_iter33_reg;
        cmp2_i_i_not_reg_1140_pp0_iter3_reg <= cmp2_i_i_not_reg_1140_pp0_iter2_reg;
        cmp2_i_i_not_reg_1140_pp0_iter4_reg <= cmp2_i_i_not_reg_1140_pp0_iter3_reg;
        cmp2_i_i_not_reg_1140_pp0_iter5_reg <= cmp2_i_i_not_reg_1140_pp0_iter4_reg;
        cmp2_i_i_not_reg_1140_pp0_iter6_reg <= cmp2_i_i_not_reg_1140_pp0_iter5_reg;
        cmp2_i_i_not_reg_1140_pp0_iter7_reg <= cmp2_i_i_not_reg_1140_pp0_iter6_reg;
        cmp2_i_i_not_reg_1140_pp0_iter8_reg <= cmp2_i_i_not_reg_1140_pp0_iter7_reg;
        cmp2_i_i_not_reg_1140_pp0_iter9_reg <= cmp2_i_i_not_reg_1140_pp0_iter8_reg;
        or_ln65_1_reg_1145 <= or_ln65_1_fu_650_p2;
        or_ln65_1_reg_1145_pp0_iter36_reg <= or_ln65_1_reg_1145;
        select_ln89_1_reg_1122_pp0_iter10_reg <= select_ln89_1_reg_1122_pp0_iter9_reg;
        select_ln89_1_reg_1122_pp0_iter11_reg <= select_ln89_1_reg_1122_pp0_iter10_reg;
        select_ln89_1_reg_1122_pp0_iter12_reg <= select_ln89_1_reg_1122_pp0_iter11_reg;
        select_ln89_1_reg_1122_pp0_iter13_reg <= select_ln89_1_reg_1122_pp0_iter12_reg;
        select_ln89_1_reg_1122_pp0_iter14_reg <= select_ln89_1_reg_1122_pp0_iter13_reg;
        select_ln89_1_reg_1122_pp0_iter15_reg <= select_ln89_1_reg_1122_pp0_iter14_reg;
        select_ln89_1_reg_1122_pp0_iter16_reg <= select_ln89_1_reg_1122_pp0_iter15_reg;
        select_ln89_1_reg_1122_pp0_iter17_reg <= select_ln89_1_reg_1122_pp0_iter16_reg;
        select_ln89_1_reg_1122_pp0_iter18_reg <= select_ln89_1_reg_1122_pp0_iter17_reg;
        select_ln89_1_reg_1122_pp0_iter19_reg <= select_ln89_1_reg_1122_pp0_iter18_reg;
        select_ln89_1_reg_1122_pp0_iter20_reg <= select_ln89_1_reg_1122_pp0_iter19_reg;
        select_ln89_1_reg_1122_pp0_iter21_reg <= select_ln89_1_reg_1122_pp0_iter20_reg;
        select_ln89_1_reg_1122_pp0_iter22_reg <= select_ln89_1_reg_1122_pp0_iter21_reg;
        select_ln89_1_reg_1122_pp0_iter23_reg <= select_ln89_1_reg_1122_pp0_iter22_reg;
        select_ln89_1_reg_1122_pp0_iter24_reg <= select_ln89_1_reg_1122_pp0_iter23_reg;
        select_ln89_1_reg_1122_pp0_iter25_reg <= select_ln89_1_reg_1122_pp0_iter24_reg;
        select_ln89_1_reg_1122_pp0_iter26_reg <= select_ln89_1_reg_1122_pp0_iter25_reg;
        select_ln89_1_reg_1122_pp0_iter27_reg <= select_ln89_1_reg_1122_pp0_iter26_reg;
        select_ln89_1_reg_1122_pp0_iter28_reg <= select_ln89_1_reg_1122_pp0_iter27_reg;
        select_ln89_1_reg_1122_pp0_iter29_reg <= select_ln89_1_reg_1122_pp0_iter28_reg;
        select_ln89_1_reg_1122_pp0_iter2_reg <= select_ln89_1_reg_1122_pp0_iter1_reg;
        select_ln89_1_reg_1122_pp0_iter30_reg <= select_ln89_1_reg_1122_pp0_iter29_reg;
        select_ln89_1_reg_1122_pp0_iter31_reg <= select_ln89_1_reg_1122_pp0_iter30_reg;
        select_ln89_1_reg_1122_pp0_iter32_reg <= select_ln89_1_reg_1122_pp0_iter31_reg;
        select_ln89_1_reg_1122_pp0_iter33_reg <= select_ln89_1_reg_1122_pp0_iter32_reg;
        select_ln89_1_reg_1122_pp0_iter34_reg <= select_ln89_1_reg_1122_pp0_iter33_reg;
        select_ln89_1_reg_1122_pp0_iter35_reg <= select_ln89_1_reg_1122_pp0_iter34_reg;
        select_ln89_1_reg_1122_pp0_iter36_reg <= select_ln89_1_reg_1122_pp0_iter35_reg;
        select_ln89_1_reg_1122_pp0_iter3_reg <= select_ln89_1_reg_1122_pp0_iter2_reg;
        select_ln89_1_reg_1122_pp0_iter4_reg <= select_ln89_1_reg_1122_pp0_iter3_reg;
        select_ln89_1_reg_1122_pp0_iter5_reg <= select_ln89_1_reg_1122_pp0_iter4_reg;
        select_ln89_1_reg_1122_pp0_iter6_reg <= select_ln89_1_reg_1122_pp0_iter5_reg;
        select_ln89_1_reg_1122_pp0_iter7_reg <= select_ln89_1_reg_1122_pp0_iter6_reg;
        select_ln89_1_reg_1122_pp0_iter8_reg <= select_ln89_1_reg_1122_pp0_iter7_reg;
        select_ln89_1_reg_1122_pp0_iter9_reg <= select_ln89_1_reg_1122_pp0_iter8_reg;
        select_ln89_reg_1116_pp0_iter10_reg <= select_ln89_reg_1116_pp0_iter9_reg;
        select_ln89_reg_1116_pp0_iter11_reg <= select_ln89_reg_1116_pp0_iter10_reg;
        select_ln89_reg_1116_pp0_iter12_reg <= select_ln89_reg_1116_pp0_iter11_reg;
        select_ln89_reg_1116_pp0_iter13_reg <= select_ln89_reg_1116_pp0_iter12_reg;
        select_ln89_reg_1116_pp0_iter14_reg <= select_ln89_reg_1116_pp0_iter13_reg;
        select_ln89_reg_1116_pp0_iter15_reg <= select_ln89_reg_1116_pp0_iter14_reg;
        select_ln89_reg_1116_pp0_iter16_reg <= select_ln89_reg_1116_pp0_iter15_reg;
        select_ln89_reg_1116_pp0_iter17_reg <= select_ln89_reg_1116_pp0_iter16_reg;
        select_ln89_reg_1116_pp0_iter18_reg <= select_ln89_reg_1116_pp0_iter17_reg;
        select_ln89_reg_1116_pp0_iter19_reg <= select_ln89_reg_1116_pp0_iter18_reg;
        select_ln89_reg_1116_pp0_iter20_reg <= select_ln89_reg_1116_pp0_iter19_reg;
        select_ln89_reg_1116_pp0_iter21_reg <= select_ln89_reg_1116_pp0_iter20_reg;
        select_ln89_reg_1116_pp0_iter22_reg <= select_ln89_reg_1116_pp0_iter21_reg;
        select_ln89_reg_1116_pp0_iter23_reg <= select_ln89_reg_1116_pp0_iter22_reg;
        select_ln89_reg_1116_pp0_iter24_reg <= select_ln89_reg_1116_pp0_iter23_reg;
        select_ln89_reg_1116_pp0_iter25_reg <= select_ln89_reg_1116_pp0_iter24_reg;
        select_ln89_reg_1116_pp0_iter26_reg <= select_ln89_reg_1116_pp0_iter25_reg;
        select_ln89_reg_1116_pp0_iter27_reg <= select_ln89_reg_1116_pp0_iter26_reg;
        select_ln89_reg_1116_pp0_iter28_reg <= select_ln89_reg_1116_pp0_iter27_reg;
        select_ln89_reg_1116_pp0_iter29_reg <= select_ln89_reg_1116_pp0_iter28_reg;
        select_ln89_reg_1116_pp0_iter2_reg <= select_ln89_reg_1116_pp0_iter1_reg;
        select_ln89_reg_1116_pp0_iter30_reg <= select_ln89_reg_1116_pp0_iter29_reg;
        select_ln89_reg_1116_pp0_iter31_reg <= select_ln89_reg_1116_pp0_iter30_reg;
        select_ln89_reg_1116_pp0_iter32_reg <= select_ln89_reg_1116_pp0_iter31_reg;
        select_ln89_reg_1116_pp0_iter33_reg <= select_ln89_reg_1116_pp0_iter32_reg;
        select_ln89_reg_1116_pp0_iter34_reg <= select_ln89_reg_1116_pp0_iter33_reg;
        select_ln89_reg_1116_pp0_iter35_reg <= select_ln89_reg_1116_pp0_iter34_reg;
        select_ln89_reg_1116_pp0_iter36_reg <= select_ln89_reg_1116_pp0_iter35_reg;
        select_ln89_reg_1116_pp0_iter3_reg <= select_ln89_reg_1116_pp0_iter2_reg;
        select_ln89_reg_1116_pp0_iter4_reg <= select_ln89_reg_1116_pp0_iter3_reg;
        select_ln89_reg_1116_pp0_iter5_reg <= select_ln89_reg_1116_pp0_iter4_reg;
        select_ln89_reg_1116_pp0_iter6_reg <= select_ln89_reg_1116_pp0_iter5_reg;
        select_ln89_reg_1116_pp0_iter7_reg <= select_ln89_reg_1116_pp0_iter6_reg;
        select_ln89_reg_1116_pp0_iter8_reg <= select_ln89_reg_1116_pp0_iter7_reg;
        select_ln89_reg_1116_pp0_iter9_reg <= select_ln89_reg_1116_pp0_iter8_reg;
        tmp_358_reg_1129_pp0_iter10_reg <= tmp_358_reg_1129_pp0_iter9_reg;
        tmp_358_reg_1129_pp0_iter11_reg <= tmp_358_reg_1129_pp0_iter10_reg;
        tmp_358_reg_1129_pp0_iter12_reg <= tmp_358_reg_1129_pp0_iter11_reg;
        tmp_358_reg_1129_pp0_iter13_reg <= tmp_358_reg_1129_pp0_iter12_reg;
        tmp_358_reg_1129_pp0_iter14_reg <= tmp_358_reg_1129_pp0_iter13_reg;
        tmp_358_reg_1129_pp0_iter15_reg <= tmp_358_reg_1129_pp0_iter14_reg;
        tmp_358_reg_1129_pp0_iter16_reg <= tmp_358_reg_1129_pp0_iter15_reg;
        tmp_358_reg_1129_pp0_iter17_reg <= tmp_358_reg_1129_pp0_iter16_reg;
        tmp_358_reg_1129_pp0_iter18_reg <= tmp_358_reg_1129_pp0_iter17_reg;
        tmp_358_reg_1129_pp0_iter19_reg <= tmp_358_reg_1129_pp0_iter18_reg;
        tmp_358_reg_1129_pp0_iter20_reg <= tmp_358_reg_1129_pp0_iter19_reg;
        tmp_358_reg_1129_pp0_iter21_reg <= tmp_358_reg_1129_pp0_iter20_reg;
        tmp_358_reg_1129_pp0_iter22_reg <= tmp_358_reg_1129_pp0_iter21_reg;
        tmp_358_reg_1129_pp0_iter23_reg <= tmp_358_reg_1129_pp0_iter22_reg;
        tmp_358_reg_1129_pp0_iter24_reg <= tmp_358_reg_1129_pp0_iter23_reg;
        tmp_358_reg_1129_pp0_iter25_reg <= tmp_358_reg_1129_pp0_iter24_reg;
        tmp_358_reg_1129_pp0_iter26_reg <= tmp_358_reg_1129_pp0_iter25_reg;
        tmp_358_reg_1129_pp0_iter27_reg <= tmp_358_reg_1129_pp0_iter26_reg;
        tmp_358_reg_1129_pp0_iter28_reg <= tmp_358_reg_1129_pp0_iter27_reg;
        tmp_358_reg_1129_pp0_iter29_reg <= tmp_358_reg_1129_pp0_iter28_reg;
        tmp_358_reg_1129_pp0_iter2_reg <= tmp_358_reg_1129;
        tmp_358_reg_1129_pp0_iter30_reg <= tmp_358_reg_1129_pp0_iter29_reg;
        tmp_358_reg_1129_pp0_iter31_reg <= tmp_358_reg_1129_pp0_iter30_reg;
        tmp_358_reg_1129_pp0_iter32_reg <= tmp_358_reg_1129_pp0_iter31_reg;
        tmp_358_reg_1129_pp0_iter33_reg <= tmp_358_reg_1129_pp0_iter32_reg;
        tmp_358_reg_1129_pp0_iter34_reg <= tmp_358_reg_1129_pp0_iter33_reg;
        tmp_358_reg_1129_pp0_iter35_reg <= tmp_358_reg_1129_pp0_iter34_reg;
        tmp_358_reg_1129_pp0_iter3_reg <= tmp_358_reg_1129_pp0_iter2_reg;
        tmp_358_reg_1129_pp0_iter4_reg <= tmp_358_reg_1129_pp0_iter3_reg;
        tmp_358_reg_1129_pp0_iter5_reg <= tmp_358_reg_1129_pp0_iter4_reg;
        tmp_358_reg_1129_pp0_iter6_reg <= tmp_358_reg_1129_pp0_iter5_reg;
        tmp_358_reg_1129_pp0_iter7_reg <= tmp_358_reg_1129_pp0_iter6_reg;
        tmp_358_reg_1129_pp0_iter8_reg <= tmp_358_reg_1129_pp0_iter7_reg;
        tmp_358_reg_1129_pp0_iter9_reg <= tmp_358_reg_1129_pp0_iter8_reg;
        tmp_374_reg_1241 <= tmp_374_fu_754_p9;
        tmp_378_reg_1246 <= tmp_378_fu_867_p9;
        tmp_382_reg_1251 <= tmp_382_fu_968_p9;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        cmp2_i_i_not_reg_1140 <= cmp2_i_i_not_fu_580_p2;
        select_ln89_1_reg_1122 <= select_ln89_1_fu_505_p3;
        select_ln89_1_reg_1122_pp0_iter1_reg <= select_ln89_1_reg_1122;
        select_ln89_reg_1116 <= select_ln89_fu_497_p3;
        select_ln89_reg_1116_pp0_iter1_reg <= select_ln89_reg_1116;
        tmp_358_reg_1129 <= empty_fu_543_p2[32'd3];
        zext_ln43_cast_reg_1107[2 : 0] <= zext_ln43_cast_fu_445_p1[2 : 0];
        zext_ln62_cast_reg_1102[2 : 0] <= zext_ln62_cast_fu_441_p1[2 : 0];
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln89_fu_467_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter36_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) 
    & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_dy_load = 2'd0;
    end else begin
        ap_sig_allocacmp_dy_load = dy_fu_126;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_dz_load = 2'd0;
    end else begin
        ap_sig_allocacmp_dz_load = dz_fu_130;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten25_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten25_load = indvar_flatten25_fu_134;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_10_ce0 = 1'b1;
    end else begin
        fb_0_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_11_ce0 = 1'b1;
    end else begin
        fb_0_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_12_ce0 = 1'b1;
    end else begin
        fb_0_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_13_ce0 = 1'b1;
    end else begin
        fb_0_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_14_ce0 = 1'b1;
    end else begin
        fb_0_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_15_ce0 = 1'b1;
    end else begin
        fb_0_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_16_ce0 = 1'b1;
    end else begin
        fb_0_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_17_ce0 = 1'b1;
    end else begin
        fb_0_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_1_ce0 = 1'b1;
    end else begin
        fb_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_2_ce0 = 1'b1;
    end else begin
        fb_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_3_ce0 = 1'b1;
    end else begin
        fb_0_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_4_ce0 = 1'b1;
    end else begin
        fb_0_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_5_ce0 = 1'b1;
    end else begin
        fb_0_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_6_ce0 = 1'b1;
    end else begin
        fb_0_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_7_ce0 = 1'b1;
    end else begin
        fb_0_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_8_ce0 = 1'b1;
    end else begin
        fb_0_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_9_ce0 = 1'b1;
    end else begin
        fb_0_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        fb_0_ce0 = 1'b1;
    end else begin
        fb_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter37 == 1'b1))) begin
        window_0_1_ce0 = 1'b1;
    end else begin
        window_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter37 == 1'b1))) begin
        window_0_1_we0 = 1'b1;
    end else begin
        window_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter37 == 1'b1))) begin
        window_0_2_ce0 = 1'b1;
    end else begin
        window_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter37 == 1'b1))) begin
        window_0_2_we0 = 1'b1;
    end else begin
        window_0_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter37 == 1'b1))) begin
        window_0_ce0 = 1'b1;
    end else begin
        window_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter37 == 1'b1))) begin
        window_0_we0 = 1'b1;
    end else begin
        window_0_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln89_1_fu_473_p2 = (ap_sig_allocacmp_indvar_flatten25_load + 4'd1);

assign add_ln89_fu_485_p2 = (ap_sig_allocacmp_dz_load + 2'd1);

assign add_ln90_fu_513_p2 = (select_ln89_fu_497_p3 + 2'd1);

assign add_ln97_fu_1007_p2 = (sub_ln97_fu_998_p2 + zext_ln97_1_fu_1004_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign cmp2_i_i_not_fu_580_p2 = (($signed(empty_fu_543_p2) > $signed(4'd5)) ? 1'b1 : 1'b0);

assign empty_58_fu_656_p1 = grp_fu_574_p2[1:0];

assign empty_59_fu_660_p2 = ($signed(2'd2) - $signed(empty_58_fu_656_p1));

assign empty_60_fu_599_p2 = ($signed(tmp1_cast_fu_595_p1) + $signed(zext_ln62_cast_reg_1102));

assign empty_fu_543_p2 = ($signed(tmp_cast_fu_539_p1) + $signed(zext_ln43_cast_reg_1107));

assign fb_0_10_address0 = zext_ln65_fu_604_p1;

assign fb_0_11_address0 = zext_ln65_fu_604_p1;

assign fb_0_12_address0 = zext_ln65_fu_604_p1;

assign fb_0_13_address0 = zext_ln65_fu_604_p1;

assign fb_0_14_address0 = zext_ln65_fu_604_p1;

assign fb_0_15_address0 = zext_ln65_fu_604_p1;

assign fb_0_16_address0 = zext_ln65_fu_604_p1;

assign fb_0_17_address0 = zext_ln65_fu_604_p1;

assign fb_0_1_address0 = zext_ln65_fu_604_p1;

assign fb_0_2_address0 = zext_ln65_fu_604_p1;

assign fb_0_3_address0 = zext_ln65_fu_604_p1;

assign fb_0_4_address0 = zext_ln65_fu_604_p1;

assign fb_0_5_address0 = zext_ln65_fu_604_p1;

assign fb_0_6_address0 = zext_ln65_fu_604_p1;

assign fb_0_7_address0 = zext_ln65_fu_604_p1;

assign fb_0_8_address0 = zext_ln65_fu_604_p1;

assign fb_0_9_address0 = zext_ln65_fu_604_p1;

assign fb_0_address0 = zext_ln65_fu_604_p1;

assign grp_fu_574_p0 = $signed(p_smodpre16_fu_564_p2);

assign grp_fu_574_p1 = 32'd3;

assign icmp_ln65_fu_634_p2 = (($signed(empty_60_fu_599_p2) > $signed(4'd5)) ? 1'b1 : 1'b0);

assign icmp_ln89_fu_467_p2 = ((ap_sig_allocacmp_indvar_flatten25_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln90_fu_491_p2 = ((ap_sig_allocacmp_dy_load == 2'd3) ? 1'b1 : 1'b0);

assign in_bounds_1_fu_1045_p2 = (xor_ln65_fu_1020_p2 & cmp9_i_i_2);

assign in_bounds_fu_1025_p2 = (xor_ln65_fu_1020_p2 & cmp8_i_i);

assign or_ln65_1_fu_650_p2 = (or_ln65_fu_640_p2 | or_ln65_2_fu_645_p2);

assign or_ln65_2_fu_645_p2 = (tmp_358_reg_1129_pp0_iter34_reg | icmp_ln65_fu_634_p2);

assign or_ln65_fu_640_p2 = (tmp_359_fu_626_p3 | cmp2_i_i_not_reg_1140_pp0_iter34_reg);

assign p_cast119_fu_556_p3 = ((tmp_358_fu_548_p3[0:0] == 1'b1) ? 4'd15 : 4'd0);

assign p_smodpost17_fu_666_p3 = ((tmp_358_reg_1129_pp0_iter35_reg[0:0] == 1'b1) ? empty_59_fu_660_p2 : empty_58_fu_656_p1);

assign p_smodpre16_fu_564_p2 = (p_cast119_fu_556_p3 ^ empty_fu_543_p2);

assign select_ln89_1_fu_505_p3 = ((icmp_ln90_fu_491_p2[0:0] == 1'b1) ? add_ln89_fu_485_p2 : ap_sig_allocacmp_dz_load);

assign select_ln89_fu_497_p3 = ((icmp_ln90_fu_491_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_dy_load);

assign sub_ln97_fu_998_p2 = (tmp_3_fu_991_p3 - zext_ln97_fu_988_p1);

assign tmp1_cast_fu_595_p1 = $signed(tmp1_fu_589_p2);

assign tmp1_fu_589_p2 = ($signed(zext_ln90_fu_586_p1) + $signed(3'd7));

assign tmp_358_fu_548_p3 = empty_fu_543_p2[32'd3];

assign tmp_359_fu_626_p3 = empty_60_fu_599_p2[32'd3];

assign tmp_372_fu_700_p11 = 'bx;

assign tmp_373_fu_727_p11 = 'bx;

assign tmp_374_fu_754_p7 = 'bx;

assign tmp_375_fu_774_p13 = 'bx;

assign tmp_376_fu_805_p13 = 'bx;

assign tmp_377_fu_836_p13 = 'bx;

assign tmp_378_fu_867_p7 = 'bx;

assign tmp_379_fu_887_p11 = 'bx;

assign tmp_380_fu_914_p11 = 'bx;

assign tmp_381_fu_941_p11 = 'bx;

assign tmp_382_fu_968_p7 = 'bx;

assign tmp_3_fu_991_p3 = {{select_ln89_1_reg_1122_pp0_iter36_reg}, {2'd0}};

assign tmp_cast_fu_539_p1 = $signed(tmp_fu_534_p2);

assign tmp_fu_534_p2 = (select_ln89_1_reg_1122 ^ 2'd2);

assign tmp_s_fu_673_p11 = 'bx;

assign window_0_1_address0 = zext_ln97_2_fu_1013_p1;

assign window_0_1_d0 = ((or_ln65_1_reg_1145_pp0_iter36_reg[0:0] == 1'b1) ? 8'd0 : tmp_378_reg_1246);

assign window_0_2_address0 = zext_ln97_2_fu_1013_p1;

assign window_0_2_d0 = ((in_bounds_1_fu_1045_p2[0:0] == 1'b1) ? tmp_382_reg_1251 : 8'd0);

assign window_0_address0 = zext_ln97_2_fu_1013_p1;

assign window_0_d0 = ((in_bounds_fu_1025_p2[0:0] == 1'b1) ? tmp_374_reg_1241 : 8'd0);

assign xor_ln65_fu_1020_p2 = (or_ln65_1_reg_1145_pp0_iter36_reg ^ 1'd1);

assign zext_ln43_cast_fu_445_p1 = zext_ln43;

assign zext_ln62_cast_fu_441_p1 = zext_ln62;

assign zext_ln65_fu_604_p1 = empty_60_fu_599_p2;

assign zext_ln90_fu_586_p1 = select_ln89_reg_1116_pp0_iter34_reg;

assign zext_ln97_1_fu_1004_p1 = select_ln89_reg_1116_pp0_iter36_reg;

assign zext_ln97_2_fu_1013_p1 = add_ln97_fu_1007_p2;

assign zext_ln97_fu_988_p1 = select_ln89_1_reg_1122_pp0_iter36_reg;

always @ (posedge ap_clk) begin
    zext_ln62_cast_reg_1102[3] <= 1'b0;
    zext_ln43_cast_reg_1107[3] <= 1'b0;
end

endmodule //predecoder_kernel_conv3d_hidden_layer_1_Pipeline_VITIS_LOOP_89_1_VITIS_LOOP_90_2
