set SynModuleInfo {
  {SRCNAME entry_proc MODELNAME entry_proc RTLNAME predecoder_kernel_entry_proc}
  {SRCNAME Block_entry1_proc MODELNAME Block_entry1_proc RTLNAME predecoder_kernel_Block_entry1_proc}
  {SRCNAME unpack_input MODELNAME unpack_input RTLNAME predecoder_kernel_unpack_input
    SUBMODULES {
      {MODELNAME predecoder_kernel_flow_control_loop_pipe RTLNAME predecoder_kernel_flow_control_loop_pipe BINDTYPE interface TYPE internal_upc_flow_control INSTNAME predecoder_kernel_flow_control_loop_pipe_U}
    }
  }
  {SRCNAME conv3d_hidden_layer<1>_Pipeline_RESET_VITIS_LOOP_40_1_VITIS_LOOP_41_2 MODELNAME conv3d_hidden_layer_1_Pipeline_RESET_VITIS_LOOP_40_1_VITIS_LOOP_41_2 RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_RESET_VITIS_LOOP_40_1_VITIS_LOOP_41_2
    SUBMODULES {
      {MODELNAME predecoder_kernel_flow_control_loop_pipe_sequential_init RTLNAME predecoder_kernel_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME predecoder_kernel_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME conv3d_hidden_layer<1>_Pipeline_VITIS_LOOP_46_1_VITIS_LOOP_47_2 MODELNAME conv3d_hidden_layer_1_Pipeline_VITIS_LOOP_46_1_VITIS_LOOP_47_2 RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_VITIS_LOOP_46_1_VITIS_LOOP_47_2}
  {SRCNAME conv3d_hidden_layer<1>_Pipeline_VITIS_LOOP_89_1_VITIS_LOOP_90_2 MODELNAME conv3d_hidden_layer_1_Pipeline_VITIS_LOOP_89_1_VITIS_LOOP_90_2 RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_VITIS_LOOP_89_1_VITIS_LOOP_90_2
    SUBMODULES {
      {MODELNAME predecoder_kernel_urem_32s_3ns_2_36_1 RTLNAME predecoder_kernel_urem_32s_3ns_2_36_1 BINDTYPE op TYPE urem IMPL auto LATENCY 35 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_sparsemux_11_3_8_1_1 RTLNAME predecoder_kernel_sparsemux_11_3_8_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
      {MODELNAME predecoder_kernel_sparsemux_7_2_8_1_1 RTLNAME predecoder_kernel_sparsemux_7_2_8_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
      {MODELNAME predecoder_kernel_sparsemux_13_3_8_1_1 RTLNAME predecoder_kernel_sparsemux_13_3_8_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
    }
  }
  {SRCNAME conv3d_hidden_layer<1>_Pipeline_OC_LOOP MODELNAME conv3d_hidden_layer_1_Pipeline_OC_LOOP RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP
    SUBMODULES {
      {MODELNAME predecoder_kernel_mul_76ns_57ns_132_5_1 RTLNAME predecoder_kernel_mul_76ns_57ns_132_5_1 BINDTYPE op TYPE mul IMPL auto LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mul_8s_8ns_16_1_1 RTLNAME predecoder_kernel_mul_8s_8ns_16_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8s_8ns_16s_17_4_1 RTLNAME predecoder_kernel_mac_muladd_8s_8ns_16s_17_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8ns_6s_16s_17_4_1 RTLNAME predecoder_kernel_mac_muladd_8ns_6s_16s_17_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8ns_7s_16s_17_4_1 RTLNAME predecoder_kernel_mac_muladd_8ns_7s_16s_17_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8s_8ns_17s_17_4_1 RTLNAME predecoder_kernel_mac_muladd_8s_8ns_17s_17_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8s_8ns_17s_18_4_1 RTLNAME predecoder_kernel_mac_muladd_8s_8ns_17s_18_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8ns_7s_9s_15_4_1 RTLNAME predecoder_kernel_mac_muladd_8ns_7s_9s_15_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8s_8ns_20s_20_4_1 RTLNAME predecoder_kernel_mac_muladd_8s_8ns_20s_20_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGbkb RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGbkb BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGcud RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGcud BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGdEe RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGdEe BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGeOg RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGeOg BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGfYi RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGfYi BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGg8j RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGg8j BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGhbi RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGhbi BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGibs RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGibs BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGjbC RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGjbC BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGkbM RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGkbM BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGlbW RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGlbW BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGmb6 RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGmb6 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGncg RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGncg BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGocq RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGocq BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGpcA RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGpcA BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGqcK RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGqcK BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGrcU RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGrcU BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGsc4 RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGsc4 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGtde RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGtde BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGudo RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGudo BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGvdy RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGvdy BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGwdI RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGwdI BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGxdS RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGxdS BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGyd2 RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGyd2 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGzec RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGzec BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGAem RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGAem BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGBew RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGBew BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_predecoder_weights_LAYER0_BIAS_ROM_AUTCeG RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_predecoder_weights_LAYER0_BIAS_ROM_AUTCeG BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_layer0_mult_ROM_AUTO_1R RTLNAME predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_layer0_mult_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME conv3d_hidden_layer<1> MODELNAME conv3d_hidden_layer_1_s RTLNAME predecoder_kernel_conv3d_hidden_layer_1_s
    SUBMODULES {
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_s_fb_0_RAM_AUTO_1R1W RTLNAME predecoder_kernel_conv3d_hidden_layer_1_s_fb_0_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_s_window_0_RAM_AUTO_1R1W RTLNAME predecoder_kernel_conv3d_hidden_layer_1_s_window_0_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_1_s_out_RAM_AUTO_1R1W RTLNAME predecoder_kernel_conv3d_hidden_layer_1_s_out_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME conv3d_hidden_layer_Pipeline_RESET_VITIS_LOOP_40_1_VITIS_LOOP_41_2_VITIS_LOOP_42 MODELNAME conv3d_hidden_layer_Pipeline_RESET_VITIS_LOOP_40_1_VITIS_LOOP_41_2_VITIS_LOOP_42 RTLNAME predecoder_kernel_conv3d_hidden_layer_Pipeline_RESET_VITIS_LOOP_40_1_VITIS_LOOP_41_2_VITIS_LOOP_42}
  {SRCNAME conv3d_hidden_layer<12>_Pipeline_VITIS_LOOP_46_1_VITIS_LOOP_47_2 MODELNAME conv3d_hidden_layer_12_Pipeline_VITIS_LOOP_46_1_VITIS_LOOP_47_2 RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_VITIS_LOOP_46_1_VITIS_LOOP_47_2}
  {SRCNAME conv3d_hidden_layer<12>_Pipeline_VITIS_LOOP_89_1_VITIS_LOOP_90_2 MODELNAME conv3d_hidden_layer_12_Pipeline_VITIS_LOOP_89_1_VITIS_LOOP_90_2 RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_VITIS_LOOP_89_1_VITIS_LOOP_90_2}
  {SRCNAME conv3d_hidden_layer<12>_Pipeline_IC_LOOP MODELNAME conv3d_hidden_layer_12_Pipeline_IC_LOOP RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP
    SUBMODULES {
      {MODELNAME predecoder_kernel_sparsemux_25_4_8_1_1 RTLNAME predecoder_kernel_sparsemux_25_4_8_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
      {MODELNAME predecoder_kernel_mac_muladd_8ns_8s_20s_20_4_1 RTLNAME predecoder_kernel_mac_muladd_8ns_8s_20s_20_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIDeQ RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIDeQ BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIEe0 RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIEe0 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIFfa RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIFfa BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIGfk RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIGfk BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIHfu RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIHfu BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIIfE RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIIfE BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIJfO RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIJfO BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIKfY RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIKfY BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEILf8 RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEILf8 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIMgi RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIMgi BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEINgs RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEINgs BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIOgC RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIOgC BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIPgM RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIPgM BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIQgW RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIQgW BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIRg6 RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIRg6 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIShg RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIShg BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIThq RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIThq BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIUhA RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIUhA BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIVhK RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIVhK BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIWhU RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIWhU BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIXh4 RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIXh4 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIYie RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIYie BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIZio RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEIZio BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEI0iy RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEI0iy BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEI1iI RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEI1iI BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEI2iS RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEI2iS BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEI3i2 RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_IC_LOOP_p_ZN18predecoder_weightsL13LAYER1_WEI3i2 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME conv3d_hidden_layer<12>_Pipeline_SUM_PARTIAL_VITIS_LOOP_109_9 MODELNAME conv3d_hidden_layer_12_Pipeline_SUM_PARTIAL_VITIS_LOOP_109_9 RTLNAME predecoder_kernel_conv3d_hidden_layer_12_Pipeline_SUM_PARTIAL_VITIS_LOOP_109_9
    SUBMODULES {
      {MODELNAME predecoder_kernel_sparsemux_7_2_20_1_1 RTLNAME predecoder_kernel_sparsemux_7_2_20_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
    }
  }
  {SRCNAME conv3d_hidden_layer<12> MODELNAME conv3d_hidden_layer_12_s RTLNAME predecoder_kernel_conv3d_hidden_layer_12_s
    SUBMODULES {
      {MODELNAME predecoder_kernel_mul_87ns_49ns_136_5_1 RTLNAME predecoder_kernel_mul_87ns_49ns_136_5_1 BINDTYPE op TYPE mul IMPL auto LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_s_predecoder_weights_LAYER1_BIAS_ROM_AUTO_1R RTLNAME predecoder_kernel_conv3d_hidden_layer_12_s_predecoder_weights_LAYER1_BIAS_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_s_layer1_mult_ROM_AUTO_1R RTLNAME predecoder_kernel_conv3d_hidden_layer_12_s_layer1_mult_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_conv3d_hidden_layer_12_s_fb_RAM_AUTO_1R1W RTLNAME predecoder_kernel_conv3d_hidden_layer_12_s_fb_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME conv1x1_output_layer MODELNAME conv1x1_output_layer RTLNAME predecoder_kernel_conv1x1_output_layer
    SUBMODULES {
      {MODELNAME predecoder_kernel_mul_8ns_8s_16_1_1 RTLNAME predecoder_kernel_mul_8ns_8s_16_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8ns_6s_16s_16_4_1 RTLNAME predecoder_kernel_mac_muladd_8ns_6s_16s_16_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8ns_7s_11s_15_4_1 RTLNAME predecoder_kernel_mac_muladd_8ns_7s_11s_15_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8ns_8s_13ns_16_4_1 RTLNAME predecoder_kernel_mac_muladd_8ns_8s_13ns_16_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8ns_6ns_16ns_16_4_1 RTLNAME predecoder_kernel_mac_muladd_8ns_6ns_16ns_16_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8ns_6s_15s_16_4_1 RTLNAME predecoder_kernel_mac_muladd_8ns_6s_15s_16_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8ns_8s_14s_16_4_1 RTLNAME predecoder_kernel_mac_muladd_8ns_8s_14s_16_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8ns_5ns_13s_14_4_1 RTLNAME predecoder_kernel_mac_muladd_8ns_5ns_13s_14_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8ns_7ns_18ns_18_4_1 RTLNAME predecoder_kernel_mac_muladd_8ns_7ns_18ns_18_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8ns_8s_16s_17_4_1 RTLNAME predecoder_kernel_mac_muladd_8ns_8s_16s_17_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8ns_8s_18s_19_4_1 RTLNAME predecoder_kernel_mac_muladd_8ns_8s_18s_19_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mac_muladd_8ns_7s_14s_16_4_1 RTLNAME predecoder_kernel_mac_muladd_8ns_7s_14s_16_4_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME edge_correction_Pipeline_INIT_VITIS_LOOP_167_1_VITIS_LOOP_168_2 MODELNAME edge_correction_Pipeline_INIT_VITIS_LOOP_167_1_VITIS_LOOP_168_2 RTLNAME predecoder_kernel_edge_correction_Pipeline_INIT_VITIS_LOOP_167_1_VITIS_LOOP_168_2}
  {SRCNAME edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4 MODELNAME edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4 RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4
    SUBMODULES {
      {MODELNAME predecoder_kernel_mul_64ns_66ns_129_5_1 RTLNAME predecoder_kernel_mul_64ns_66ns_129_5_1 BINDTYPE op TYPE mul IMPL auto LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_urem_64s_6ns_5_68_1 RTLNAME predecoder_kernel_urem_64s_6ns_5_68_1 BINDTYPE op TYPE urem IMPL auto LATENCY 67 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_sparsemux_13_3_1_1_1 RTLNAME predecoder_kernel_sparsemux_13_3_1_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
      {MODELNAME predecoder_kernel_mul_9ns_11ns_19_1_1 RTLNAME predecoder_kernel_mul_9ns_11ns_19_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_sparsemux_11_3_1_1_1 RTLNAME predecoder_kernel_sparsemux_11_3_1_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
      {MODELNAME predecoder_kernel_mul_10ns_12ns_21_1_1 RTLNAME predecoder_kernel_mul_10ns_12ns_21_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_mul_11ns_13ns_23_1_1 RTLNAME predecoder_kernel_mul_11ns_13ns_23_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_sparsemux_9_3_1_1_1 RTLNAME predecoder_kernel_sparsemux_9_3_1_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
      {MODELNAME predecoder_kernel_mul_12ns_14ns_25_1_1 RTLNAME predecoder_kernel_mul_12ns_14ns_25_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_sparsemux_35_5_1_1_1 RTLNAME predecoder_kernel_sparsemux_35_5_1_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24pred4jc RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24pred4jc BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24pred5jm RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24pred5jm BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24pred6jw RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24pred6jw BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24pred7jG RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24pred7jG BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24pred8jQ RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24pred8jQ BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24pred9j0 RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24pred9j0 BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbak RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbak BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbbk RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbbk BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbck RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbck BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbdk RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbdk BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbek RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbek BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbfk RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbfk BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbgk RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbgk BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbhl RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbhl BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbil RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbil BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbjl RTLNAME predecoder_kernel_edge_correction_Pipeline_EC_LOOP_VITIS_LOOP_174_3_VITIS_LOOP_175_4_p_ZN24predbjl BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME edge_correction_Pipeline_VITIS_LOOP_213_5_VITIS_LOOP_214_6_VITIS_LOOP_215_7 MODELNAME edge_correction_Pipeline_VITIS_LOOP_213_5_VITIS_LOOP_214_6_VITIS_LOOP_215_7 RTLNAME predecoder_kernel_edge_correction_Pipeline_VITIS_LOOP_213_5_VITIS_LOOP_214_6_VITIS_LOOP_215_7}
  {SRCNAME edge_correction MODELNAME edge_correction RTLNAME predecoder_kernel_edge_correction
    SUBMODULES {
      {MODELNAME predecoder_kernel_edge_correction_correction_RAM_AUTO_1R1W RTLNAME predecoder_kernel_edge_correction_correction_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME Block_entry17_proc MODELNAME Block_entry17_proc RTLNAME predecoder_kernel_Block_entry17_proc}
  {SRCNAME predecoder_kernel MODELNAME predecoder_kernel RTLNAME predecoder_kernel IS_TOP 1
    SUBMODULES {
      {MODELNAME predecoder_kernel_fifo_w64_d8_S RTLNAME predecoder_kernel_fifo_w64_d8_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME correction_hbm_c_U}
      {MODELNAME predecoder_kernel_fifo_w512_d2_S RTLNAME predecoder_kernel_fifo_w512_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME in_beat_channel_U}
      {MODELNAME predecoder_kernel_fifo_w96_d8_S RTLNAME predecoder_kernel_fifo_w96_d8_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME s0_U}
      {MODELNAME predecoder_kernel_fifo_w96_d8_S RTLNAME predecoder_kernel_fifo_w96_d8_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME s1_U}
      {MODELNAME predecoder_kernel_fifo_w96_d8_S RTLNAME predecoder_kernel_fifo_w96_d8_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME s2_U}
      {MODELNAME predecoder_kernel_fifo_w448_d8_A RTLNAME predecoder_kernel_fifo_w448_d8_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME s3_U}
      {MODELNAME predecoder_kernel_fifo_w512_d2_S RTLNAME predecoder_kernel_fifo_w512_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME out_beat_U}
      {MODELNAME predecoder_kernel_start_for_conv3d_hidden_layer_1_U0 RTLNAME predecoder_kernel_start_for_conv3d_hidden_layer_1_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_conv3d_hidden_layer_1_U0_U}
      {MODELNAME predecoder_kernel_start_for_conv3d_hidden_layer_12_U0 RTLNAME predecoder_kernel_start_for_conv3d_hidden_layer_12_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_conv3d_hidden_layer_12_U0_U}
      {MODELNAME predecoder_kernel_start_for_conv1x1_output_layer_U0 RTLNAME predecoder_kernel_start_for_conv1x1_output_layer_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_conv1x1_output_layer_U0_U}
      {MODELNAME predecoder_kernel_start_for_edge_correction_U0 RTLNAME predecoder_kernel_start_for_edge_correction_U0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME start_for_edge_correction_U0_U}
      {MODELNAME predecoder_kernel_gmem0_m_axi RTLNAME predecoder_kernel_gmem0_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME predecoder_kernel_gmem1_m_axi RTLNAME predecoder_kernel_gmem1_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME predecoder_kernel_control_s_axi RTLNAME predecoder_kernel_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
