-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity predecoder_kernel_conv3d_hidden_layer_12_Pipeline_SUM_PARTIAL_VITIS_LOOP_109_9 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    acc_cast : IN STD_LOGIC_VECTOR (13 downto 0);
    conv3_i203_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_1116206_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_2131209_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_1212_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_1_1215_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_1_2218_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_2221_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_2_1224_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_2_2227_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_1148204_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_1116_1207_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_2131_1210_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_1_188213_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_1_1_1216_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_1_2_1219_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_2_162222_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_2_1_1225_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_2_2_1228_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_2161205_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_1116_2208_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_2131_2211_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_1_2101214_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_1_1_2217_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_1_2_2220_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_2_275223_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_2_1_2226_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    conv3_i_2_2_2229_reload : IN STD_LOGIC_VECTOR (19 downto 0);
    acc_3_out : OUT STD_LOGIC_VECTOR (24 downto 0);
    acc_3_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of predecoder_kernel_conv3d_hidden_layer_12_Pipeline_SUM_PARTIAL_VITIS_LOOP_109_9 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln108_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal tmp_510_fu_424_p9 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_510_reg_705 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln112_fu_612_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln112_reg_710 : STD_LOGIC_VECTOR (20 downto 0);
    signal acc_fu_100 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    signal acc_3_fu_658_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal acc_cast_cast_fu_291_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal dy_fu_104 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal add_ln109_fu_618_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_dy_load : STD_LOGIC_VECTOR (1 downto 0);
    signal dz_fu_108 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal select_ln108_fu_356_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_dz_load : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten54_fu_112 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln108_1_fu_324_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten54_load : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln109_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln108_fu_336_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_507_fu_364_p7 : STD_LOGIC_VECTOR (19 downto 0);
    signal select_ln106_fu_348_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_508_fu_384_p7 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_509_fu_404_p7 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_507_fu_364_p9 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_508_fu_384_p9 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_509_fu_404_p9 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_510_fu_424_p7 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_511_fu_444_p7 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_512_fu_464_p7 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_513_fu_484_p7 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_511_fu_444_p9 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_512_fu_464_p9 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_513_fu_484_p9 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_514_fu_504_p7 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_514_fu_504_p9 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_515_fu_528_p7 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_516_fu_548_p7 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_517_fu_568_p7 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_515_fu_528_p9 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_516_fu_548_p9 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_517_fu_568_p9 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_518_fu_588_p7 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_518_fu_588_p9 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln112_18_fu_524_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln112_19_fu_608_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln112_20_fu_645_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln112_fu_642_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln112_27_fu_648_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln112_21_fu_654_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal tmp_507_fu_364_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_507_fu_364_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_507_fu_364_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_508_fu_384_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_508_fu_384_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_508_fu_384_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_509_fu_404_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_509_fu_404_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_509_fu_404_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_510_fu_424_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_510_fu_424_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_510_fu_424_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_511_fu_444_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_511_fu_444_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_511_fu_444_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_512_fu_464_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_512_fu_464_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_512_fu_464_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_513_fu_484_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_513_fu_484_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_513_fu_484_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_514_fu_504_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_514_fu_504_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_514_fu_504_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_515_fu_528_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_515_fu_528_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_515_fu_528_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_516_fu_548_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_516_fu_548_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_516_fu_548_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_517_fu_568_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_517_fu_568_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_517_fu_568_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_518_fu_588_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_518_fu_588_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_518_fu_588_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component predecoder_kernel_sparsemux_7_2_20_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (19 downto 0);
        din1 : IN STD_LOGIC_VECTOR (19 downto 0);
        din2 : IN STD_LOGIC_VECTOR (19 downto 0);
        def : IN STD_LOGIC_VECTOR (19 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (19 downto 0) );
    end component;


    component predecoder_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_7_2_20_1_1_U2071 : component predecoder_kernel_sparsemux_7_2_20_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 20,
        CASE1 => "01",
        din1_WIDTH => 20,
        CASE2 => "10",
        din2_WIDTH => 20,
        def_WIDTH => 20,
        sel_WIDTH => 2,
        dout_WIDTH => 20)
    port map (
        din0 => conv3_i203_reload,
        din1 => conv3_i_1116206_reload,
        din2 => conv3_i_2131209_reload,
        def => tmp_507_fu_364_p7,
        sel => select_ln106_fu_348_p3,
        dout => tmp_507_fu_364_p9);

    sparsemux_7_2_20_1_1_U2072 : component predecoder_kernel_sparsemux_7_2_20_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 20,
        CASE1 => "01",
        din1_WIDTH => 20,
        CASE2 => "10",
        din2_WIDTH => 20,
        def_WIDTH => 20,
        sel_WIDTH => 2,
        dout_WIDTH => 20)
    port map (
        din0 => conv3_i_1212_reload,
        din1 => conv3_i_1_1215_reload,
        din2 => conv3_i_1_2218_reload,
        def => tmp_508_fu_384_p7,
        sel => select_ln106_fu_348_p3,
        dout => tmp_508_fu_384_p9);

    sparsemux_7_2_20_1_1_U2073 : component predecoder_kernel_sparsemux_7_2_20_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 20,
        CASE1 => "01",
        din1_WIDTH => 20,
        CASE2 => "10",
        din2_WIDTH => 20,
        def_WIDTH => 20,
        sel_WIDTH => 2,
        dout_WIDTH => 20)
    port map (
        din0 => conv3_i_2221_reload,
        din1 => conv3_i_2_1224_reload,
        din2 => conv3_i_2_2227_reload,
        def => tmp_509_fu_404_p7,
        sel => select_ln106_fu_348_p3,
        dout => tmp_509_fu_404_p9);

    sparsemux_7_2_20_1_1_U2074 : component predecoder_kernel_sparsemux_7_2_20_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 20,
        CASE1 => "01",
        din1_WIDTH => 20,
        CASE2 => "10",
        din2_WIDTH => 20,
        def_WIDTH => 20,
        sel_WIDTH => 2,
        dout_WIDTH => 20)
    port map (
        din0 => tmp_507_fu_364_p9,
        din1 => tmp_508_fu_384_p9,
        din2 => tmp_509_fu_404_p9,
        def => tmp_510_fu_424_p7,
        sel => select_ln108_fu_356_p3,
        dout => tmp_510_fu_424_p9);

    sparsemux_7_2_20_1_1_U2075 : component predecoder_kernel_sparsemux_7_2_20_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 20,
        CASE1 => "01",
        din1_WIDTH => 20,
        CASE2 => "10",
        din2_WIDTH => 20,
        def_WIDTH => 20,
        sel_WIDTH => 2,
        dout_WIDTH => 20)
    port map (
        din0 => conv3_i_1148204_reload,
        din1 => conv3_i_1116_1207_reload,
        din2 => conv3_i_2131_1210_reload,
        def => tmp_511_fu_444_p7,
        sel => select_ln106_fu_348_p3,
        dout => tmp_511_fu_444_p9);

    sparsemux_7_2_20_1_1_U2076 : component predecoder_kernel_sparsemux_7_2_20_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 20,
        CASE1 => "01",
        din1_WIDTH => 20,
        CASE2 => "10",
        din2_WIDTH => 20,
        def_WIDTH => 20,
        sel_WIDTH => 2,
        dout_WIDTH => 20)
    port map (
        din0 => conv3_i_1_188213_reload,
        din1 => conv3_i_1_1_1216_reload,
        din2 => conv3_i_1_2_1219_reload,
        def => tmp_512_fu_464_p7,
        sel => select_ln106_fu_348_p3,
        dout => tmp_512_fu_464_p9);

    sparsemux_7_2_20_1_1_U2077 : component predecoder_kernel_sparsemux_7_2_20_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 20,
        CASE1 => "01",
        din1_WIDTH => 20,
        CASE2 => "10",
        din2_WIDTH => 20,
        def_WIDTH => 20,
        sel_WIDTH => 2,
        dout_WIDTH => 20)
    port map (
        din0 => conv3_i_2_162222_reload,
        din1 => conv3_i_2_1_1225_reload,
        din2 => conv3_i_2_2_1228_reload,
        def => tmp_513_fu_484_p7,
        sel => select_ln106_fu_348_p3,
        dout => tmp_513_fu_484_p9);

    sparsemux_7_2_20_1_1_U2078 : component predecoder_kernel_sparsemux_7_2_20_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 20,
        CASE1 => "01",
        din1_WIDTH => 20,
        CASE2 => "10",
        din2_WIDTH => 20,
        def_WIDTH => 20,
        sel_WIDTH => 2,
        dout_WIDTH => 20)
    port map (
        din0 => tmp_511_fu_444_p9,
        din1 => tmp_512_fu_464_p9,
        din2 => tmp_513_fu_484_p9,
        def => tmp_514_fu_504_p7,
        sel => select_ln108_fu_356_p3,
        dout => tmp_514_fu_504_p9);

    sparsemux_7_2_20_1_1_U2079 : component predecoder_kernel_sparsemux_7_2_20_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 20,
        CASE1 => "01",
        din1_WIDTH => 20,
        CASE2 => "10",
        din2_WIDTH => 20,
        def_WIDTH => 20,
        sel_WIDTH => 2,
        dout_WIDTH => 20)
    port map (
        din0 => conv3_i_2161205_reload,
        din1 => conv3_i_1116_2208_reload,
        din2 => conv3_i_2131_2211_reload,
        def => tmp_515_fu_528_p7,
        sel => select_ln106_fu_348_p3,
        dout => tmp_515_fu_528_p9);

    sparsemux_7_2_20_1_1_U2080 : component predecoder_kernel_sparsemux_7_2_20_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 20,
        CASE1 => "01",
        din1_WIDTH => 20,
        CASE2 => "10",
        din2_WIDTH => 20,
        def_WIDTH => 20,
        sel_WIDTH => 2,
        dout_WIDTH => 20)
    port map (
        din0 => conv3_i_1_2101214_reload,
        din1 => conv3_i_1_1_2217_reload,
        din2 => conv3_i_1_2_2220_reload,
        def => tmp_516_fu_548_p7,
        sel => select_ln106_fu_348_p3,
        dout => tmp_516_fu_548_p9);

    sparsemux_7_2_20_1_1_U2081 : component predecoder_kernel_sparsemux_7_2_20_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 20,
        CASE1 => "01",
        din1_WIDTH => 20,
        CASE2 => "10",
        din2_WIDTH => 20,
        def_WIDTH => 20,
        sel_WIDTH => 2,
        dout_WIDTH => 20)
    port map (
        din0 => conv3_i_2_275223_reload,
        din1 => conv3_i_2_1_2226_reload,
        din2 => conv3_i_2_2_2229_reload,
        def => tmp_517_fu_568_p7,
        sel => select_ln106_fu_348_p3,
        dout => tmp_517_fu_568_p9);

    sparsemux_7_2_20_1_1_U2082 : component predecoder_kernel_sparsemux_7_2_20_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 20,
        CASE1 => "01",
        din1_WIDTH => 20,
        CASE2 => "10",
        din2_WIDTH => 20,
        def_WIDTH => 20,
        sel_WIDTH => 2,
        dout_WIDTH => 20)
    port map (
        din0 => tmp_515_fu_528_p9,
        din1 => tmp_516_fu_548_p9,
        din2 => tmp_517_fu_568_p9,
        def => tmp_518_fu_588_p7,
        sel => select_ln108_fu_356_p3,
        dout => tmp_518_fu_588_p9);

    flow_control_loop_pipe_sequential_init_U : component predecoder_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    acc_fu_100 <= acc_cast_cast_fu_291_p1;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    acc_fu_100 <= acc_3_fu_658_p2;
                end if;
            end if; 
        end if;
    end process;

    dy_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln108_fu_318_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    dy_fu_104 <= add_ln109_fu_618_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    dy_fu_104 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    dz_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln108_fu_318_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    dz_fu_108 <= select_ln108_fu_356_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    dz_fu_108 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten54_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln108_fu_318_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten54_fu_112 <= add_ln108_1_fu_324_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten54_fu_112 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln112_reg_710 <= add_ln112_fu_612_p2;
                tmp_510_reg_705 <= tmp_510_fu_424_p9;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_3_fu_658_p2 <= std_logic_vector(unsigned(acc_fu_100) + unsigned(sext_ln112_21_fu_654_p1));
    acc_3_out <= acc_fu_100;

    acc_3_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln108_fu_318_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln108_fu_318_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_3_out_ap_vld <= ap_const_logic_1;
        else 
            acc_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

        acc_cast_cast_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_cast),25));

    add_ln108_1_fu_324_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten54_load) + unsigned(ap_const_lv4_1));
    add_ln108_fu_336_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_dz_load) + unsigned(ap_const_lv2_1));
    add_ln109_fu_618_p2 <= std_logic_vector(unsigned(select_ln106_fu_348_p3) + unsigned(ap_const_lv2_1));
    add_ln112_27_fu_648_p2 <= std_logic_vector(signed(sext_ln112_20_fu_645_p1) + signed(sext_ln112_fu_642_p1));
    add_ln112_fu_612_p2 <= std_logic_vector(signed(sext_ln112_18_fu_524_p1) + signed(sext_ln112_19_fu_608_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln108_fu_318_p2)
    begin
        if (((icmp_ln108_fu_318_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_dy_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, dy_fu_104)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_dy_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_dy_load <= dy_fu_104;
        end if; 
    end process;


    ap_sig_allocacmp_dz_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, dz_fu_108)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_dz_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_dz_load <= dz_fu_108;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten54_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten54_fu_112)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten54_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten54_load <= indvar_flatten54_fu_112;
        end if; 
    end process;

    icmp_ln108_fu_318_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten54_load = ap_const_lv4_9) else "0";
    icmp_ln109_fu_342_p2 <= "1" when (ap_sig_allocacmp_dy_load = ap_const_lv2_3) else "0";
    select_ln106_fu_348_p3 <= 
        ap_const_lv2_0 when (icmp_ln109_fu_342_p2(0) = '1') else 
        ap_sig_allocacmp_dy_load;
    select_ln108_fu_356_p3 <= 
        add_ln108_fu_336_p2 when (icmp_ln109_fu_342_p2(0) = '1') else 
        ap_sig_allocacmp_dz_load;
        sext_ln112_18_fu_524_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_514_fu_504_p9),21));

        sext_ln112_19_fu_608_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_518_fu_588_p9),21));

        sext_ln112_20_fu_645_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln112_reg_710),22));

        sext_ln112_21_fu_654_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln112_27_fu_648_p2),25));

        sext_ln112_fu_642_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_510_reg_705),22));

    tmp_507_fu_364_p7 <= "XXXXXXXXXXXXXXXXXXXX";
    tmp_508_fu_384_p7 <= "XXXXXXXXXXXXXXXXXXXX";
    tmp_509_fu_404_p7 <= "XXXXXXXXXXXXXXXXXXXX";
    tmp_510_fu_424_p7 <= "XXXXXXXXXXXXXXXXXXXX";
    tmp_511_fu_444_p7 <= "XXXXXXXXXXXXXXXXXXXX";
    tmp_512_fu_464_p7 <= "XXXXXXXXXXXXXXXXXXXX";
    tmp_513_fu_484_p7 <= "XXXXXXXXXXXXXXXXXXXX";
    tmp_514_fu_504_p7 <= "XXXXXXXXXXXXXXXXXXXX";
    tmp_515_fu_528_p7 <= "XXXXXXXXXXXXXXXXXXXX";
    tmp_516_fu_548_p7 <= "XXXXXXXXXXXXXXXXXXXX";
    tmp_517_fu_568_p7 <= "XXXXXXXXXXXXXXXXXXXX";
    tmp_518_fu_588_p7 <= "XXXXXXXXXXXXXXXXXXXX";
end behav;
