-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGlbW is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 12
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of predecoder_kernel_conv3d_hidden_layer_1_Pipeline_OC_LOOP_p_ZN18predecoder_weightsL13LAYER0_WEIGlbW is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10001111", 1 => "00100111", 2 => "11110001", 3 => "00100100", 
    4 => "00010100", 5 => "10000001", 6 => "01000111", 7 => "01011011", 
    8 => "10100100", 9 => "11111011", 10 => "11110011", 11 => "00010110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

