// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module predecoder_kernel_conv3d_hidden_layer_12_Pipeline_SUM_PARTIAL_VITIS_LOOP_109_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        acc_cast,
        conv3_i203_reload,
        conv3_i_1116206_reload,
        conv3_i_2131209_reload,
        conv3_i_1212_reload,
        conv3_i_1_1215_reload,
        conv3_i_1_2218_reload,
        conv3_i_2221_reload,
        conv3_i_2_1224_reload,
        conv3_i_2_2227_reload,
        conv3_i_1148204_reload,
        conv3_i_1116_1207_reload,
        conv3_i_2131_1210_reload,
        conv3_i_1_188213_reload,
        conv3_i_1_1_1216_reload,
        conv3_i_1_2_1219_reload,
        conv3_i_2_162222_reload,
        conv3_i_2_1_1225_reload,
        conv3_i_2_2_1228_reload,
        conv3_i_2161205_reload,
        conv3_i_1116_2208_reload,
        conv3_i_2131_2211_reload,
        conv3_i_1_2101214_reload,
        conv3_i_1_1_2217_reload,
        conv3_i_1_2_2220_reload,
        conv3_i_2_275223_reload,
        conv3_i_2_1_2226_reload,
        conv3_i_2_2_2229_reload,
        acc_3_out,
        acc_3_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [13:0] acc_cast;
input  [19:0] conv3_i203_reload;
input  [19:0] conv3_i_1116206_reload;
input  [19:0] conv3_i_2131209_reload;
input  [19:0] conv3_i_1212_reload;
input  [19:0] conv3_i_1_1215_reload;
input  [19:0] conv3_i_1_2218_reload;
input  [19:0] conv3_i_2221_reload;
input  [19:0] conv3_i_2_1224_reload;
input  [19:0] conv3_i_2_2227_reload;
input  [19:0] conv3_i_1148204_reload;
input  [19:0] conv3_i_1116_1207_reload;
input  [19:0] conv3_i_2131_1210_reload;
input  [19:0] conv3_i_1_188213_reload;
input  [19:0] conv3_i_1_1_1216_reload;
input  [19:0] conv3_i_1_2_1219_reload;
input  [19:0] conv3_i_2_162222_reload;
input  [19:0] conv3_i_2_1_1225_reload;
input  [19:0] conv3_i_2_2_1228_reload;
input  [19:0] conv3_i_2161205_reload;
input  [19:0] conv3_i_1116_2208_reload;
input  [19:0] conv3_i_2131_2211_reload;
input  [19:0] conv3_i_1_2101214_reload;
input  [19:0] conv3_i_1_1_2217_reload;
input  [19:0] conv3_i_1_2_2220_reload;
input  [19:0] conv3_i_2_275223_reload;
input  [19:0] conv3_i_2_1_2226_reload;
input  [19:0] conv3_i_2_2_2229_reload;
output  [24:0] acc_3_out;
output   acc_3_out_ap_vld;

reg ap_idle;
reg acc_3_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln108_fu_318_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [19:0] tmp_510_fu_424_p9;
reg   [19:0] tmp_510_reg_705;
wire    ap_block_pp0_stage0_11001;
wire   [20:0] add_ln112_fu_612_p2;
reg   [20:0] add_ln112_reg_710;
reg   [24:0] acc_fu_100;
wire   [24:0] acc_3_fu_658_p2;
wire  signed [24:0] acc_cast_cast_fu_291_p1;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
reg   [1:0] dy_fu_104;
wire   [1:0] add_ln109_fu_618_p2;
reg   [1:0] ap_sig_allocacmp_dy_load;
reg   [1:0] dz_fu_108;
wire   [1:0] select_ln108_fu_356_p3;
reg   [1:0] ap_sig_allocacmp_dz_load;
reg   [3:0] indvar_flatten54_fu_112;
wire   [3:0] add_ln108_1_fu_324_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten54_load;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln109_fu_342_p2;
wire   [1:0] add_ln108_fu_336_p2;
wire   [19:0] tmp_507_fu_364_p7;
wire   [1:0] select_ln106_fu_348_p3;
wire   [19:0] tmp_508_fu_384_p7;
wire   [19:0] tmp_509_fu_404_p7;
wire   [19:0] tmp_507_fu_364_p9;
wire   [19:0] tmp_508_fu_384_p9;
wire   [19:0] tmp_509_fu_404_p9;
wire   [19:0] tmp_510_fu_424_p7;
wire   [19:0] tmp_511_fu_444_p7;
wire   [19:0] tmp_512_fu_464_p7;
wire   [19:0] tmp_513_fu_484_p7;
wire   [19:0] tmp_511_fu_444_p9;
wire   [19:0] tmp_512_fu_464_p9;
wire   [19:0] tmp_513_fu_484_p9;
wire   [19:0] tmp_514_fu_504_p7;
wire   [19:0] tmp_514_fu_504_p9;
wire   [19:0] tmp_515_fu_528_p7;
wire   [19:0] tmp_516_fu_548_p7;
wire   [19:0] tmp_517_fu_568_p7;
wire   [19:0] tmp_515_fu_528_p9;
wire   [19:0] tmp_516_fu_548_p9;
wire   [19:0] tmp_517_fu_568_p9;
wire   [19:0] tmp_518_fu_588_p7;
wire   [19:0] tmp_518_fu_588_p9;
wire  signed [20:0] sext_ln112_18_fu_524_p1;
wire  signed [20:0] sext_ln112_19_fu_608_p1;
wire  signed [21:0] sext_ln112_20_fu_645_p1;
wire  signed [21:0] sext_ln112_fu_642_p1;
wire   [21:0] add_ln112_27_fu_648_p2;
wire  signed [24:0] sext_ln112_21_fu_654_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [1:0] tmp_507_fu_364_p1;
wire   [1:0] tmp_507_fu_364_p3;
wire  signed [1:0] tmp_507_fu_364_p5;
wire   [1:0] tmp_508_fu_384_p1;
wire   [1:0] tmp_508_fu_384_p3;
wire  signed [1:0] tmp_508_fu_384_p5;
wire   [1:0] tmp_509_fu_404_p1;
wire   [1:0] tmp_509_fu_404_p3;
wire  signed [1:0] tmp_509_fu_404_p5;
wire   [1:0] tmp_510_fu_424_p1;
wire   [1:0] tmp_510_fu_424_p3;
wire  signed [1:0] tmp_510_fu_424_p5;
wire   [1:0] tmp_511_fu_444_p1;
wire   [1:0] tmp_511_fu_444_p3;
wire  signed [1:0] tmp_511_fu_444_p5;
wire   [1:0] tmp_512_fu_464_p1;
wire   [1:0] tmp_512_fu_464_p3;
wire  signed [1:0] tmp_512_fu_464_p5;
wire   [1:0] tmp_513_fu_484_p1;
wire   [1:0] tmp_513_fu_484_p3;
wire  signed [1:0] tmp_513_fu_484_p5;
wire   [1:0] tmp_514_fu_504_p1;
wire   [1:0] tmp_514_fu_504_p3;
wire  signed [1:0] tmp_514_fu_504_p5;
wire   [1:0] tmp_515_fu_528_p1;
wire   [1:0] tmp_515_fu_528_p3;
wire  signed [1:0] tmp_515_fu_528_p5;
wire   [1:0] tmp_516_fu_548_p1;
wire   [1:0] tmp_516_fu_548_p3;
wire  signed [1:0] tmp_516_fu_548_p5;
wire   [1:0] tmp_517_fu_568_p1;
wire   [1:0] tmp_517_fu_568_p3;
wire  signed [1:0] tmp_517_fu_568_p5;
wire   [1:0] tmp_518_fu_588_p1;
wire   [1:0] tmp_518_fu_588_p3;
wire  signed [1:0] tmp_518_fu_588_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 acc_fu_100 = 25'd0;
#0 dy_fu_104 = 2'd0;
#0 dz_fu_108 = 2'd0;
#0 indvar_flatten54_fu_112 = 4'd0;
#0 ap_done_reg = 1'b0;
end

predecoder_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U2071(
    .din0(conv3_i203_reload),
    .din1(conv3_i_1116206_reload),
    .din2(conv3_i_2131209_reload),
    .def(tmp_507_fu_364_p7),
    .sel(select_ln106_fu_348_p3),
    .dout(tmp_507_fu_364_p9)
);

predecoder_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U2072(
    .din0(conv3_i_1212_reload),
    .din1(conv3_i_1_1215_reload),
    .din2(conv3_i_1_2218_reload),
    .def(tmp_508_fu_384_p7),
    .sel(select_ln106_fu_348_p3),
    .dout(tmp_508_fu_384_p9)
);

predecoder_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U2073(
    .din0(conv3_i_2221_reload),
    .din1(conv3_i_2_1224_reload),
    .din2(conv3_i_2_2227_reload),
    .def(tmp_509_fu_404_p7),
    .sel(select_ln106_fu_348_p3),
    .dout(tmp_509_fu_404_p9)
);

predecoder_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U2074(
    .din0(tmp_507_fu_364_p9),
    .din1(tmp_508_fu_384_p9),
    .din2(tmp_509_fu_404_p9),
    .def(tmp_510_fu_424_p7),
    .sel(select_ln108_fu_356_p3),
    .dout(tmp_510_fu_424_p9)
);

predecoder_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U2075(
    .din0(conv3_i_1148204_reload),
    .din1(conv3_i_1116_1207_reload),
    .din2(conv3_i_2131_1210_reload),
    .def(tmp_511_fu_444_p7),
    .sel(select_ln106_fu_348_p3),
    .dout(tmp_511_fu_444_p9)
);

predecoder_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U2076(
    .din0(conv3_i_1_188213_reload),
    .din1(conv3_i_1_1_1216_reload),
    .din2(conv3_i_1_2_1219_reload),
    .def(tmp_512_fu_464_p7),
    .sel(select_ln106_fu_348_p3),
    .dout(tmp_512_fu_464_p9)
);

predecoder_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U2077(
    .din0(conv3_i_2_162222_reload),
    .din1(conv3_i_2_1_1225_reload),
    .din2(conv3_i_2_2_1228_reload),
    .def(tmp_513_fu_484_p7),
    .sel(select_ln106_fu_348_p3),
    .dout(tmp_513_fu_484_p9)
);

predecoder_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U2078(
    .din0(tmp_511_fu_444_p9),
    .din1(tmp_512_fu_464_p9),
    .din2(tmp_513_fu_484_p9),
    .def(tmp_514_fu_504_p7),
    .sel(select_ln108_fu_356_p3),
    .dout(tmp_514_fu_504_p9)
);

predecoder_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U2079(
    .din0(conv3_i_2161205_reload),
    .din1(conv3_i_1116_2208_reload),
    .din2(conv3_i_2131_2211_reload),
    .def(tmp_515_fu_528_p7),
    .sel(select_ln106_fu_348_p3),
    .dout(tmp_515_fu_528_p9)
);

predecoder_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U2080(
    .din0(conv3_i_1_2101214_reload),
    .din1(conv3_i_1_1_2217_reload),
    .din2(conv3_i_1_2_2220_reload),
    .def(tmp_516_fu_548_p7),
    .sel(select_ln106_fu_348_p3),
    .dout(tmp_516_fu_548_p9)
);

predecoder_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U2081(
    .din0(conv3_i_2_275223_reload),
    .din1(conv3_i_2_1_2226_reload),
    .din2(conv3_i_2_2_2229_reload),
    .def(tmp_517_fu_568_p7),
    .sel(select_ln106_fu_348_p3),
    .dout(tmp_517_fu_568_p9)
);

predecoder_kernel_sparsemux_7_2_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 20 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 20 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 20 ),
    .def_WIDTH( 20 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 20 ))
sparsemux_7_2_20_1_1_U2082(
    .din0(tmp_515_fu_528_p9),
    .din1(tmp_516_fu_548_p9),
    .din2(tmp_517_fu_568_p9),
    .def(tmp_518_fu_588_p7),
    .sel(select_ln108_fu_356_p3),
    .dout(tmp_518_fu_588_p9)
);

predecoder_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            acc_fu_100 <= acc_cast_cast_fu_291_p1;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            acc_fu_100 <= acc_3_fu_658_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln108_fu_318_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            dy_fu_104 <= add_ln109_fu_618_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            dy_fu_104 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln108_fu_318_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            dz_fu_108 <= select_ln108_fu_356_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            dz_fu_108 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln108_fu_318_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten54_fu_112 <= add_ln108_1_fu_324_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten54_fu_112 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln112_reg_710 <= add_ln112_fu_612_p2;
        tmp_510_reg_705 <= tmp_510_fu_424_p9;
    end
end

always @ (*) begin
    if (((icmp_ln108_fu_318_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_3_out_ap_vld = 1'b1;
    end else begin
        acc_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln108_fu_318_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_dy_load = 2'd0;
    end else begin
        ap_sig_allocacmp_dy_load = dy_fu_104;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_dz_load = 2'd0;
    end else begin
        ap_sig_allocacmp_dz_load = dz_fu_108;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten54_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten54_load = indvar_flatten54_fu_112;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_3_fu_658_p2 = ($signed(acc_fu_100) + $signed(sext_ln112_21_fu_654_p1));

assign acc_3_out = acc_fu_100;

assign acc_cast_cast_fu_291_p1 = $signed(acc_cast);

assign add_ln108_1_fu_324_p2 = (ap_sig_allocacmp_indvar_flatten54_load + 4'd1);

assign add_ln108_fu_336_p2 = (ap_sig_allocacmp_dz_load + 2'd1);

assign add_ln109_fu_618_p2 = (select_ln106_fu_348_p3 + 2'd1);

assign add_ln112_27_fu_648_p2 = ($signed(sext_ln112_20_fu_645_p1) + $signed(sext_ln112_fu_642_p1));

assign add_ln112_fu_612_p2 = ($signed(sext_ln112_18_fu_524_p1) + $signed(sext_ln112_19_fu_608_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln108_fu_318_p2 = ((ap_sig_allocacmp_indvar_flatten54_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_342_p2 = ((ap_sig_allocacmp_dy_load == 2'd3) ? 1'b1 : 1'b0);

assign select_ln106_fu_348_p3 = ((icmp_ln109_fu_342_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_dy_load);

assign select_ln108_fu_356_p3 = ((icmp_ln109_fu_342_p2[0:0] == 1'b1) ? add_ln108_fu_336_p2 : ap_sig_allocacmp_dz_load);

assign sext_ln112_18_fu_524_p1 = $signed(tmp_514_fu_504_p9);

assign sext_ln112_19_fu_608_p1 = $signed(tmp_518_fu_588_p9);

assign sext_ln112_20_fu_645_p1 = $signed(add_ln112_reg_710);

assign sext_ln112_21_fu_654_p1 = $signed(add_ln112_27_fu_648_p2);

assign sext_ln112_fu_642_p1 = $signed(tmp_510_reg_705);

assign tmp_507_fu_364_p7 = 'bx;

assign tmp_508_fu_384_p7 = 'bx;

assign tmp_509_fu_404_p7 = 'bx;

assign tmp_510_fu_424_p7 = 'bx;

assign tmp_511_fu_444_p7 = 'bx;

assign tmp_512_fu_464_p7 = 'bx;

assign tmp_513_fu_484_p7 = 'bx;

assign tmp_514_fu_504_p7 = 'bx;

assign tmp_515_fu_528_p7 = 'bx;

assign tmp_516_fu_548_p7 = 'bx;

assign tmp_517_fu_568_p7 = 'bx;

assign tmp_518_fu_588_p7 = 'bx;

endmodule //predecoder_kernel_conv3d_hidden_layer_12_Pipeline_SUM_PARTIAL_VITIS_LOOP_109_9
