// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module predecoder_kernel_conv3d_hidden_layer_1_Pipeline_RESET_VITIS_LOOP_40_1_VITIS_LOOP_41_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fb_0_address0,
        fb_0_ce0,
        fb_0_we0,
        fb_0_d0,
        fb_0_1_address0,
        fb_0_1_ce0,
        fb_0_1_we0,
        fb_0_1_d0,
        fb_0_2_address0,
        fb_0_2_ce0,
        fb_0_2_we0,
        fb_0_2_d0,
        fb_0_3_address0,
        fb_0_3_ce0,
        fb_0_3_we0,
        fb_0_3_d0,
        fb_0_4_address0,
        fb_0_4_ce0,
        fb_0_4_we0,
        fb_0_4_d0,
        fb_0_5_address0,
        fb_0_5_ce0,
        fb_0_5_we0,
        fb_0_5_d0,
        fb_0_6_address0,
        fb_0_6_ce0,
        fb_0_6_we0,
        fb_0_6_d0,
        fb_0_7_address0,
        fb_0_7_ce0,
        fb_0_7_we0,
        fb_0_7_d0,
        fb_0_8_address0,
        fb_0_8_ce0,
        fb_0_8_we0,
        fb_0_8_d0,
        fb_0_9_address0,
        fb_0_9_ce0,
        fb_0_9_we0,
        fb_0_9_d0,
        fb_0_10_address0,
        fb_0_10_ce0,
        fb_0_10_we0,
        fb_0_10_d0,
        fb_0_11_address0,
        fb_0_11_ce0,
        fb_0_11_we0,
        fb_0_11_d0,
        fb_0_12_address0,
        fb_0_12_ce0,
        fb_0_12_we0,
        fb_0_12_d0,
        fb_0_13_address0,
        fb_0_13_ce0,
        fb_0_13_we0,
        fb_0_13_d0,
        fb_0_14_address0,
        fb_0_14_ce0,
        fb_0_14_we0,
        fb_0_14_d0,
        fb_0_15_address0,
        fb_0_15_ce0,
        fb_0_15_we0,
        fb_0_15_d0,
        fb_0_16_address0,
        fb_0_16_ce0,
        fb_0_16_we0,
        fb_0_16_d0,
        fb_0_17_address0,
        fb_0_17_ce0,
        fb_0_17_we0,
        fb_0_17_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] fb_0_address0;
output   fb_0_ce0;
output   fb_0_we0;
output  [7:0] fb_0_d0;
output  [2:0] fb_0_1_address0;
output   fb_0_1_ce0;
output   fb_0_1_we0;
output  [7:0] fb_0_1_d0;
output  [2:0] fb_0_2_address0;
output   fb_0_2_ce0;
output   fb_0_2_we0;
output  [7:0] fb_0_2_d0;
output  [2:0] fb_0_3_address0;
output   fb_0_3_ce0;
output   fb_0_3_we0;
output  [7:0] fb_0_3_d0;
output  [2:0] fb_0_4_address0;
output   fb_0_4_ce0;
output   fb_0_4_we0;
output  [7:0] fb_0_4_d0;
output  [2:0] fb_0_5_address0;
output   fb_0_5_ce0;
output   fb_0_5_we0;
output  [7:0] fb_0_5_d0;
output  [2:0] fb_0_6_address0;
output   fb_0_6_ce0;
output   fb_0_6_we0;
output  [7:0] fb_0_6_d0;
output  [2:0] fb_0_7_address0;
output   fb_0_7_ce0;
output   fb_0_7_we0;
output  [7:0] fb_0_7_d0;
output  [2:0] fb_0_8_address0;
output   fb_0_8_ce0;
output   fb_0_8_we0;
output  [7:0] fb_0_8_d0;
output  [2:0] fb_0_9_address0;
output   fb_0_9_ce0;
output   fb_0_9_we0;
output  [7:0] fb_0_9_d0;
output  [2:0] fb_0_10_address0;
output   fb_0_10_ce0;
output   fb_0_10_we0;
output  [7:0] fb_0_10_d0;
output  [2:0] fb_0_11_address0;
output   fb_0_11_ce0;
output   fb_0_11_we0;
output  [7:0] fb_0_11_d0;
output  [2:0] fb_0_12_address0;
output   fb_0_12_ce0;
output   fb_0_12_we0;
output  [7:0] fb_0_12_d0;
output  [2:0] fb_0_13_address0;
output   fb_0_13_ce0;
output   fb_0_13_we0;
output  [7:0] fb_0_13_d0;
output  [2:0] fb_0_14_address0;
output   fb_0_14_ce0;
output   fb_0_14_we0;
output  [7:0] fb_0_14_d0;
output  [2:0] fb_0_15_address0;
output   fb_0_15_ce0;
output   fb_0_15_we0;
output  [7:0] fb_0_15_d0;
output  [2:0] fb_0_16_address0;
output   fb_0_16_ce0;
output   fb_0_16_we0;
output  [7:0] fb_0_16_d0;
output  [2:0] fb_0_17_address0;
output   fb_0_17_ce0;
output   fb_0_17_we0;
output  [7:0] fb_0_17_d0;

reg ap_idle;
reg fb_0_ce0;
reg fb_0_we0;
reg fb_0_1_ce0;
reg fb_0_1_we0;
reg fb_0_2_ce0;
reg fb_0_2_we0;
reg fb_0_3_ce0;
reg fb_0_3_we0;
reg fb_0_4_ce0;
reg fb_0_4_we0;
reg fb_0_5_ce0;
reg fb_0_5_we0;
reg fb_0_6_ce0;
reg fb_0_6_we0;
reg fb_0_7_ce0;
reg fb_0_7_we0;
reg fb_0_8_ce0;
reg fb_0_8_we0;
reg fb_0_9_ce0;
reg fb_0_9_we0;
reg fb_0_10_ce0;
reg fb_0_10_we0;
reg fb_0_11_ce0;
reg fb_0_11_we0;
reg fb_0_12_ce0;
reg fb_0_12_we0;
reg fb_0_13_ce0;
reg fb_0_13_we0;
reg fb_0_14_ce0;
reg fb_0_14_we0;
reg fb_0_15_ce0;
reg fb_0_15_we0;
reg fb_0_16_ce0;
reg fb_0_16_we0;
reg fb_0_17_ce0;
reg fb_0_17_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln39_fu_391_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [1:0] select_ln39_1_fu_450_p3;
reg   [1:0] select_ln39_1_reg_590;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] select_ln40_fu_470_p3;
reg   [2:0] select_ln40_reg_594;
wire   [2:0] select_ln40_1_fu_478_p3;
reg   [2:0] select_ln40_1_reg_598;
wire   [63:0] zext_ln40_fu_531_p1;
wire    ap_block_pp0_stage0;
reg   [2:0] x_fu_88;
wire   [2:0] add_ln41_fu_486_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_x_load;
reg   [2:0] y_fu_92;
reg   [2:0] ap_sig_allocacmp_y_load;
reg   [5:0] indvar_flatten_fu_96;
wire   [5:0] select_ln40_2_fu_498_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [1:0] s_fu_100;
reg   [1:0] ap_sig_allocacmp_s_load;
reg   [6:0] indvar_flatten11_fu_104;
wire   [6:0] add_ln39_1_fu_397_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten11_load;
wire   [0:0] icmp_ln40_fu_418_p2;
wire   [0:0] icmp_ln41_fu_438_p2;
wire   [0:0] xor_ln39_fu_432_p2;
wire   [1:0] add_ln39_fu_412_p2;
wire   [2:0] select_ln39_fu_424_p3;
wire   [0:0] and_ln39_fu_444_p2;
wire   [0:0] or_ln40_fu_464_p2;
wire   [2:0] add_ln40_fu_458_p2;
wire   [5:0] add_ln40_1_fu_492_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 x_fu_88 = 3'd0;
#0 y_fu_92 = 3'd0;
#0 indvar_flatten_fu_96 = 6'd0;
#0 s_fu_100 = 2'd0;
#0 indvar_flatten11_fu_104 = 7'd0;
#0 ap_done_reg = 1'b0;
end

predecoder_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln39_fu_391_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten11_fu_104 <= add_ln39_1_fu_397_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten11_fu_104 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln39_fu_391_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_96 <= select_ln40_2_fu_498_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_96 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln39_fu_391_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            s_fu_100 <= select_ln39_1_fu_450_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            s_fu_100 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln39_fu_391_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_88 <= add_ln41_fu_486_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_88 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln39_fu_391_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_92 <= select_ln40_1_fu_478_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_92 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln39_1_reg_590 <= select_ln39_1_fu_450_p3;
        select_ln40_1_reg_598 <= select_ln40_1_fu_478_p3;
        select_ln40_reg_594 <= select_ln40_fu_470_p3;
    end
end

always @ (*) begin
    if (((icmp_ln39_fu_391_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten11_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten11_load = indvar_flatten11_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_s_load = 2'd0;
    end else begin
        ap_sig_allocacmp_s_load = s_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_load = 3'd0;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_y_load = 3'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_10_ce0 = 1'b1;
    end else begin
        fb_0_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln40_reg_594 == 3'd4) & (select_ln39_1_reg_590 == 2'd1))) begin
        fb_0_10_we0 = 1'b1;
    end else begin
        fb_0_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_11_ce0 = 1'b1;
    end else begin
        fb_0_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln40_reg_594 == 3'd0) & ~(select_ln40_reg_594 == 3'd1) & ~(select_ln40_reg_594 == 3'd2) & ~(select_ln40_reg_594 == 3'd3) & ~(select_ln40_reg_594 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln39_1_reg_590 == 2'd1))) begin
        fb_0_11_we0 = 1'b1;
    end else begin
        fb_0_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_12_ce0 = 1'b1;
    end else begin
        fb_0_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln39_1_reg_590 == 2'd0) & ~(select_ln39_1_reg_590 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln40_reg_594 == 3'd0))) begin
        fb_0_12_we0 = 1'b1;
    end else begin
        fb_0_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_13_ce0 = 1'b1;
    end else begin
        fb_0_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln39_1_reg_590 == 2'd0) & ~(select_ln39_1_reg_590 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln40_reg_594 == 3'd1))) begin
        fb_0_13_we0 = 1'b1;
    end else begin
        fb_0_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_14_ce0 = 1'b1;
    end else begin
        fb_0_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln39_1_reg_590 == 2'd0) & ~(select_ln39_1_reg_590 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln40_reg_594 == 3'd2))) begin
        fb_0_14_we0 = 1'b1;
    end else begin
        fb_0_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_15_ce0 = 1'b1;
    end else begin
        fb_0_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln39_1_reg_590 == 2'd0) & ~(select_ln39_1_reg_590 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln40_reg_594 == 3'd3))) begin
        fb_0_15_we0 = 1'b1;
    end else begin
        fb_0_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_16_ce0 = 1'b1;
    end else begin
        fb_0_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln39_1_reg_590 == 2'd0) & ~(select_ln39_1_reg_590 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln40_reg_594 == 3'd4))) begin
        fb_0_16_we0 = 1'b1;
    end else begin
        fb_0_16_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_17_ce0 = 1'b1;
    end else begin
        fb_0_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln39_1_reg_590 == 2'd0) & ~(select_ln40_reg_594 == 3'd0) & ~(select_ln40_reg_594 == 3'd1) & ~(select_ln40_reg_594 == 3'd2) & ~(select_ln40_reg_594 == 3'd3) & ~(select_ln40_reg_594 == 3'd4) & ~(select_ln39_1_reg_590 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_17_we0 = 1'b1;
    end else begin
        fb_0_17_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_1_ce0 = 1'b1;
    end else begin
        fb_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln40_reg_594 == 3'd1) & (select_ln39_1_reg_590 == 2'd0))) begin
        fb_0_1_we0 = 1'b1;
    end else begin
        fb_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_2_ce0 = 1'b1;
    end else begin
        fb_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln40_reg_594 == 3'd2) & (select_ln39_1_reg_590 == 2'd0))) begin
        fb_0_2_we0 = 1'b1;
    end else begin
        fb_0_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_3_ce0 = 1'b1;
    end else begin
        fb_0_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln40_reg_594 == 3'd3) & (select_ln39_1_reg_590 == 2'd0))) begin
        fb_0_3_we0 = 1'b1;
    end else begin
        fb_0_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_4_ce0 = 1'b1;
    end else begin
        fb_0_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln40_reg_594 == 3'd4) & (select_ln39_1_reg_590 == 2'd0))) begin
        fb_0_4_we0 = 1'b1;
    end else begin
        fb_0_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_5_ce0 = 1'b1;
    end else begin
        fb_0_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln40_reg_594 == 3'd0) & ~(select_ln40_reg_594 == 3'd1) & ~(select_ln40_reg_594 == 3'd2) & ~(select_ln40_reg_594 == 3'd3) & ~(select_ln40_reg_594 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln39_1_reg_590 == 2'd0))) begin
        fb_0_5_we0 = 1'b1;
    end else begin
        fb_0_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_6_ce0 = 1'b1;
    end else begin
        fb_0_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln40_reg_594 == 3'd0) & (select_ln39_1_reg_590 == 2'd1))) begin
        fb_0_6_we0 = 1'b1;
    end else begin
        fb_0_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_7_ce0 = 1'b1;
    end else begin
        fb_0_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln40_reg_594 == 3'd1) & (select_ln39_1_reg_590 == 2'd1))) begin
        fb_0_7_we0 = 1'b1;
    end else begin
        fb_0_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_8_ce0 = 1'b1;
    end else begin
        fb_0_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln40_reg_594 == 3'd2) & (select_ln39_1_reg_590 == 2'd1))) begin
        fb_0_8_we0 = 1'b1;
    end else begin
        fb_0_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_9_ce0 = 1'b1;
    end else begin
        fb_0_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln40_reg_594 == 3'd3) & (select_ln39_1_reg_590 == 2'd1))) begin
        fb_0_9_we0 = 1'b1;
    end else begin
        fb_0_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        fb_0_ce0 = 1'b1;
    end else begin
        fb_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (select_ln40_reg_594 == 3'd0) & (select_ln39_1_reg_590 == 2'd0))) begin
        fb_0_we0 = 1'b1;
    end else begin
        fb_0_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln39_1_fu_397_p2 = (ap_sig_allocacmp_indvar_flatten11_load + 7'd1);

assign add_ln39_fu_412_p2 = (ap_sig_allocacmp_s_load + 2'd1);

assign add_ln40_1_fu_492_p2 = (ap_sig_allocacmp_indvar_flatten_load + 6'd1);

assign add_ln40_fu_458_p2 = (select_ln39_fu_424_p3 + 3'd1);

assign add_ln41_fu_486_p2 = (select_ln40_fu_470_p3 + 3'd1);

assign and_ln39_fu_444_p2 = (xor_ln39_fu_432_p2 & icmp_ln41_fu_438_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign fb_0_10_address0 = zext_ln40_fu_531_p1;

assign fb_0_10_d0 = 8'd0;

assign fb_0_11_address0 = zext_ln40_fu_531_p1;

assign fb_0_11_d0 = 8'd0;

assign fb_0_12_address0 = zext_ln40_fu_531_p1;

assign fb_0_12_d0 = 8'd0;

assign fb_0_13_address0 = zext_ln40_fu_531_p1;

assign fb_0_13_d0 = 8'd0;

assign fb_0_14_address0 = zext_ln40_fu_531_p1;

assign fb_0_14_d0 = 8'd0;

assign fb_0_15_address0 = zext_ln40_fu_531_p1;

assign fb_0_15_d0 = 8'd0;

assign fb_0_16_address0 = zext_ln40_fu_531_p1;

assign fb_0_16_d0 = 8'd0;

assign fb_0_17_address0 = zext_ln40_fu_531_p1;

assign fb_0_17_d0 = 8'd0;

assign fb_0_1_address0 = zext_ln40_fu_531_p1;

assign fb_0_1_d0 = 8'd0;

assign fb_0_2_address0 = zext_ln40_fu_531_p1;

assign fb_0_2_d0 = 8'd0;

assign fb_0_3_address0 = zext_ln40_fu_531_p1;

assign fb_0_3_d0 = 8'd0;

assign fb_0_4_address0 = zext_ln40_fu_531_p1;

assign fb_0_4_d0 = 8'd0;

assign fb_0_5_address0 = zext_ln40_fu_531_p1;

assign fb_0_5_d0 = 8'd0;

assign fb_0_6_address0 = zext_ln40_fu_531_p1;

assign fb_0_6_d0 = 8'd0;

assign fb_0_7_address0 = zext_ln40_fu_531_p1;

assign fb_0_7_d0 = 8'd0;

assign fb_0_8_address0 = zext_ln40_fu_531_p1;

assign fb_0_8_d0 = 8'd0;

assign fb_0_9_address0 = zext_ln40_fu_531_p1;

assign fb_0_9_d0 = 8'd0;

assign fb_0_address0 = zext_ln40_fu_531_p1;

assign fb_0_d0 = 8'd0;

assign icmp_ln39_fu_391_p2 = ((ap_sig_allocacmp_indvar_flatten11_load == 7'd108) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_418_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 6'd36) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_438_p2 = ((ap_sig_allocacmp_x_load == 3'd6) ? 1'b1 : 1'b0);

assign or_ln40_fu_464_p2 = (icmp_ln40_fu_418_p2 | and_ln39_fu_444_p2);

assign select_ln39_1_fu_450_p3 = ((icmp_ln40_fu_418_p2[0:0] == 1'b1) ? add_ln39_fu_412_p2 : ap_sig_allocacmp_s_load);

assign select_ln39_fu_424_p3 = ((icmp_ln40_fu_418_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_y_load);

assign select_ln40_1_fu_478_p3 = ((and_ln39_fu_444_p2[0:0] == 1'b1) ? add_ln40_fu_458_p2 : select_ln39_fu_424_p3);

assign select_ln40_2_fu_498_p3 = ((icmp_ln40_fu_418_p2[0:0] == 1'b1) ? 6'd1 : add_ln40_1_fu_492_p2);

assign select_ln40_fu_470_p3 = ((or_ln40_fu_464_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_x_load);

assign xor_ln39_fu_432_p2 = (icmp_ln40_fu_418_p2 ^ 1'd1);

assign zext_ln40_fu_531_p1 = select_ln40_1_reg_598;

endmodule //predecoder_kernel_conv3d_hidden_layer_1_Pipeline_RESET_VITIS_LOOP_40_1_VITIS_LOOP_41_2
