// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module predecoder_kernel_edge_correction_Pipeline_VITIS_LOOP_213_5_VITIS_LOOP_214_6_VITIS_LOOP_215_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        correction_address0,
        correction_ce0,
        correction_q0,
        correction_1_address0,
        correction_1_ce0,
        correction_1_q0,
        correction_2_address0,
        correction_2_ce0,
        correction_2_q0,
        correction_3_address0,
        correction_3_ce0,
        correction_3_q0,
        correction_4_address0,
        correction_4_ce0,
        correction_4_q0,
        correction_5_address0,
        correction_5_ce0,
        correction_5_q0,
        correction_6_address0,
        correction_6_ce0,
        correction_6_q0,
        correction_7_address0,
        correction_7_ce0,
        correction_7_q0,
        correction_8_address0,
        correction_8_ce0,
        correction_8_q0,
        correction_9_address0,
        correction_9_ce0,
        correction_9_q0,
        correction_10_address0,
        correction_10_ce0,
        correction_10_q0,
        correction_11_address0,
        correction_11_ce0,
        correction_11_q0,
        correction_12_address0,
        correction_12_ce0,
        correction_12_q0,
        correction_13_address0,
        correction_13_ce0,
        correction_13_q0,
        correction_14_address0,
        correction_14_ce0,
        correction_14_q0,
        correction_15_address0,
        correction_15_ce0,
        correction_15_q0,
        correction_16_address0,
        correction_16_ce0,
        correction_16_q0,
        correction_17_address0,
        correction_17_ce0,
        correction_17_q0,
        correction_18_address0,
        correction_18_ce0,
        correction_18_q0,
        correction_19_address0,
        correction_19_ce0,
        correction_19_q0,
        correction_20_address0,
        correction_20_ce0,
        correction_20_q0,
        correction_21_address0,
        correction_21_ce0,
        correction_21_q0,
        correction_22_address0,
        correction_22_ce0,
        correction_22_q0,
        correction_23_address0,
        correction_23_ce0,
        correction_23_q0,
        correction_24_address0,
        correction_24_ce0,
        correction_24_q0,
        correction_25_address0,
        correction_25_ce0,
        correction_25_q0,
        correction_26_address0,
        correction_26_ce0,
        correction_26_q0,
        correction_27_address0,
        correction_27_ce0,
        correction_27_q0,
        correction_28_address0,
        correction_28_ce0,
        correction_28_q0,
        correction_29_address0,
        correction_29_ce0,
        correction_29_q0,
        correction_30_address0,
        correction_30_ce0,
        correction_30_q0,
        correction_31_address0,
        correction_31_ce0,
        correction_31_q0,
        correction_32_address0,
        correction_32_ce0,
        correction_32_q0,
        correction_33_address0,
        correction_33_ce0,
        correction_33_q0,
        correction_34_address0,
        correction_34_ce0,
        correction_34_q0,
        correction_35_address0,
        correction_35_ce0,
        correction_35_q0,
        correction_36_address0,
        correction_36_ce0,
        correction_36_q0,
        correction_37_address0,
        correction_37_ce0,
        correction_37_q0,
        correction_38_address0,
        correction_38_ce0,
        correction_38_q0,
        correction_39_address0,
        correction_39_ce0,
        correction_39_q0,
        correction_40_address0,
        correction_40_ce0,
        correction_40_q0,
        correction_41_address0,
        correction_41_ce0,
        correction_41_q0,
        correction_42_address0,
        correction_42_ce0,
        correction_42_q0,
        correction_43_address0,
        correction_43_ce0,
        correction_43_q0,
        correction_44_address0,
        correction_44_ce0,
        correction_44_q0,
        correction_45_address0,
        correction_45_ce0,
        correction_45_q0,
        correction_46_address0,
        correction_46_ce0,
        correction_46_q0,
        correction_47_address0,
        correction_47_ce0,
        correction_47_q0,
        correction_48_address0,
        correction_48_ce0,
        correction_48_q0,
        correction_49_address0,
        correction_49_ce0,
        correction_49_q0,
        correction_50_address0,
        correction_50_ce0,
        correction_50_q0,
        correction_51_address0,
        correction_51_ce0,
        correction_51_q0,
        correction_52_address0,
        correction_52_ce0,
        correction_52_q0,
        correction_53_address0,
        correction_53_ce0,
        correction_53_q0,
        correction_54_address0,
        correction_54_ce0,
        correction_54_q0,
        correction_55_address0,
        correction_55_ce0,
        correction_55_q0,
        correction_56_address0,
        correction_56_ce0,
        correction_56_q0,
        correction_57_address0,
        correction_57_ce0,
        correction_57_q0,
        correction_58_address0,
        correction_58_ce0,
        correction_58_q0,
        correction_59_address0,
        correction_59_ce0,
        correction_59_q0,
        correction_60_address0,
        correction_60_ce0,
        correction_60_q0,
        correction_61_address0,
        correction_61_ce0,
        correction_61_q0,
        correction_62_address0,
        correction_62_ce0,
        correction_62_q0,
        correction_63_address0,
        correction_63_ce0,
        correction_63_q0,
        correction_64_address0,
        correction_64_ce0,
        correction_64_q0,
        correction_65_address0,
        correction_65_ce0,
        correction_65_q0,
        correction_66_address0,
        correction_66_ce0,
        correction_66_q0,
        correction_67_address0,
        correction_67_ce0,
        correction_67_q0,
        correction_68_address0,
        correction_68_ce0,
        correction_68_q0,
        correction_69_address0,
        correction_69_ce0,
        correction_69_q0,
        correction_70_address0,
        correction_70_ce0,
        correction_70_q0,
        correction_71_address0,
        correction_71_ce0,
        correction_71_q0,
        beat_2_out,
        beat_2_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [1:0] correction_address0;
output   correction_ce0;
input  [0:0] correction_q0;
output  [1:0] correction_1_address0;
output   correction_1_ce0;
input  [0:0] correction_1_q0;
output  [1:0] correction_2_address0;
output   correction_2_ce0;
input  [0:0] correction_2_q0;
output  [1:0] correction_3_address0;
output   correction_3_ce0;
input  [0:0] correction_3_q0;
output  [1:0] correction_4_address0;
output   correction_4_ce0;
input  [0:0] correction_4_q0;
output  [1:0] correction_5_address0;
output   correction_5_ce0;
input  [0:0] correction_5_q0;
output  [1:0] correction_6_address0;
output   correction_6_ce0;
input  [0:0] correction_6_q0;
output  [1:0] correction_7_address0;
output   correction_7_ce0;
input  [0:0] correction_7_q0;
output  [1:0] correction_8_address0;
output   correction_8_ce0;
input  [0:0] correction_8_q0;
output  [1:0] correction_9_address0;
output   correction_9_ce0;
input  [0:0] correction_9_q0;
output  [1:0] correction_10_address0;
output   correction_10_ce0;
input  [0:0] correction_10_q0;
output  [1:0] correction_11_address0;
output   correction_11_ce0;
input  [0:0] correction_11_q0;
output  [1:0] correction_12_address0;
output   correction_12_ce0;
input  [0:0] correction_12_q0;
output  [1:0] correction_13_address0;
output   correction_13_ce0;
input  [0:0] correction_13_q0;
output  [1:0] correction_14_address0;
output   correction_14_ce0;
input  [0:0] correction_14_q0;
output  [1:0] correction_15_address0;
output   correction_15_ce0;
input  [0:0] correction_15_q0;
output  [1:0] correction_16_address0;
output   correction_16_ce0;
input  [0:0] correction_16_q0;
output  [1:0] correction_17_address0;
output   correction_17_ce0;
input  [0:0] correction_17_q0;
output  [1:0] correction_18_address0;
output   correction_18_ce0;
input  [0:0] correction_18_q0;
output  [1:0] correction_19_address0;
output   correction_19_ce0;
input  [0:0] correction_19_q0;
output  [1:0] correction_20_address0;
output   correction_20_ce0;
input  [0:0] correction_20_q0;
output  [1:0] correction_21_address0;
output   correction_21_ce0;
input  [0:0] correction_21_q0;
output  [1:0] correction_22_address0;
output   correction_22_ce0;
input  [0:0] correction_22_q0;
output  [1:0] correction_23_address0;
output   correction_23_ce0;
input  [0:0] correction_23_q0;
output  [1:0] correction_24_address0;
output   correction_24_ce0;
input  [0:0] correction_24_q0;
output  [1:0] correction_25_address0;
output   correction_25_ce0;
input  [0:0] correction_25_q0;
output  [1:0] correction_26_address0;
output   correction_26_ce0;
input  [0:0] correction_26_q0;
output  [1:0] correction_27_address0;
output   correction_27_ce0;
input  [0:0] correction_27_q0;
output  [1:0] correction_28_address0;
output   correction_28_ce0;
input  [0:0] correction_28_q0;
output  [1:0] correction_29_address0;
output   correction_29_ce0;
input  [0:0] correction_29_q0;
output  [1:0] correction_30_address0;
output   correction_30_ce0;
input  [0:0] correction_30_q0;
output  [1:0] correction_31_address0;
output   correction_31_ce0;
input  [0:0] correction_31_q0;
output  [1:0] correction_32_address0;
output   correction_32_ce0;
input  [0:0] correction_32_q0;
output  [1:0] correction_33_address0;
output   correction_33_ce0;
input  [0:0] correction_33_q0;
output  [1:0] correction_34_address0;
output   correction_34_ce0;
input  [0:0] correction_34_q0;
output  [1:0] correction_35_address0;
output   correction_35_ce0;
input  [0:0] correction_35_q0;
output  [1:0] correction_36_address0;
output   correction_36_ce0;
input  [0:0] correction_36_q0;
output  [1:0] correction_37_address0;
output   correction_37_ce0;
input  [0:0] correction_37_q0;
output  [1:0] correction_38_address0;
output   correction_38_ce0;
input  [0:0] correction_38_q0;
output  [1:0] correction_39_address0;
output   correction_39_ce0;
input  [0:0] correction_39_q0;
output  [1:0] correction_40_address0;
output   correction_40_ce0;
input  [0:0] correction_40_q0;
output  [1:0] correction_41_address0;
output   correction_41_ce0;
input  [0:0] correction_41_q0;
output  [1:0] correction_42_address0;
output   correction_42_ce0;
input  [0:0] correction_42_q0;
output  [1:0] correction_43_address0;
output   correction_43_ce0;
input  [0:0] correction_43_q0;
output  [1:0] correction_44_address0;
output   correction_44_ce0;
input  [0:0] correction_44_q0;
output  [1:0] correction_45_address0;
output   correction_45_ce0;
input  [0:0] correction_45_q0;
output  [1:0] correction_46_address0;
output   correction_46_ce0;
input  [0:0] correction_46_q0;
output  [1:0] correction_47_address0;
output   correction_47_ce0;
input  [0:0] correction_47_q0;
output  [1:0] correction_48_address0;
output   correction_48_ce0;
input  [0:0] correction_48_q0;
output  [1:0] correction_49_address0;
output   correction_49_ce0;
input  [0:0] correction_49_q0;
output  [1:0] correction_50_address0;
output   correction_50_ce0;
input  [0:0] correction_50_q0;
output  [1:0] correction_51_address0;
output   correction_51_ce0;
input  [0:0] correction_51_q0;
output  [1:0] correction_52_address0;
output   correction_52_ce0;
input  [0:0] correction_52_q0;
output  [1:0] correction_53_address0;
output   correction_53_ce0;
input  [0:0] correction_53_q0;
output  [1:0] correction_54_address0;
output   correction_54_ce0;
input  [0:0] correction_54_q0;
output  [1:0] correction_55_address0;
output   correction_55_ce0;
input  [0:0] correction_55_q0;
output  [1:0] correction_56_address0;
output   correction_56_ce0;
input  [0:0] correction_56_q0;
output  [1:0] correction_57_address0;
output   correction_57_ce0;
input  [0:0] correction_57_q0;
output  [1:0] correction_58_address0;
output   correction_58_ce0;
input  [0:0] correction_58_q0;
output  [1:0] correction_59_address0;
output   correction_59_ce0;
input  [0:0] correction_59_q0;
output  [1:0] correction_60_address0;
output   correction_60_ce0;
input  [0:0] correction_60_q0;
output  [1:0] correction_61_address0;
output   correction_61_ce0;
input  [0:0] correction_61_q0;
output  [1:0] correction_62_address0;
output   correction_62_ce0;
input  [0:0] correction_62_q0;
output  [1:0] correction_63_address0;
output   correction_63_ce0;
input  [0:0] correction_63_q0;
output  [1:0] correction_64_address0;
output   correction_64_ce0;
input  [0:0] correction_64_q0;
output  [1:0] correction_65_address0;
output   correction_65_ce0;
input  [0:0] correction_65_q0;
output  [1:0] correction_66_address0;
output   correction_66_ce0;
input  [0:0] correction_66_q0;
output  [1:0] correction_67_address0;
output   correction_67_ce0;
input  [0:0] correction_67_q0;
output  [1:0] correction_68_address0;
output   correction_68_ce0;
input  [0:0] correction_68_q0;
output  [1:0] correction_69_address0;
output   correction_69_ce0;
input  [0:0] correction_69_q0;
output  [1:0] correction_70_address0;
output   correction_70_ce0;
input  [0:0] correction_70_q0;
output  [1:0] correction_71_address0;
output   correction_71_ce0;
input  [0:0] correction_71_q0;
output  [511:0] beat_2_out;
output   beat_2_out_ap_vld;

reg ap_idle;
reg correction_ce0;
reg correction_1_ce0;
reg correction_2_ce0;
reg correction_3_ce0;
reg correction_4_ce0;
reg correction_5_ce0;
reg correction_6_ce0;
reg correction_7_ce0;
reg correction_8_ce0;
reg correction_9_ce0;
reg correction_10_ce0;
reg correction_11_ce0;
reg correction_12_ce0;
reg correction_13_ce0;
reg correction_14_ce0;
reg correction_15_ce0;
reg correction_16_ce0;
reg correction_17_ce0;
reg correction_18_ce0;
reg correction_19_ce0;
reg correction_20_ce0;
reg correction_21_ce0;
reg correction_22_ce0;
reg correction_23_ce0;
reg correction_24_ce0;
reg correction_25_ce0;
reg correction_26_ce0;
reg correction_27_ce0;
reg correction_28_ce0;
reg correction_29_ce0;
reg correction_30_ce0;
reg correction_31_ce0;
reg correction_32_ce0;
reg correction_33_ce0;
reg correction_34_ce0;
reg correction_35_ce0;
reg correction_36_ce0;
reg correction_37_ce0;
reg correction_38_ce0;
reg correction_39_ce0;
reg correction_40_ce0;
reg correction_41_ce0;
reg correction_42_ce0;
reg correction_43_ce0;
reg correction_44_ce0;
reg correction_45_ce0;
reg correction_46_ce0;
reg correction_47_ce0;
reg correction_48_ce0;
reg correction_49_ce0;
reg correction_50_ce0;
reg correction_51_ce0;
reg correction_52_ce0;
reg correction_53_ce0;
reg correction_54_ce0;
reg correction_55_ce0;
reg correction_56_ce0;
reg correction_57_ce0;
reg correction_58_ce0;
reg correction_59_ce0;
reg correction_60_ce0;
reg correction_61_ce0;
reg correction_62_ce0;
reg correction_63_ce0;
reg correction_64_ce0;
reg correction_65_ce0;
reg correction_66_ce0;
reg correction_67_ce0;
reg correction_68_ce0;
reg correction_69_ce0;
reg correction_70_ce0;
reg correction_71_ce0;
reg beat_2_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln213_fu_1218_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] select_ln213_fu_1280_p3;
reg   [2:0] select_ln213_reg_2036;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] select_ln212_1_fu_1300_p3;
reg   [2:0] select_ln212_1_reg_2042;
wire   [2:0] select_ln214_fu_1308_p3;
reg   [2:0] select_ln214_reg_2059;
wire   [0:0] trunc_ln213_fu_1316_p1;
reg   [0:0] trunc_ln213_reg_2066;
wire   [63:0] zext_ln212_fu_1330_p1;
wire    ap_block_pp0_stage0;
reg   [511:0] beat_fu_218;
reg   [511:0] beat_1_fu_1971_p4;
wire    ap_loop_init;
reg   [2:0] x_fu_222;
wire   [2:0] add_ln215_fu_1406_p2;
reg   [2:0] ap_sig_allocacmp_x_load;
reg   [2:0] y_fu_226;
reg   [2:0] ap_sig_allocacmp_y_load;
reg   [5:0] indvar_flatten43_fu_230;
wire   [5:0] select_ln214_1_fu_1418_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten43_load;
reg   [2:0] t_fu_234;
reg   [2:0] ap_sig_allocacmp_t_load;
reg   [7:0] indvar_flatten58_fu_238;
wire   [7:0] add_ln213_1_fu_1224_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten58_load;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln214_fu_1248_p2;
wire   [0:0] icmp_ln215_fu_1268_p2;
wire   [0:0] xor_ln212_fu_1262_p2;
wire   [2:0] add_ln213_fu_1242_p2;
wire   [2:0] select_ln212_fu_1254_p3;
wire   [0:0] and_ln212_fu_1274_p2;
wire   [0:0] or_ln212_fu_1294_p2;
wire   [2:0] add_ln214_fu_1288_p2;
wire   [1:0] lshr_ln2_fu_1320_p4;
wire   [5:0] add_ln214_1_fu_1412_p2;
wire   [5:0] p_shl4_fu_1454_p3;
wire   [3:0] p_shl5_fu_1465_p3;
wire   [6:0] p_shl4_cast_fu_1461_p1;
wire   [6:0] p_shl5_cast_fu_1472_p1;
wire   [6:0] empty_fu_1476_p2;
wire   [6:0] zext_ln214_fu_1482_p1;
wire   [6:0] empty_55_fu_1485_p2;
wire   [7:0] p_shl7_fu_1499_p3;
wire   [9:0] p_shl6_fu_1491_p3;
wire  signed [9:0] p_shl7_cast_fu_1507_p1;
wire   [0:0] tmp_s_fu_1520_p13;
wire   [0:0] tmp_1_fu_1551_p13;
wire   [0:0] tmp_2_fu_1582_p13;
wire   [0:0] tmp_3_fu_1613_p13;
wire   [0:0] tmp_4_fu_1644_p13;
wire   [0:0] tmp_5_fu_1675_p13;
wire   [0:0] tmp_s_fu_1520_p15;
wire   [0:0] tmp_1_fu_1551_p15;
wire   [0:0] tmp_2_fu_1582_p15;
wire   [0:0] tmp_3_fu_1613_p15;
wire   [0:0] tmp_4_fu_1644_p15;
wire   [0:0] tmp_5_fu_1675_p15;
wire   [0:0] tmp_6_fu_1706_p13;
wire   [0:0] tmp_7_fu_1737_p13;
wire   [0:0] tmp_8_fu_1768_p13;
wire   [0:0] tmp_9_fu_1799_p13;
wire   [0:0] tmp_10_fu_1830_p13;
wire   [0:0] tmp_11_fu_1861_p13;
wire   [0:0] tmp_12_fu_1892_p13;
wire   [0:0] tmp_7_fu_1737_p15;
wire   [0:0] tmp_8_fu_1768_p15;
wire   [0:0] tmp_9_fu_1799_p15;
wire   [0:0] tmp_10_fu_1830_p15;
wire   [0:0] tmp_11_fu_1861_p15;
wire   [0:0] tmp_12_fu_1892_p15;
wire   [0:0] tmp_13_fu_1923_p13;
wire   [0:0] tmp_13_fu_1923_p15;
wire   [0:0] tmp_6_fu_1706_p15;
wire   [9:0] empty_56_fu_1511_p2;
wire   [9:0] trunc_ln212_1_cast_fu_1517_p1;
wire   [9:0] add_ln217_fu_1961_p2;
wire  signed [31:0] sext_ln217_fu_1967_p1;
wire   [0:0] select_ln217_fu_1954_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [2:0] tmp_s_fu_1520_p1;
wire   [2:0] tmp_s_fu_1520_p3;
wire   [2:0] tmp_s_fu_1520_p5;
wire   [2:0] tmp_s_fu_1520_p7;
wire  signed [2:0] tmp_s_fu_1520_p9;
wire  signed [2:0] tmp_s_fu_1520_p11;
wire   [2:0] tmp_1_fu_1551_p1;
wire   [2:0] tmp_1_fu_1551_p3;
wire   [2:0] tmp_1_fu_1551_p5;
wire   [2:0] tmp_1_fu_1551_p7;
wire  signed [2:0] tmp_1_fu_1551_p9;
wire  signed [2:0] tmp_1_fu_1551_p11;
wire   [2:0] tmp_2_fu_1582_p1;
wire   [2:0] tmp_2_fu_1582_p3;
wire   [2:0] tmp_2_fu_1582_p5;
wire   [2:0] tmp_2_fu_1582_p7;
wire  signed [2:0] tmp_2_fu_1582_p9;
wire  signed [2:0] tmp_2_fu_1582_p11;
wire   [2:0] tmp_3_fu_1613_p1;
wire   [2:0] tmp_3_fu_1613_p3;
wire   [2:0] tmp_3_fu_1613_p5;
wire   [2:0] tmp_3_fu_1613_p7;
wire  signed [2:0] tmp_3_fu_1613_p9;
wire  signed [2:0] tmp_3_fu_1613_p11;
wire   [2:0] tmp_4_fu_1644_p1;
wire   [2:0] tmp_4_fu_1644_p3;
wire   [2:0] tmp_4_fu_1644_p5;
wire   [2:0] tmp_4_fu_1644_p7;
wire  signed [2:0] tmp_4_fu_1644_p9;
wire  signed [2:0] tmp_4_fu_1644_p11;
wire   [2:0] tmp_5_fu_1675_p1;
wire   [2:0] tmp_5_fu_1675_p3;
wire   [2:0] tmp_5_fu_1675_p5;
wire   [2:0] tmp_5_fu_1675_p7;
wire  signed [2:0] tmp_5_fu_1675_p9;
wire  signed [2:0] tmp_5_fu_1675_p11;
wire   [2:0] tmp_6_fu_1706_p1;
wire   [2:0] tmp_6_fu_1706_p3;
wire   [2:0] tmp_6_fu_1706_p5;
wire   [2:0] tmp_6_fu_1706_p7;
wire  signed [2:0] tmp_6_fu_1706_p9;
wire  signed [2:0] tmp_6_fu_1706_p11;
wire   [2:0] tmp_7_fu_1737_p1;
wire   [2:0] tmp_7_fu_1737_p3;
wire   [2:0] tmp_7_fu_1737_p5;
wire   [2:0] tmp_7_fu_1737_p7;
wire  signed [2:0] tmp_7_fu_1737_p9;
wire  signed [2:0] tmp_7_fu_1737_p11;
wire   [2:0] tmp_8_fu_1768_p1;
wire   [2:0] tmp_8_fu_1768_p3;
wire   [2:0] tmp_8_fu_1768_p5;
wire   [2:0] tmp_8_fu_1768_p7;
wire  signed [2:0] tmp_8_fu_1768_p9;
wire  signed [2:0] tmp_8_fu_1768_p11;
wire   [2:0] tmp_9_fu_1799_p1;
wire   [2:0] tmp_9_fu_1799_p3;
wire   [2:0] tmp_9_fu_1799_p5;
wire   [2:0] tmp_9_fu_1799_p7;
wire  signed [2:0] tmp_9_fu_1799_p9;
wire  signed [2:0] tmp_9_fu_1799_p11;
wire   [2:0] tmp_10_fu_1830_p1;
wire   [2:0] tmp_10_fu_1830_p3;
wire   [2:0] tmp_10_fu_1830_p5;
wire   [2:0] tmp_10_fu_1830_p7;
wire  signed [2:0] tmp_10_fu_1830_p9;
wire  signed [2:0] tmp_10_fu_1830_p11;
wire   [2:0] tmp_11_fu_1861_p1;
wire   [2:0] tmp_11_fu_1861_p3;
wire   [2:0] tmp_11_fu_1861_p5;
wire   [2:0] tmp_11_fu_1861_p7;
wire  signed [2:0] tmp_11_fu_1861_p9;
wire  signed [2:0] tmp_11_fu_1861_p11;
wire   [2:0] tmp_12_fu_1892_p1;
wire   [2:0] tmp_12_fu_1892_p3;
wire   [2:0] tmp_12_fu_1892_p5;
wire   [2:0] tmp_12_fu_1892_p7;
wire  signed [2:0] tmp_12_fu_1892_p9;
wire  signed [2:0] tmp_12_fu_1892_p11;
wire   [2:0] tmp_13_fu_1923_p1;
wire   [2:0] tmp_13_fu_1923_p3;
wire   [2:0] tmp_13_fu_1923_p5;
wire   [2:0] tmp_13_fu_1923_p7;
wire  signed [2:0] tmp_13_fu_1923_p9;
wire  signed [2:0] tmp_13_fu_1923_p11;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 beat_fu_218 = 512'd0;
#0 x_fu_222 = 3'd0;
#0 y_fu_226 = 3'd0;
#0 indvar_flatten43_fu_230 = 6'd0;
#0 t_fu_234 = 3'd0;
#0 indvar_flatten58_fu_238 = 8'd0;
#0 ap_done_reg = 1'b0;
end

predecoder_kernel_sparsemux_13_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_13_3_1_1_1_U2733(
    .din0(correction_q0),
    .din1(correction_1_q0),
    .din2(correction_2_q0),
    .din3(correction_3_q0),
    .din4(correction_4_q0),
    .din5(correction_5_q0),
    .def(tmp_s_fu_1520_p13),
    .sel(select_ln212_1_reg_2042),
    .dout(tmp_s_fu_1520_p15)
);

predecoder_kernel_sparsemux_13_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_13_3_1_1_1_U2734(
    .din0(correction_6_q0),
    .din1(correction_7_q0),
    .din2(correction_8_q0),
    .din3(correction_9_q0),
    .din4(correction_10_q0),
    .din5(correction_11_q0),
    .def(tmp_1_fu_1551_p13),
    .sel(select_ln212_1_reg_2042),
    .dout(tmp_1_fu_1551_p15)
);

predecoder_kernel_sparsemux_13_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_13_3_1_1_1_U2735(
    .din0(correction_12_q0),
    .din1(correction_13_q0),
    .din2(correction_14_q0),
    .din3(correction_15_q0),
    .din4(correction_16_q0),
    .din5(correction_17_q0),
    .def(tmp_2_fu_1582_p13),
    .sel(select_ln212_1_reg_2042),
    .dout(tmp_2_fu_1582_p15)
);

predecoder_kernel_sparsemux_13_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_13_3_1_1_1_U2736(
    .din0(correction_18_q0),
    .din1(correction_19_q0),
    .din2(correction_20_q0),
    .din3(correction_21_q0),
    .din4(correction_22_q0),
    .din5(correction_23_q0),
    .def(tmp_3_fu_1613_p13),
    .sel(select_ln212_1_reg_2042),
    .dout(tmp_3_fu_1613_p15)
);

predecoder_kernel_sparsemux_13_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_13_3_1_1_1_U2737(
    .din0(correction_24_q0),
    .din1(correction_25_q0),
    .din2(correction_26_q0),
    .din3(correction_27_q0),
    .din4(correction_28_q0),
    .din5(correction_29_q0),
    .def(tmp_4_fu_1644_p13),
    .sel(select_ln212_1_reg_2042),
    .dout(tmp_4_fu_1644_p15)
);

predecoder_kernel_sparsemux_13_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_13_3_1_1_1_U2738(
    .din0(correction_30_q0),
    .din1(correction_31_q0),
    .din2(correction_32_q0),
    .din3(correction_33_q0),
    .din4(correction_34_q0),
    .din5(correction_35_q0),
    .def(tmp_5_fu_1675_p13),
    .sel(select_ln212_1_reg_2042),
    .dout(tmp_5_fu_1675_p15)
);

predecoder_kernel_sparsemux_13_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_13_3_1_1_1_U2739(
    .din0(tmp_s_fu_1520_p15),
    .din1(tmp_1_fu_1551_p15),
    .din2(tmp_2_fu_1582_p15),
    .din3(tmp_3_fu_1613_p15),
    .din4(tmp_4_fu_1644_p15),
    .din5(tmp_5_fu_1675_p15),
    .def(tmp_6_fu_1706_p13),
    .sel(select_ln214_reg_2059),
    .dout(tmp_6_fu_1706_p15)
);

predecoder_kernel_sparsemux_13_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_13_3_1_1_1_U2740(
    .din0(correction_36_q0),
    .din1(correction_37_q0),
    .din2(correction_38_q0),
    .din3(correction_39_q0),
    .din4(correction_40_q0),
    .din5(correction_41_q0),
    .def(tmp_7_fu_1737_p13),
    .sel(select_ln212_1_reg_2042),
    .dout(tmp_7_fu_1737_p15)
);

predecoder_kernel_sparsemux_13_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_13_3_1_1_1_U2741(
    .din0(correction_42_q0),
    .din1(correction_43_q0),
    .din2(correction_44_q0),
    .din3(correction_45_q0),
    .din4(correction_46_q0),
    .din5(correction_47_q0),
    .def(tmp_8_fu_1768_p13),
    .sel(select_ln212_1_reg_2042),
    .dout(tmp_8_fu_1768_p15)
);

predecoder_kernel_sparsemux_13_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_13_3_1_1_1_U2742(
    .din0(correction_48_q0),
    .din1(correction_49_q0),
    .din2(correction_50_q0),
    .din3(correction_51_q0),
    .din4(correction_52_q0),
    .din5(correction_53_q0),
    .def(tmp_9_fu_1799_p13),
    .sel(select_ln212_1_reg_2042),
    .dout(tmp_9_fu_1799_p15)
);

predecoder_kernel_sparsemux_13_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_13_3_1_1_1_U2743(
    .din0(correction_54_q0),
    .din1(correction_55_q0),
    .din2(correction_56_q0),
    .din3(correction_57_q0),
    .din4(correction_58_q0),
    .din5(correction_59_q0),
    .def(tmp_10_fu_1830_p13),
    .sel(select_ln212_1_reg_2042),
    .dout(tmp_10_fu_1830_p15)
);

predecoder_kernel_sparsemux_13_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_13_3_1_1_1_U2744(
    .din0(correction_60_q0),
    .din1(correction_61_q0),
    .din2(correction_62_q0),
    .din3(correction_63_q0),
    .din4(correction_64_q0),
    .din5(correction_65_q0),
    .def(tmp_11_fu_1861_p13),
    .sel(select_ln212_1_reg_2042),
    .dout(tmp_11_fu_1861_p15)
);

predecoder_kernel_sparsemux_13_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_13_3_1_1_1_U2745(
    .din0(correction_66_q0),
    .din1(correction_67_q0),
    .din2(correction_68_q0),
    .din3(correction_69_q0),
    .din4(correction_70_q0),
    .din5(correction_71_q0),
    .def(tmp_12_fu_1892_p13),
    .sel(select_ln212_1_reg_2042),
    .dout(tmp_12_fu_1892_p15)
);

predecoder_kernel_sparsemux_13_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_13_3_1_1_1_U2746(
    .din0(tmp_7_fu_1737_p15),
    .din1(tmp_8_fu_1768_p15),
    .din2(tmp_9_fu_1799_p15),
    .din3(tmp_10_fu_1830_p15),
    .din4(tmp_11_fu_1861_p15),
    .din5(tmp_12_fu_1892_p15),
    .def(tmp_13_fu_1923_p13),
    .sel(select_ln214_reg_2059),
    .dout(tmp_13_fu_1923_p15)
);

predecoder_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            beat_fu_218 <= 512'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            beat_fu_218 <= beat_1_fu_1971_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln213_fu_1218_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten43_fu_230 <= select_ln214_1_fu_1418_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten43_fu_230 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln213_fu_1218_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten58_fu_238 <= add_ln213_1_fu_1224_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten58_fu_238 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln213_fu_1218_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            t_fu_234 <= select_ln213_fu_1280_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            t_fu_234 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln213_fu_1218_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_222 <= add_ln215_fu_1406_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_222 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln213_fu_1218_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_226 <= select_ln214_fu_1308_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_226 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln212_1_reg_2042 <= select_ln212_1_fu_1300_p3;
        select_ln213_reg_2036 <= select_ln213_fu_1280_p3;
        select_ln214_reg_2059 <= select_ln214_fu_1308_p3;
        trunc_ln213_reg_2066 <= trunc_ln213_fu_1316_p1;
    end
end

always @ (*) begin
    if (((icmp_ln213_fu_1218_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten43_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten43_load = indvar_flatten43_fu_230;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten58_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten58_load = indvar_flatten58_fu_238;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_t_load = 3'd0;
    end else begin
        ap_sig_allocacmp_t_load = t_fu_234;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_load = 3'd0;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_222;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_y_load = 3'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_226;
    end
end

always @ (*) begin
    if (((icmp_ln213_fu_1218_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        beat_2_out_ap_vld = 1'b1;
    end else begin
        beat_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_10_ce0 = 1'b1;
    end else begin
        correction_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_11_ce0 = 1'b1;
    end else begin
        correction_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_12_ce0 = 1'b1;
    end else begin
        correction_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_13_ce0 = 1'b1;
    end else begin
        correction_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_14_ce0 = 1'b1;
    end else begin
        correction_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_15_ce0 = 1'b1;
    end else begin
        correction_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_16_ce0 = 1'b1;
    end else begin
        correction_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_17_ce0 = 1'b1;
    end else begin
        correction_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_18_ce0 = 1'b1;
    end else begin
        correction_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_19_ce0 = 1'b1;
    end else begin
        correction_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_1_ce0 = 1'b1;
    end else begin
        correction_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_20_ce0 = 1'b1;
    end else begin
        correction_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_21_ce0 = 1'b1;
    end else begin
        correction_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_22_ce0 = 1'b1;
    end else begin
        correction_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_23_ce0 = 1'b1;
    end else begin
        correction_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_24_ce0 = 1'b1;
    end else begin
        correction_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_25_ce0 = 1'b1;
    end else begin
        correction_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_26_ce0 = 1'b1;
    end else begin
        correction_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_27_ce0 = 1'b1;
    end else begin
        correction_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_28_ce0 = 1'b1;
    end else begin
        correction_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_29_ce0 = 1'b1;
    end else begin
        correction_29_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_2_ce0 = 1'b1;
    end else begin
        correction_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_30_ce0 = 1'b1;
    end else begin
        correction_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_31_ce0 = 1'b1;
    end else begin
        correction_31_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_32_ce0 = 1'b1;
    end else begin
        correction_32_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_33_ce0 = 1'b1;
    end else begin
        correction_33_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_34_ce0 = 1'b1;
    end else begin
        correction_34_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_35_ce0 = 1'b1;
    end else begin
        correction_35_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_36_ce0 = 1'b1;
    end else begin
        correction_36_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_37_ce0 = 1'b1;
    end else begin
        correction_37_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_38_ce0 = 1'b1;
    end else begin
        correction_38_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_39_ce0 = 1'b1;
    end else begin
        correction_39_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_3_ce0 = 1'b1;
    end else begin
        correction_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_40_ce0 = 1'b1;
    end else begin
        correction_40_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_41_ce0 = 1'b1;
    end else begin
        correction_41_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_42_ce0 = 1'b1;
    end else begin
        correction_42_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_43_ce0 = 1'b1;
    end else begin
        correction_43_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_44_ce0 = 1'b1;
    end else begin
        correction_44_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_45_ce0 = 1'b1;
    end else begin
        correction_45_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_46_ce0 = 1'b1;
    end else begin
        correction_46_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_47_ce0 = 1'b1;
    end else begin
        correction_47_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_48_ce0 = 1'b1;
    end else begin
        correction_48_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_49_ce0 = 1'b1;
    end else begin
        correction_49_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_4_ce0 = 1'b1;
    end else begin
        correction_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_50_ce0 = 1'b1;
    end else begin
        correction_50_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_51_ce0 = 1'b1;
    end else begin
        correction_51_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_52_ce0 = 1'b1;
    end else begin
        correction_52_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_53_ce0 = 1'b1;
    end else begin
        correction_53_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_54_ce0 = 1'b1;
    end else begin
        correction_54_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_55_ce0 = 1'b1;
    end else begin
        correction_55_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_56_ce0 = 1'b1;
    end else begin
        correction_56_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_57_ce0 = 1'b1;
    end else begin
        correction_57_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_58_ce0 = 1'b1;
    end else begin
        correction_58_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_59_ce0 = 1'b1;
    end else begin
        correction_59_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_5_ce0 = 1'b1;
    end else begin
        correction_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_60_ce0 = 1'b1;
    end else begin
        correction_60_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_61_ce0 = 1'b1;
    end else begin
        correction_61_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_62_ce0 = 1'b1;
    end else begin
        correction_62_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_63_ce0 = 1'b1;
    end else begin
        correction_63_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_64_ce0 = 1'b1;
    end else begin
        correction_64_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_65_ce0 = 1'b1;
    end else begin
        correction_65_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_66_ce0 = 1'b1;
    end else begin
        correction_66_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_67_ce0 = 1'b1;
    end else begin
        correction_67_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_68_ce0 = 1'b1;
    end else begin
        correction_68_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_69_ce0 = 1'b1;
    end else begin
        correction_69_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_6_ce0 = 1'b1;
    end else begin
        correction_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_70_ce0 = 1'b1;
    end else begin
        correction_70_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_71_ce0 = 1'b1;
    end else begin
        correction_71_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_7_ce0 = 1'b1;
    end else begin
        correction_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_8_ce0 = 1'b1;
    end else begin
        correction_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_9_ce0 = 1'b1;
    end else begin
        correction_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        correction_ce0 = 1'b1;
    end else begin
        correction_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln213_1_fu_1224_p2 = (ap_sig_allocacmp_indvar_flatten58_load + 8'd1);

assign add_ln213_fu_1242_p2 = (ap_sig_allocacmp_t_load + 3'd1);

assign add_ln214_1_fu_1412_p2 = (ap_sig_allocacmp_indvar_flatten43_load + 6'd1);

assign add_ln214_fu_1288_p2 = (select_ln212_fu_1254_p3 + 3'd1);

assign add_ln215_fu_1406_p2 = (select_ln212_1_fu_1300_p3 + 3'd1);

assign add_ln217_fu_1961_p2 = (empty_56_fu_1511_p2 + trunc_ln212_1_cast_fu_1517_p1);

assign and_ln212_fu_1274_p2 = (xor_ln212_fu_1262_p2 & icmp_ln215_fu_1268_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    beat_1_fu_1971_p4 = beat_fu_218;
    beat_1_fu_1971_p4[sext_ln217_fu_1967_p1] = |(select_ln217_fu_1954_p3);
end

assign beat_2_out = beat_fu_218;

assign correction_10_address0 = zext_ln212_fu_1330_p1;

assign correction_11_address0 = zext_ln212_fu_1330_p1;

assign correction_12_address0 = zext_ln212_fu_1330_p1;

assign correction_13_address0 = zext_ln212_fu_1330_p1;

assign correction_14_address0 = zext_ln212_fu_1330_p1;

assign correction_15_address0 = zext_ln212_fu_1330_p1;

assign correction_16_address0 = zext_ln212_fu_1330_p1;

assign correction_17_address0 = zext_ln212_fu_1330_p1;

assign correction_18_address0 = zext_ln212_fu_1330_p1;

assign correction_19_address0 = zext_ln212_fu_1330_p1;

assign correction_1_address0 = zext_ln212_fu_1330_p1;

assign correction_20_address0 = zext_ln212_fu_1330_p1;

assign correction_21_address0 = zext_ln212_fu_1330_p1;

assign correction_22_address0 = zext_ln212_fu_1330_p1;

assign correction_23_address0 = zext_ln212_fu_1330_p1;

assign correction_24_address0 = zext_ln212_fu_1330_p1;

assign correction_25_address0 = zext_ln212_fu_1330_p1;

assign correction_26_address0 = zext_ln212_fu_1330_p1;

assign correction_27_address0 = zext_ln212_fu_1330_p1;

assign correction_28_address0 = zext_ln212_fu_1330_p1;

assign correction_29_address0 = zext_ln212_fu_1330_p1;

assign correction_2_address0 = zext_ln212_fu_1330_p1;

assign correction_30_address0 = zext_ln212_fu_1330_p1;

assign correction_31_address0 = zext_ln212_fu_1330_p1;

assign correction_32_address0 = zext_ln212_fu_1330_p1;

assign correction_33_address0 = zext_ln212_fu_1330_p1;

assign correction_34_address0 = zext_ln212_fu_1330_p1;

assign correction_35_address0 = zext_ln212_fu_1330_p1;

assign correction_36_address0 = zext_ln212_fu_1330_p1;

assign correction_37_address0 = zext_ln212_fu_1330_p1;

assign correction_38_address0 = zext_ln212_fu_1330_p1;

assign correction_39_address0 = zext_ln212_fu_1330_p1;

assign correction_3_address0 = zext_ln212_fu_1330_p1;

assign correction_40_address0 = zext_ln212_fu_1330_p1;

assign correction_41_address0 = zext_ln212_fu_1330_p1;

assign correction_42_address0 = zext_ln212_fu_1330_p1;

assign correction_43_address0 = zext_ln212_fu_1330_p1;

assign correction_44_address0 = zext_ln212_fu_1330_p1;

assign correction_45_address0 = zext_ln212_fu_1330_p1;

assign correction_46_address0 = zext_ln212_fu_1330_p1;

assign correction_47_address0 = zext_ln212_fu_1330_p1;

assign correction_48_address0 = zext_ln212_fu_1330_p1;

assign correction_49_address0 = zext_ln212_fu_1330_p1;

assign correction_4_address0 = zext_ln212_fu_1330_p1;

assign correction_50_address0 = zext_ln212_fu_1330_p1;

assign correction_51_address0 = zext_ln212_fu_1330_p1;

assign correction_52_address0 = zext_ln212_fu_1330_p1;

assign correction_53_address0 = zext_ln212_fu_1330_p1;

assign correction_54_address0 = zext_ln212_fu_1330_p1;

assign correction_55_address0 = zext_ln212_fu_1330_p1;

assign correction_56_address0 = zext_ln212_fu_1330_p1;

assign correction_57_address0 = zext_ln212_fu_1330_p1;

assign correction_58_address0 = zext_ln212_fu_1330_p1;

assign correction_59_address0 = zext_ln212_fu_1330_p1;

assign correction_5_address0 = zext_ln212_fu_1330_p1;

assign correction_60_address0 = zext_ln212_fu_1330_p1;

assign correction_61_address0 = zext_ln212_fu_1330_p1;

assign correction_62_address0 = zext_ln212_fu_1330_p1;

assign correction_63_address0 = zext_ln212_fu_1330_p1;

assign correction_64_address0 = zext_ln212_fu_1330_p1;

assign correction_65_address0 = zext_ln212_fu_1330_p1;

assign correction_66_address0 = zext_ln212_fu_1330_p1;

assign correction_67_address0 = zext_ln212_fu_1330_p1;

assign correction_68_address0 = zext_ln212_fu_1330_p1;

assign correction_69_address0 = zext_ln212_fu_1330_p1;

assign correction_6_address0 = zext_ln212_fu_1330_p1;

assign correction_70_address0 = zext_ln212_fu_1330_p1;

assign correction_71_address0 = zext_ln212_fu_1330_p1;

assign correction_7_address0 = zext_ln212_fu_1330_p1;

assign correction_8_address0 = zext_ln212_fu_1330_p1;

assign correction_9_address0 = zext_ln212_fu_1330_p1;

assign correction_address0 = zext_ln212_fu_1330_p1;

assign empty_55_fu_1485_p2 = (empty_fu_1476_p2 + zext_ln214_fu_1482_p1);

assign empty_56_fu_1511_p2 = ($signed(p_shl6_fu_1491_p3) - $signed(p_shl7_cast_fu_1507_p1));

assign empty_fu_1476_p2 = (p_shl4_cast_fu_1461_p1 - p_shl5_cast_fu_1472_p1);

assign icmp_ln213_fu_1218_p2 = ((ap_sig_allocacmp_indvar_flatten58_load == 8'd216) ? 1'b1 : 1'b0);

assign icmp_ln214_fu_1248_p2 = ((ap_sig_allocacmp_indvar_flatten43_load == 6'd36) ? 1'b1 : 1'b0);

assign icmp_ln215_fu_1268_p2 = ((ap_sig_allocacmp_x_load == 3'd6) ? 1'b1 : 1'b0);

assign lshr_ln2_fu_1320_p4 = {{select_ln213_fu_1280_p3[2:1]}};

assign or_ln212_fu_1294_p2 = (icmp_ln214_fu_1248_p2 | and_ln212_fu_1274_p2);

assign p_shl4_cast_fu_1461_p1 = p_shl4_fu_1454_p3;

assign p_shl4_fu_1454_p3 = {{select_ln213_reg_2036}, {3'd0}};

assign p_shl5_cast_fu_1472_p1 = p_shl5_fu_1465_p3;

assign p_shl5_fu_1465_p3 = {{select_ln213_reg_2036}, {1'd0}};

assign p_shl6_fu_1491_p3 = {{empty_55_fu_1485_p2}, {3'd0}};

assign p_shl7_cast_fu_1507_p1 = $signed(p_shl7_fu_1499_p3);

assign p_shl7_fu_1499_p3 = {{empty_55_fu_1485_p2}, {1'd0}};

assign select_ln212_1_fu_1300_p3 = ((or_ln212_fu_1294_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_x_load);

assign select_ln212_fu_1254_p3 = ((icmp_ln214_fu_1248_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_y_load);

assign select_ln213_fu_1280_p3 = ((icmp_ln214_fu_1248_p2[0:0] == 1'b1) ? add_ln213_fu_1242_p2 : ap_sig_allocacmp_t_load);

assign select_ln214_1_fu_1418_p3 = ((icmp_ln214_fu_1248_p2[0:0] == 1'b1) ? 6'd1 : add_ln214_1_fu_1412_p2);

assign select_ln214_fu_1308_p3 = ((and_ln212_fu_1274_p2[0:0] == 1'b1) ? add_ln214_fu_1288_p2 : select_ln212_fu_1254_p3);

assign select_ln217_fu_1954_p3 = ((trunc_ln213_reg_2066[0:0] == 1'b1) ? tmp_13_fu_1923_p15 : tmp_6_fu_1706_p15);

assign sext_ln217_fu_1967_p1 = $signed(add_ln217_fu_1961_p2);

assign tmp_10_fu_1830_p13 = 'bx;

assign tmp_11_fu_1861_p13 = 'bx;

assign tmp_12_fu_1892_p13 = 'bx;

assign tmp_13_fu_1923_p13 = 'bx;

assign tmp_1_fu_1551_p13 = 'bx;

assign tmp_2_fu_1582_p13 = 'bx;

assign tmp_3_fu_1613_p13 = 'bx;

assign tmp_4_fu_1644_p13 = 'bx;

assign tmp_5_fu_1675_p13 = 'bx;

assign tmp_6_fu_1706_p13 = 'bx;

assign tmp_7_fu_1737_p13 = 'bx;

assign tmp_8_fu_1768_p13 = 'bx;

assign tmp_9_fu_1799_p13 = 'bx;

assign tmp_s_fu_1520_p13 = 'bx;

assign trunc_ln212_1_cast_fu_1517_p1 = select_ln212_1_reg_2042;

assign trunc_ln213_fu_1316_p1 = select_ln213_fu_1280_p3[0:0];

assign xor_ln212_fu_1262_p2 = (icmp_ln214_fu_1248_p2 ^ 1'd1);

assign zext_ln212_fu_1330_p1 = lshr_ln2_fu_1320_p4;

assign zext_ln214_fu_1482_p1 = select_ln214_reg_2059;

endmodule //predecoder_kernel_edge_correction_Pipeline_VITIS_LOOP_213_5_VITIS_LOOP_214_6_VITIS_LOOP_215_7
