// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module predecoder_kernel_conv1x1_output_layer (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s2_dout,
        s2_num_data_valid,
        s2_fifo_cap,
        s2_empty_n,
        s2_read,
        s3_din,
        s3_num_data_valid,
        s3_fifo_cap,
        s3_full_n,
        s3_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [95:0] s2_dout;
input  [3:0] s2_num_data_valid;
input  [3:0] s2_fifo_cap;
input   s2_empty_n;
output   s2_read;
output  [447:0] s3_din;
input  [3:0] s3_num_data_valid;
input  [3:0] s3_fifo_cap;
input   s3_full_n;
output   s3_write;
output   start_out;
output   start_write;

reg ap_idle;
reg s2_read;
reg s3_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln131_fu_177_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s2_blk_n;
wire    ap_block_pp0_stage0;
reg    s3_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] a_fu_194_p1;
reg   [7:0] a_reg_1267;
wire   [7:0] tmp_fu_202_p4;
reg   [7:0] tmp_reg_1277;
reg   [7:0] tmp_reg_1277_pp0_iter2_reg;
reg   [7:0] tmp_reg_1277_pp0_iter3_reg;
reg   [7:0] tmp_10_reg_1290;
reg   [7:0] tmp_10_reg_1290_pp0_iter2_reg;
reg   [7:0] tmp_10_reg_1290_pp0_iter3_reg;
reg   [7:0] tmp_10_reg_1290_pp0_iter4_reg;
reg   [7:0] tmp_12_reg_1299;
reg   [7:0] tmp_12_reg_1299_pp0_iter2_reg;
reg   [7:0] tmp_12_reg_1299_pp0_iter3_reg;
reg   [7:0] tmp_14_reg_1309;
reg   [7:0] tmp_14_reg_1309_pp0_iter2_reg;
reg   [7:0] tmp_14_reg_1309_pp0_iter3_reg;
reg   [7:0] tmp_17_reg_1317;
reg   [7:0] tmp_17_reg_1317_pp0_iter2_reg;
reg   [7:0] tmp_17_reg_1317_pp0_iter3_reg;
reg   [7:0] tmp_17_reg_1317_pp0_iter4_reg;
reg   [7:0] tmp_17_reg_1317_pp0_iter5_reg;
reg   [7:0] tmp_17_reg_1317_pp0_iter6_reg;
reg   [7:0] tmp_21_reg_1326;
reg   [7:0] tmp_21_reg_1326_pp0_iter2_reg;
reg   [7:0] tmp_21_reg_1326_pp0_iter3_reg;
reg   [7:0] tmp_23_reg_1334;
reg   [7:0] tmp_23_reg_1334_pp0_iter2_reg;
reg   [7:0] tmp_23_reg_1334_pp0_iter3_reg;
reg   [7:0] tmp_23_reg_1334_pp0_iter4_reg;
reg   [7:0] tmp_25_reg_1342;
reg   [7:0] tmp_25_reg_1342_pp0_iter2_reg;
reg   [7:0] tmp_28_reg_1349;
reg   [7:0] tmp_28_reg_1349_pp0_iter2_reg;
reg   [7:0] tmp_28_reg_1349_pp0_iter3_reg;
reg   [7:0] tmp_31_reg_1356;
reg   [7:0] tmp_31_reg_1356_pp0_iter2_reg;
reg   [7:0] tmp_31_reg_1356_pp0_iter3_reg;
reg   [7:0] tmp_31_reg_1356_pp0_iter4_reg;
reg   [7:0] tmp_31_reg_1356_pp0_iter5_reg;
reg   [7:0] tmp_32_reg_1363;
reg   [7:0] tmp_32_reg_1363_pp0_iter2_reg;
reg   [7:0] tmp_32_reg_1363_pp0_iter3_reg;
reg   [7:0] tmp_32_reg_1363_pp0_iter4_reg;
reg   [7:0] tmp_32_reg_1363_pp0_iter5_reg;
wire   [15:0] zext_ln142_1_fu_316_p1;
reg   [15:0] zext_ln142_1_reg_1371;
wire  signed [15:0] acc_5_fu_334_p2;
wire   [10:0] sub_ln142_11_fu_350_p2;
reg   [10:0] sub_ln142_11_reg_1407;
wire   [15:0] zext_ln142_39_fu_407_p1;
wire   [11:0] sub_ln142_fu_432_p2;
reg   [11:0] sub_ln142_reg_1422;
wire  signed [10:0] sub_ln142_2_fu_452_p2;
reg  signed [10:0] sub_ln142_2_reg_1427;
reg  signed [10:0] sub_ln142_2_reg_1427_pp0_iter5_reg;
wire   [13:0] zext_ln142_49_fu_461_p1;
wire   [13:0] sub_ln142_4_fu_485_p2;
reg  signed [13:0] sub_ln142_4_reg_1443;
(* use_dsp48 = "no" *) wire   [15:0] add_ln144_13_fu_584_p2;
reg   [15:0] add_ln144_13_reg_1458;
reg  signed [15:0] add_ln144_13_reg_1458_pp0_iter5_reg;
wire   [11:0] sub_ln142_13_fu_662_p2;
reg   [11:0] sub_ln142_13_reg_1463;
wire   [15:0] sub_ln142_20_fu_679_p2;
reg   [15:0] sub_ln142_20_reg_1468;
wire   [15:0] add_ln144_24_fu_726_p2;
reg   [15:0] add_ln144_24_reg_1478;
wire   [16:0] add_ln144_6_fu_825_p2;
reg   [16:0] add_ln144_6_reg_1488;
wire   [17:0] acc_9_fu_950_p2;
reg   [17:0] acc_9_reg_1503;
reg   [17:0] acc_9_reg_1503_pp0_iter7_reg;
(* use_dsp48 = "no" *) wire   [13:0] add_ln144_20_fu_1018_p2;
reg   [13:0] add_ln144_20_reg_1518;
wire   [17:0] acc_10_fu_1102_p2;
reg   [17:0] acc_10_reg_1533;
(* use_dsp48 = "no" *) wire   [18:0] acc_11_fu_1111_p2;
reg   [18:0] acc_11_reg_1538;
reg   [7:0] i_fu_152;
wire   [7:0] i_2_fu_183_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] acc_5_fu_334_p0;
wire  signed [7:0] acc_5_fu_334_p1;
wire   [9:0] and_ln142_22_fu_339_p3;
wire   [10:0] zext_ln142_27_fu_346_p1;
wire   [11:0] and_ln_fu_356_p3;
wire   [9:0] and_ln142_1_fu_367_p3;
wire   [12:0] zext_ln142_2_fu_363_p1;
wire   [12:0] zext_ln142_3_fu_374_p1;
wire   [14:0] and_ln142_3_fu_390_p3;
wire   [15:0] zext_ln142_38_fu_387_p1;
wire   [15:0] zext_ln142_5_fu_397_p1;
wire   [10:0] and_ln142_4_fu_410_p3;
wire   [8:0] and_ln142_5_fu_421_p3;
wire   [11:0] zext_ln142_6_fu_417_p1;
wire   [11:0] zext_ln142_7_fu_428_p1;
wire   [9:0] and_ln142_8_fu_441_p3;
wire   [10:0] zext_ln142_10_fu_448_p1;
wire   [10:0] zext_ln142_42_fu_438_p1;
wire   [11:0] and_ln142_9_fu_464_p3;
wire   [12:0] zext_ln142_12_fu_471_p1;
wire   [12:0] sub_ln142_3_fu_475_p2;
wire  signed [13:0] sext_ln142_4_fu_481_p1;
wire   [12:0] add_ln142_fu_378_p2;
wire   [12:0] add_ln144_fu_494_p2;
wire   [11:0] and_ln142_11_fu_504_p3;
wire   [8:0] and_ln142_12_fu_515_p3;
wire   [12:0] zext_ln142_16_fu_522_p1;
wire   [12:0] zext_ln142_15_fu_511_p1;
wire   [12:0] and_ln142_13_fu_532_p3;
wire   [9:0] and_ln142_14_fu_543_p3;
wire   [13:0] zext_ln142_17_fu_539_p1;
wire   [13:0] zext_ln142_18_fu_550_p1;
wire   [13:0] sub_ln142_6_fu_554_p2;
wire   [12:0] sub_ln142_5_fu_526_p2;
wire   [12:0] add_ln144_11_fu_564_p2;
wire  signed [14:0] sext_ln144_11_fu_570_p1;
wire  signed [14:0] sext_ln142_7_fu_560_p1;
wire   [14:0] add_ln144_12_fu_574_p2;
wire  signed [15:0] sext_ln144_12_fu_580_p1;
wire  signed [15:0] grp_fu_1148_p3;
wire   [13:0] and_ln142_20_fu_589_p3;
wire   [14:0] zext_ln142_25_fu_596_p1;
wire   [14:0] sub_ln142_9_fu_600_p2;
wire   [8:0] and_ln142_21_fu_610_p3;
wire  signed [15:0] sext_ln142_13_fu_606_p1;
wire   [15:0] zext_ln142_26_fu_617_p1;
wire  signed [11:0] sext_ln142_14_fu_627_p1;
wire   [11:0] zext_ln142_37_fu_384_p1;
wire   [11:0] sub_ln142_12_fu_630_p2;
wire   [10:0] and_ln142_23_fu_640_p3;
wire   [8:0] and_ln142_24_fu_651_p3;
wire   [11:0] zext_ln142_28_fu_647_p1;
wire   [11:0] zext_ln142_29_fu_658_p1;
wire   [14:0] and_ln142_25_fu_668_p3;
wire   [15:0] zext_ln142_30_fu_675_p1;
wire   [13:0] and_ln142_26_fu_685_p3;
wire   [10:0] and_ln142_27_fu_696_p3;
wire   [14:0] zext_ln142_32_fu_703_p1;
wire   [14:0] zext_ln142_31_fu_692_p1;
wire  signed [14:0] sub_ln142_14_fu_707_p2;
wire  signed [14:0] grp_fu_1157_p3;
wire  signed [14:0] sext_ln142_15_fu_636_p1;
(* use_dsp48 = "no" *) wire   [14:0] add_ln144_23_fu_717_p2;
wire  signed [15:0] sext_ln144_17_fu_722_p1;
wire   [15:0] sub_ln142_10_fu_621_p2;
wire   [10:0] and_ln142_2_fu_732_p3;
wire   [11:0] and_ln142_6_fu_746_p3;
wire   [8:0] and_ln142_7_fu_757_p3;
wire   [12:0] zext_ln142_8_fu_753_p1;
wire   [12:0] zext_ln142_9_fu_764_p1;
wire   [12:0] sub_ln142_1_fu_768_p2;
wire  signed [15:0] sub_ln144_fu_787_p0;
wire   [15:0] grp_fu_1166_p3;
wire   [15:0] zext_ln142_4_fu_739_p1;
(* use_dsp48 = "no" *) wire   [15:0] sub_ln144_fu_787_p2;
wire   [15:0] sext_ln144_2_fu_796_p0;
wire  signed [15:0] grp_fu_1175_p3;
wire  signed [16:0] sext_ln144_2_fu_796_p1;
wire  signed [16:0] sext_ln144_fu_792_p1;
wire  signed [12:0] sext_ln142_fu_743_p1;
wire  signed [12:0] sext_ln142_3_fu_778_p1;
wire   [12:0] add_ln144_4_fu_805_p2;
wire  signed [13:0] sext_ln144_5_fu_811_p1;
wire  signed [13:0] sext_ln142_1_fu_774_p1;
wire   [13:0] add_ln144_5_fu_815_p2;
wire  signed [16:0] sext_ln144_6_fu_821_p1;
wire   [16:0] add_ln144_3_fu_799_p2;
wire   [11:0] and_ln142_16_fu_831_p3;
wire   [12:0] zext_ln142_43_fu_781_p1;
wire   [12:0] zext_ln142_20_fu_838_p1;
wire  signed [12:0] sub_ln142_19_fu_842_p2;
wire   [13:0] and_ln142_28_fu_858_p3;
wire  signed [16:0] sext_ln142_17_fu_855_p1;
wire  signed [16:0] sext_ln142_16_fu_852_p1;
wire   [16:0] add_ln144_25_fu_872_p2;
wire  signed [16:0] sext_ln144_7_fu_869_p1;
wire   [16:0] add_ln144_26_fu_878_p2;
wire  signed [15:0] grp_fu_1184_p3;
wire  signed [17:0] sext_ln144_18_fu_888_p1;
wire  signed [17:0] sext_ln144_8_fu_884_p1;
wire   [17:0] add_ln144_28_fu_891_p2;
wire   [17:0] zext_ln142_33_fu_865_p1;
wire   [11:0] and_ln142_s_fu_906_p3;
wire   [9:0] and_ln142_10_fu_921_p3;
wire  signed [15:0] grp_fu_1193_p3;
wire  signed [17:0] sext_ln144_10_fu_935_p1;
wire  signed [17:0] sext_ln144_1_fu_932_p1;
wire   [17:0] add_ln144_8_fu_938_p2;
wire   [17:0] zext_ln142_14_fu_917_p1;
wire   [17:0] sub_ln144_1_fu_944_p2;
wire   [17:0] zext_ln144_fu_928_p1;
wire   [8:0] and_ln142_17_fu_956_p3;
wire   [13:0] and_ln142_18_fu_967_p3;
wire   [14:0] zext_ln142_23_fu_974_p1;
wire   [14:0] sub_ln142_7_fu_978_p2;
wire   [11:0] and_ln142_19_fu_988_p3;
wire  signed [15:0] sext_ln142_12_fu_984_p1;
wire   [15:0] zext_ln142_24_fu_995_p1;
wire  signed [11:0] sext_ln142_2_fu_903_p1;
wire   [11:0] zext_ln142_22_fu_963_p1;
wire   [11:0] add_ln144_19_fu_1008_p2;
wire  signed [13:0] sext_ln144_14_fu_1014_p1;
wire  signed [13:0] grp_fu_1202_p3;
wire   [12:0] zext_ln142_13_fu_913_p1;
wire   [12:0] sub_ln142_15_fu_1023_p2;
wire   [9:0] and_ln142_29_fu_1033_p3;
wire  signed [13:0] sext_ln142_21_fu_1029_p1;
wire   [13:0] zext_ln142_35_fu_1040_p1;
wire  signed [13:0] sub_ln142_16_fu_1044_p2;
wire  signed [17:0] grp_fu_1211_p3;
wire   [14:0] and_ln142_15_fu_1060_p3;
wire   [15:0] zext_ln142_41_fu_1057_p1;
wire   [15:0] zext_ln142_19_fu_1067_p1;
wire   [15:0] sub_ln142_18_fu_1071_p2;
wire  signed [16:0] grp_fu_1220_p3;
wire  signed [17:0] sext_ln144_4_fu_1081_p1;
wire  signed [17:0] sext_ln142_9_fu_1077_p1;
wire  signed [15:0] grp_fu_1229_p3;
wire  signed [17:0] sext_ln144_13_fu_1090_p1;
wire   [17:0] add_ln144_15_fu_1084_p2;
wire  signed [17:0] sext_ln144_15_fu_1099_p1;
wire   [17:0] add_ln144_17_fu_1093_p2;
wire  signed [15:0] grp_fu_1247_p3;
wire  signed [18:0] sext_ln144_19_fu_1108_p1;
wire  signed [18:0] grp_fu_1238_p3;
wire  signed [31:0] sext_ln137_1_fu_1119_p1;
wire   [50:0] tmp_53_fu_1122_p3;
wire  signed [63:0] sext_ln147_fu_1129_p1;
wire  signed [31:0] sext_ln137_fu_1116_p1;
wire   [424:0] tmp_395_fu_1133_p4;
wire   [7:0] grp_fu_1148_p0;
wire  signed [5:0] grp_fu_1148_p1;
wire   [7:0] grp_fu_1157_p0;
wire  signed [6:0] grp_fu_1157_p1;
wire  signed [10:0] grp_fu_1157_p2;
wire   [7:0] grp_fu_1166_p0;
wire  signed [7:0] grp_fu_1166_p1;
wire   [12:0] grp_fu_1166_p2;
wire   [7:0] grp_fu_1175_p0;
wire   [5:0] grp_fu_1175_p1;
wire   [15:0] grp_fu_1175_p2;
wire   [7:0] grp_fu_1184_p0;
wire  signed [5:0] grp_fu_1184_p1;
wire   [7:0] grp_fu_1193_p0;
wire  signed [7:0] grp_fu_1193_p1;
wire   [7:0] grp_fu_1202_p0;
wire   [4:0] grp_fu_1202_p1;
wire   [7:0] grp_fu_1211_p0;
wire   [6:0] grp_fu_1211_p1;
wire   [17:0] grp_fu_1211_p2;
wire   [7:0] grp_fu_1220_p0;
wire  signed [7:0] grp_fu_1220_p1;
wire   [7:0] grp_fu_1229_p0;
wire  signed [5:0] grp_fu_1229_p1;
wire  signed [15:0] grp_fu_1229_p2;
wire   [7:0] grp_fu_1238_p0;
wire  signed [7:0] grp_fu_1238_p1;
wire   [7:0] grp_fu_1247_p0;
wire  signed [6:0] grp_fu_1247_p1;
reg    grp_fu_1148_ce;
reg    grp_fu_1157_ce;
reg    grp_fu_1166_ce;
reg    grp_fu_1175_ce;
reg    grp_fu_1184_ce;
reg    grp_fu_1193_ce;
reg    grp_fu_1202_ce;
reg    grp_fu_1211_ce;
reg    grp_fu_1220_ce;
reg    grp_fu_1229_ce;
reg    grp_fu_1238_ce;
reg    grp_fu_1247_ce;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [13:0] grp_fu_1148_p00;
wire   [14:0] grp_fu_1157_p00;
wire   [15:0] grp_fu_1166_p00;
wire   [15:0] grp_fu_1166_p20;
wire   [13:0] grp_fu_1175_p00;
wire   [13:0] grp_fu_1184_p00;
wire   [15:0] grp_fu_1193_p00;
wire   [12:0] grp_fu_1202_p00;
wire   [14:0] grp_fu_1211_p00;
wire   [15:0] grp_fu_1238_p00;
wire   [14:0] grp_fu_1247_p00;
reg    ap_condition_281;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_fu_152 = 8'd0;
end

predecoder_kernel_mul_8ns_8s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8s_16_1_1_U2120(
    .din0(acc_5_fu_334_p0),
    .din1(acc_5_fu_334_p1),
    .dout(acc_5_fu_334_p2)
);

predecoder_kernel_mac_muladd_8ns_6s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_6s_16s_16_4_1_U2121(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1148_p0),
    .din1(grp_fu_1148_p1),
    .din2(acc_5_fu_334_p2),
    .ce(grp_fu_1148_ce),
    .dout(grp_fu_1148_p3)
);

predecoder_kernel_mac_muladd_8ns_7s_11s_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 15 ))
mac_muladd_8ns_7s_11s_15_4_1_U2122(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1157_p0),
    .din1(grp_fu_1157_p1),
    .din2(grp_fu_1157_p2),
    .ce(grp_fu_1157_ce),
    .dout(grp_fu_1157_p3)
);

predecoder_kernel_mac_muladd_8ns_8s_13ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8s_13ns_16_4_1_U2123(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1166_p0),
    .din1(grp_fu_1166_p1),
    .din2(grp_fu_1166_p2),
    .ce(grp_fu_1166_ce),
    .dout(grp_fu_1166_p3)
);

predecoder_kernel_mac_muladd_8ns_6ns_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_6ns_16ns_16_4_1_U2124(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1175_p0),
    .din1(grp_fu_1175_p1),
    .din2(grp_fu_1175_p2),
    .ce(grp_fu_1175_ce),
    .dout(grp_fu_1175_p3)
);

predecoder_kernel_mac_muladd_8ns_6s_15s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_6s_15s_16_4_1_U2125(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1184_p0),
    .din1(grp_fu_1184_p1),
    .din2(sub_ln142_14_fu_707_p2),
    .ce(grp_fu_1184_ce),
    .dout(grp_fu_1184_p3)
);

predecoder_kernel_mac_muladd_8ns_8s_14s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_8s_14s_16_4_1_U2126(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1193_p0),
    .din1(grp_fu_1193_p1),
    .din2(sub_ln142_4_reg_1443),
    .ce(grp_fu_1193_ce),
    .dout(grp_fu_1193_p3)
);

predecoder_kernel_mac_muladd_8ns_5ns_13s_14_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 14 ))
mac_muladd_8ns_5ns_13s_14_4_1_U2127(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1202_p0),
    .din1(grp_fu_1202_p1),
    .din2(sub_ln142_19_fu_842_p2),
    .ce(grp_fu_1202_ce),
    .dout(grp_fu_1202_p3)
);

predecoder_kernel_mac_muladd_8ns_7ns_18ns_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_8ns_7ns_18ns_18_4_1_U2128(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1211_p0),
    .din1(grp_fu_1211_p1),
    .din2(grp_fu_1211_p2),
    .ce(grp_fu_1211_ce),
    .dout(grp_fu_1211_p3)
);

predecoder_kernel_mac_muladd_8ns_8s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8s_16s_17_4_1_U2129(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1220_p0),
    .din1(grp_fu_1220_p1),
    .din2(add_ln144_13_reg_1458_pp0_iter5_reg),
    .ce(grp_fu_1220_ce),
    .dout(grp_fu_1220_p3)
);

predecoder_kernel_mac_muladd_8ns_6s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_6s_16s_16_4_1_U2130(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1229_p0),
    .din1(grp_fu_1229_p1),
    .din2(grp_fu_1229_p2),
    .ce(grp_fu_1229_ce),
    .dout(grp_fu_1229_p3)
);

predecoder_kernel_mac_muladd_8ns_8s_18s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 19 ))
mac_muladd_8ns_8s_18s_19_4_1_U2131(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1238_p0),
    .din1(grp_fu_1238_p1),
    .din2(grp_fu_1211_p3),
    .ce(grp_fu_1238_ce),
    .dout(grp_fu_1238_p3)
);

predecoder_kernel_mac_muladd_8ns_7s_14s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 16 ))
mac_muladd_8ns_7s_14s_16_4_1_U2132(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1247_p0),
    .din1(grp_fu_1247_p1),
    .din2(sub_ln142_16_fu_1044_p2),
    .ce(grp_fu_1247_ce),
    .dout(grp_fu_1247_p3)
);

predecoder_kernel_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_281)) begin
        if ((icmp_ln131_fu_177_p2 == 1'd0)) begin
            i_fu_152 <= i_2_fu_183_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_152 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_reg_1267 <= a_fu_194_p1;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        tmp_10_reg_1290 <= {{s2_dout[23:16]}};
        tmp_12_reg_1299 <= {{s2_dout[31:24]}};
        tmp_14_reg_1309 <= {{s2_dout[39:32]}};
        tmp_17_reg_1317 <= {{s2_dout[47:40]}};
        tmp_21_reg_1326 <= {{s2_dout[55:48]}};
        tmp_23_reg_1334 <= {{s2_dout[63:56]}};
        tmp_25_reg_1342 <= {{s2_dout[71:64]}};
        tmp_28_reg_1349 <= {{s2_dout[79:72]}};
        tmp_31_reg_1356 <= {{s2_dout[87:80]}};
        tmp_32_reg_1363 <= {{s2_dout[95:88]}};
        tmp_reg_1277 <= {{s2_dout[15:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        acc_10_reg_1533 <= acc_10_fu_1102_p2;
        acc_11_reg_1538 <= acc_11_fu_1111_p2;
        acc_9_reg_1503 <= acc_9_fu_950_p2;
        acc_9_reg_1503_pp0_iter7_reg <= acc_9_reg_1503;
        add_ln144_13_reg_1458 <= add_ln144_13_fu_584_p2;
        add_ln144_13_reg_1458_pp0_iter5_reg <= add_ln144_13_reg_1458;
        add_ln144_20_reg_1518 <= add_ln144_20_fu_1018_p2;
        add_ln144_24_reg_1478 <= add_ln144_24_fu_726_p2;
        add_ln144_6_reg_1488 <= add_ln144_6_fu_825_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        sub_ln142_11_reg_1407[10 : 2] <= sub_ln142_11_fu_350_p2[10 : 2];
        sub_ln142_13_reg_1463[11 : 1] <= sub_ln142_13_fu_662_p2[11 : 1];
        sub_ln142_20_reg_1468 <= sub_ln142_20_fu_679_p2;
        sub_ln142_2_reg_1427 <= sub_ln142_2_fu_452_p2;
        sub_ln142_2_reg_1427_pp0_iter5_reg <= sub_ln142_2_reg_1427;
        sub_ln142_4_reg_1443 <= sub_ln142_4_fu_485_p2;
        sub_ln142_reg_1422[11 : 1] <= sub_ln142_fu_432_p2[11 : 1];
        tmp_10_reg_1290_pp0_iter2_reg <= tmp_10_reg_1290;
        tmp_10_reg_1290_pp0_iter3_reg <= tmp_10_reg_1290_pp0_iter2_reg;
        tmp_10_reg_1290_pp0_iter4_reg <= tmp_10_reg_1290_pp0_iter3_reg;
        tmp_12_reg_1299_pp0_iter2_reg <= tmp_12_reg_1299;
        tmp_12_reg_1299_pp0_iter3_reg <= tmp_12_reg_1299_pp0_iter2_reg;
        tmp_14_reg_1309_pp0_iter2_reg <= tmp_14_reg_1309;
        tmp_14_reg_1309_pp0_iter3_reg <= tmp_14_reg_1309_pp0_iter2_reg;
        tmp_17_reg_1317_pp0_iter2_reg <= tmp_17_reg_1317;
        tmp_17_reg_1317_pp0_iter3_reg <= tmp_17_reg_1317_pp0_iter2_reg;
        tmp_17_reg_1317_pp0_iter4_reg <= tmp_17_reg_1317_pp0_iter3_reg;
        tmp_17_reg_1317_pp0_iter5_reg <= tmp_17_reg_1317_pp0_iter4_reg;
        tmp_17_reg_1317_pp0_iter6_reg <= tmp_17_reg_1317_pp0_iter5_reg;
        tmp_21_reg_1326_pp0_iter2_reg <= tmp_21_reg_1326;
        tmp_21_reg_1326_pp0_iter3_reg <= tmp_21_reg_1326_pp0_iter2_reg;
        tmp_23_reg_1334_pp0_iter2_reg <= tmp_23_reg_1334;
        tmp_23_reg_1334_pp0_iter3_reg <= tmp_23_reg_1334_pp0_iter2_reg;
        tmp_23_reg_1334_pp0_iter4_reg <= tmp_23_reg_1334_pp0_iter3_reg;
        tmp_25_reg_1342_pp0_iter2_reg <= tmp_25_reg_1342;
        tmp_28_reg_1349_pp0_iter2_reg <= tmp_28_reg_1349;
        tmp_28_reg_1349_pp0_iter3_reg <= tmp_28_reg_1349_pp0_iter2_reg;
        tmp_31_reg_1356_pp0_iter2_reg <= tmp_31_reg_1356;
        tmp_31_reg_1356_pp0_iter3_reg <= tmp_31_reg_1356_pp0_iter2_reg;
        tmp_31_reg_1356_pp0_iter4_reg <= tmp_31_reg_1356_pp0_iter3_reg;
        tmp_31_reg_1356_pp0_iter5_reg <= tmp_31_reg_1356_pp0_iter4_reg;
        tmp_32_reg_1363_pp0_iter2_reg <= tmp_32_reg_1363;
        tmp_32_reg_1363_pp0_iter3_reg <= tmp_32_reg_1363_pp0_iter2_reg;
        tmp_32_reg_1363_pp0_iter4_reg <= tmp_32_reg_1363_pp0_iter3_reg;
        tmp_32_reg_1363_pp0_iter5_reg <= tmp_32_reg_1363_pp0_iter4_reg;
        tmp_reg_1277_pp0_iter2_reg <= tmp_reg_1277;
        tmp_reg_1277_pp0_iter3_reg <= tmp_reg_1277_pp0_iter2_reg;
        zext_ln142_1_reg_1371[7 : 0] <= zext_ln142_1_fu_316_p1[7 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln131_fu_177_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_152;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1148_ce = 1'b1;
    end else begin
        grp_fu_1148_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1157_ce = 1'b1;
    end else begin
        grp_fu_1157_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1166_ce = 1'b1;
    end else begin
        grp_fu_1166_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1175_ce = 1'b1;
    end else begin
        grp_fu_1175_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1184_ce = 1'b1;
    end else begin
        grp_fu_1184_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1193_ce = 1'b1;
    end else begin
        grp_fu_1193_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1202_ce = 1'b1;
    end else begin
        grp_fu_1202_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1211_ce = 1'b1;
    end else begin
        grp_fu_1211_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1220_ce = 1'b1;
    end else begin
        grp_fu_1220_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1229_ce = 1'b1;
    end else begin
        grp_fu_1229_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1238_ce = 1'b1;
    end else begin
        grp_fu_1238_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1247_ce = 1'b1;
    end else begin
        grp_fu_1247_ce = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s2_blk_n = s2_empty_n;
    end else begin
        s2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s2_read = 1'b1;
    end else begin
        s2_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        s3_blk_n = s3_full_n;
    end else begin
        s3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        s3_write = 1'b1;
    end else begin
        s3_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_194_p1 = s2_dout[7:0];

assign acc_10_fu_1102_p2 = ($signed(sext_ln144_15_fu_1099_p1) + $signed(add_ln144_17_fu_1093_p2));

assign acc_11_fu_1111_p2 = ($signed(sext_ln144_19_fu_1108_p1) + $signed(grp_fu_1238_p3));

assign acc_5_fu_334_p0 = zext_ln142_1_reg_1371;

assign acc_5_fu_334_p1 = 16'd65453;

assign acc_9_fu_950_p2 = (sub_ln144_1_fu_944_p2 + zext_ln144_fu_928_p1);

assign add_ln142_fu_378_p2 = (zext_ln142_2_fu_363_p1 + zext_ln142_3_fu_374_p1);

assign add_ln144_11_fu_564_p2 = (sub_ln142_5_fu_526_p2 + 13'd1845);

assign add_ln144_12_fu_574_p2 = ($signed(sext_ln144_11_fu_570_p1) + $signed(sext_ln142_7_fu_560_p1));

assign add_ln144_13_fu_584_p2 = ($signed(sext_ln144_12_fu_580_p1) + $signed(grp_fu_1148_p3));

assign add_ln144_15_fu_1084_p2 = ($signed(sext_ln144_4_fu_1081_p1) + $signed(sext_ln142_9_fu_1077_p1));

assign add_ln144_17_fu_1093_p2 = ($signed(sext_ln144_13_fu_1090_p1) + $signed(add_ln144_15_fu_1084_p2));

assign add_ln144_19_fu_1008_p2 = ($signed(sext_ln142_2_fu_903_p1) + $signed(zext_ln142_22_fu_963_p1));

assign add_ln144_20_fu_1018_p2 = ($signed(sext_ln144_14_fu_1014_p1) + $signed(grp_fu_1202_p3));

assign add_ln144_23_fu_717_p2 = ($signed(grp_fu_1157_p3) + $signed(sext_ln142_15_fu_636_p1));

assign add_ln144_24_fu_726_p2 = ($signed(sext_ln144_17_fu_722_p1) + $signed(sub_ln142_10_fu_621_p2));

assign add_ln144_25_fu_872_p2 = ($signed(sext_ln142_17_fu_855_p1) + $signed(sext_ln142_16_fu_852_p1));

assign add_ln144_26_fu_878_p2 = ($signed(add_ln144_25_fu_872_p2) + $signed(sext_ln144_7_fu_869_p1));

assign add_ln144_28_fu_891_p2 = ($signed(sext_ln144_18_fu_888_p1) + $signed(sext_ln144_8_fu_884_p1));

assign add_ln144_3_fu_799_p2 = ($signed(sext_ln144_2_fu_796_p1) + $signed(sext_ln144_fu_792_p1));

assign add_ln144_4_fu_805_p2 = ($signed(sext_ln142_fu_743_p1) + $signed(sext_ln142_3_fu_778_p1));

assign add_ln144_5_fu_815_p2 = ($signed(sext_ln144_5_fu_811_p1) + $signed(sext_ln142_1_fu_774_p1));

assign add_ln144_6_fu_825_p2 = ($signed(sext_ln144_6_fu_821_p1) + $signed(add_ln144_3_fu_799_p2));

assign add_ln144_8_fu_938_p2 = ($signed(sext_ln144_10_fu_935_p1) + $signed(sext_ln144_1_fu_932_p1));

assign add_ln144_fu_494_p2 = (add_ln142_fu_378_p2 + 13'd1128);

assign and_ln142_10_fu_921_p3 = {{tmp_32_reg_1363_pp0_iter5_reg}, {2'd0}};

assign and_ln142_11_fu_504_p3 = {{tmp_10_reg_1290_pp0_iter3_reg}, {4'd0}};

assign and_ln142_12_fu_515_p3 = {{tmp_10_reg_1290_pp0_iter3_reg}, {1'd0}};

assign and_ln142_13_fu_532_p3 = {{tmp_12_reg_1299_pp0_iter3_reg}, {5'd0}};

assign and_ln142_14_fu_543_p3 = {{tmp_12_reg_1299_pp0_iter3_reg}, {2'd0}};

assign and_ln142_15_fu_1060_p3 = {{tmp_17_reg_1317_pp0_iter6_reg}, {7'd0}};

assign and_ln142_16_fu_831_p3 = {{tmp_23_reg_1334_pp0_iter4_reg}, {4'd0}};

assign and_ln142_17_fu_956_p3 = {{tmp_31_reg_1356_pp0_iter5_reg}, {1'd0}};

assign and_ln142_18_fu_967_p3 = {{tmp_32_reg_1363_pp0_iter5_reg}, {6'd0}};

assign and_ln142_19_fu_988_p3 = {{tmp_32_reg_1363_pp0_iter5_reg}, {4'd0}};

assign and_ln142_1_fu_367_p3 = {{tmp_reg_1277_pp0_iter3_reg}, {2'd0}};

assign and_ln142_20_fu_589_p3 = {{tmp_reg_1277_pp0_iter3_reg}, {6'd0}};

assign and_ln142_21_fu_610_p3 = {{tmp_reg_1277_pp0_iter3_reg}, {1'd0}};

assign and_ln142_22_fu_339_p3 = {{tmp_10_reg_1290_pp0_iter2_reg}, {2'd0}};

assign and_ln142_23_fu_640_p3 = {{tmp_12_reg_1299_pp0_iter3_reg}, {3'd0}};

assign and_ln142_24_fu_651_p3 = {{tmp_12_reg_1299_pp0_iter3_reg}, {1'd0}};

assign and_ln142_25_fu_668_p3 = {{tmp_14_reg_1309_pp0_iter3_reg}, {7'd0}};

assign and_ln142_26_fu_685_p3 = {{tmp_21_reg_1326_pp0_iter3_reg}, {6'd0}};

assign and_ln142_27_fu_696_p3 = {{tmp_21_reg_1326_pp0_iter3_reg}, {3'd0}};

assign and_ln142_28_fu_858_p3 = {{tmp_23_reg_1334_pp0_iter4_reg}, {6'd0}};

assign and_ln142_29_fu_1033_p3 = {{tmp_31_reg_1356_pp0_iter5_reg}, {2'd0}};

assign and_ln142_2_fu_732_p3 = {{tmp_10_reg_1290_pp0_iter4_reg}, {3'd0}};

assign and_ln142_3_fu_390_p3 = {{tmp_12_reg_1299_pp0_iter3_reg}, {7'd0}};

assign and_ln142_4_fu_410_p3 = {{tmp_14_reg_1309_pp0_iter3_reg}, {3'd0}};

assign and_ln142_5_fu_421_p3 = {{tmp_14_reg_1309_pp0_iter3_reg}, {1'd0}};

assign and_ln142_6_fu_746_p3 = {{tmp_17_reg_1317_pp0_iter4_reg}, {4'd0}};

assign and_ln142_7_fu_757_p3 = {{tmp_17_reg_1317_pp0_iter4_reg}, {1'd0}};

assign and_ln142_8_fu_441_p3 = {{tmp_21_reg_1326_pp0_iter3_reg}, {2'd0}};

assign and_ln142_9_fu_464_p3 = {{tmp_28_reg_1349_pp0_iter3_reg}, {4'd0}};

assign and_ln142_s_fu_906_p3 = {{tmp_31_reg_1356_pp0_iter5_reg}, {4'd0}};

assign and_ln_fu_356_p3 = {{tmp_reg_1277_pp0_iter3_reg}, {4'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (s2_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter8 = (s3_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_281 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign grp_fu_1148_p0 = grp_fu_1148_p00;

assign grp_fu_1148_p00 = tmp_fu_202_p4;

assign grp_fu_1148_p1 = 14'd16361;

assign grp_fu_1157_p0 = grp_fu_1157_p00;

assign grp_fu_1157_p00 = a_fu_194_p1;

assign grp_fu_1157_p1 = 15'd32716;

assign grp_fu_1157_p2 = 15'd31815;

assign grp_fu_1166_p0 = grp_fu_1166_p00;

assign grp_fu_1166_p00 = a_reg_1267;

assign grp_fu_1166_p1 = 16'd65433;

assign grp_fu_1166_p2 = grp_fu_1166_p20;

assign grp_fu_1166_p20 = add_ln144_fu_494_p2;

assign grp_fu_1175_p0 = grp_fu_1175_p00;

assign grp_fu_1175_p00 = tmp_23_reg_1334;

assign grp_fu_1175_p1 = 14'd59;

assign grp_fu_1175_p2 = (zext_ln142_38_fu_387_p1 - zext_ln142_5_fu_397_p1);

assign grp_fu_1184_p0 = grp_fu_1184_p00;

assign grp_fu_1184_p00 = tmp_17_reg_1317;

assign grp_fu_1184_p1 = 14'd16363;

assign grp_fu_1193_p0 = grp_fu_1193_p00;

assign grp_fu_1193_p00 = tmp_25_reg_1342_pp0_iter2_reg;

assign grp_fu_1193_p1 = 16'd65428;

assign grp_fu_1202_p0 = grp_fu_1202_p00;

assign grp_fu_1202_p00 = tmp_25_reg_1342_pp0_iter2_reg;

assign grp_fu_1202_p1 = 13'd25;

assign grp_fu_1211_p0 = grp_fu_1211_p00;

assign grp_fu_1211_p00 = tmp_25_reg_1342_pp0_iter2_reg;

assign grp_fu_1211_p1 = 15'd97;

assign grp_fu_1211_p2 = (add_ln144_28_fu_891_p2 - zext_ln142_33_fu_865_p1);

assign grp_fu_1220_p0 = zext_ln142_39_fu_407_p1;

assign grp_fu_1220_p1 = 16'd65433;

assign grp_fu_1229_p0 = zext_ln142_49_fu_461_p1;

assign grp_fu_1229_p1 = 14'd16355;

assign grp_fu_1229_p2 = ($signed(sext_ln142_12_fu_984_p1) - $signed(zext_ln142_24_fu_995_p1));

assign grp_fu_1238_p0 = grp_fu_1238_p00;

assign grp_fu_1238_p00 = tmp_28_reg_1349_pp0_iter3_reg;

assign grp_fu_1238_p1 = 16'd65420;

assign grp_fu_1247_p0 = grp_fu_1247_p00;

assign grp_fu_1247_p00 = tmp_32_reg_1363_pp0_iter3_reg;

assign grp_fu_1247_p1 = 15'd32707;

assign i_2_fu_183_p2 = (ap_sig_allocacmp_i_1 + 8'd1);

assign icmp_ln131_fu_177_p2 = ((ap_sig_allocacmp_i_1 == 8'd216) ? 1'b1 : 1'b0);

assign s3_din = $signed(tmp_395_fu_1133_p4);

assign sext_ln137_1_fu_1119_p1 = $signed(acc_10_reg_1533);

assign sext_ln137_fu_1116_p1 = $signed(acc_9_reg_1503_pp0_iter7_reg);

assign sext_ln142_12_fu_984_p1 = $signed(sub_ln142_7_fu_978_p2);

assign sext_ln142_13_fu_606_p1 = $signed(sub_ln142_9_fu_600_p2);

assign sext_ln142_14_fu_627_p1 = $signed(sub_ln142_11_reg_1407);

assign sext_ln142_15_fu_636_p1 = $signed(sub_ln142_12_fu_630_p2);

assign sext_ln142_16_fu_852_p1 = $signed(sub_ln142_13_reg_1463);

assign sext_ln142_17_fu_855_p1 = $signed(sub_ln142_20_reg_1468);

assign sext_ln142_1_fu_774_p1 = $signed(sub_ln142_1_fu_768_p2);

assign sext_ln142_21_fu_1029_p1 = $signed(sub_ln142_15_fu_1023_p2);

assign sext_ln142_2_fu_903_p1 = sub_ln142_2_reg_1427_pp0_iter5_reg;

assign sext_ln142_3_fu_778_p1 = sub_ln142_2_reg_1427;

assign sext_ln142_4_fu_481_p1 = $signed(sub_ln142_3_fu_475_p2);

assign sext_ln142_7_fu_560_p1 = $signed(sub_ln142_6_fu_554_p2);

assign sext_ln142_9_fu_1077_p1 = $signed(sub_ln142_18_fu_1071_p2);

assign sext_ln142_fu_743_p1 = $signed(sub_ln142_reg_1422);

assign sext_ln144_10_fu_935_p1 = grp_fu_1193_p3;

assign sext_ln144_11_fu_570_p1 = $signed(add_ln144_11_fu_564_p2);

assign sext_ln144_12_fu_580_p1 = $signed(add_ln144_12_fu_574_p2);

assign sext_ln144_13_fu_1090_p1 = grp_fu_1229_p3;

assign sext_ln144_14_fu_1014_p1 = $signed(add_ln144_19_fu_1008_p2);

assign sext_ln144_15_fu_1099_p1 = $signed(add_ln144_20_reg_1518);

assign sext_ln144_17_fu_722_p1 = $signed(add_ln144_23_fu_717_p2);

assign sext_ln144_18_fu_888_p1 = grp_fu_1184_p3;

assign sext_ln144_19_fu_1108_p1 = grp_fu_1247_p3;

assign sext_ln144_1_fu_932_p1 = $signed(add_ln144_6_reg_1488);

assign sext_ln144_2_fu_796_p0 = grp_fu_1175_p3;

assign sext_ln144_2_fu_796_p1 = $signed(sext_ln144_2_fu_796_p0);

assign sext_ln144_4_fu_1081_p1 = grp_fu_1220_p3;

assign sext_ln144_5_fu_811_p1 = $signed(add_ln144_4_fu_805_p2);

assign sext_ln144_6_fu_821_p1 = $signed(add_ln144_5_fu_815_p2);

assign sext_ln144_7_fu_869_p1 = $signed(add_ln144_24_reg_1478);

assign sext_ln144_8_fu_884_p1 = $signed(add_ln144_26_fu_878_p2);

assign sext_ln144_fu_792_p1 = $signed(sub_ln144_fu_787_p2);

assign sext_ln147_fu_1129_p1 = $signed(tmp_53_fu_1122_p3);

assign start_out = real_start;

assign sub_ln142_10_fu_621_p2 = ($signed(sext_ln142_13_fu_606_p1) - $signed(zext_ln142_26_fu_617_p1));

assign sub_ln142_11_fu_350_p2 = (11'd0 - zext_ln142_27_fu_346_p1);

assign sub_ln142_12_fu_630_p2 = ($signed(sext_ln142_14_fu_627_p1) - $signed(zext_ln142_37_fu_384_p1));

assign sub_ln142_13_fu_662_p2 = (zext_ln142_28_fu_647_p1 - zext_ln142_29_fu_658_p1);

assign sub_ln142_14_fu_707_p2 = (zext_ln142_32_fu_703_p1 - zext_ln142_31_fu_692_p1);

assign sub_ln142_15_fu_1023_p2 = (13'd0 - zext_ln142_13_fu_913_p1);

assign sub_ln142_16_fu_1044_p2 = ($signed(sext_ln142_21_fu_1029_p1) - $signed(zext_ln142_35_fu_1040_p1));

assign sub_ln142_18_fu_1071_p2 = (zext_ln142_41_fu_1057_p1 - zext_ln142_19_fu_1067_p1);

assign sub_ln142_19_fu_842_p2 = (zext_ln142_43_fu_781_p1 - zext_ln142_20_fu_838_p1);

assign sub_ln142_1_fu_768_p2 = (zext_ln142_8_fu_753_p1 - zext_ln142_9_fu_764_p1);

assign sub_ln142_20_fu_679_p2 = (zext_ln142_39_fu_407_p1 - zext_ln142_30_fu_675_p1);

assign sub_ln142_2_fu_452_p2 = (zext_ln142_10_fu_448_p1 - zext_ln142_42_fu_438_p1);

assign sub_ln142_3_fu_475_p2 = (13'd0 - zext_ln142_12_fu_471_p1);

assign sub_ln142_4_fu_485_p2 = ($signed(sext_ln142_4_fu_481_p1) - $signed(zext_ln142_49_fu_461_p1));

assign sub_ln142_5_fu_526_p2 = (zext_ln142_16_fu_522_p1 - zext_ln142_15_fu_511_p1);

assign sub_ln142_6_fu_554_p2 = (zext_ln142_17_fu_539_p1 - zext_ln142_18_fu_550_p1);

assign sub_ln142_7_fu_978_p2 = (15'd0 - zext_ln142_23_fu_974_p1);

assign sub_ln142_9_fu_600_p2 = (15'd0 - zext_ln142_25_fu_596_p1);

assign sub_ln142_fu_432_p2 = (zext_ln142_6_fu_417_p1 - zext_ln142_7_fu_428_p1);

assign sub_ln144_1_fu_944_p2 = (add_ln144_8_fu_938_p2 - zext_ln142_14_fu_917_p1);

assign sub_ln144_fu_787_p0 = grp_fu_1166_p3;

assign sub_ln144_fu_787_p2 = ($signed(sub_ln144_fu_787_p0) - $signed(zext_ln142_4_fu_739_p1));

assign tmp_395_fu_1133_p4 = {{{{329'd555356629313575812933360731095294709076729024733066056234213152646821808251319366480208477552638677}, {sext_ln147_fu_1129_p1}}}, {sext_ln137_fu_1116_p1}};

assign tmp_53_fu_1122_p3 = {{acc_11_reg_1538}, {sext_ln137_1_fu_1119_p1}};

assign tmp_fu_202_p4 = {{s2_dout[15:8]}};

assign zext_ln142_10_fu_448_p1 = and_ln142_8_fu_441_p3;

assign zext_ln142_12_fu_471_p1 = and_ln142_9_fu_464_p3;

assign zext_ln142_13_fu_913_p1 = and_ln142_s_fu_906_p3;

assign zext_ln142_14_fu_917_p1 = and_ln142_s_fu_906_p3;

assign zext_ln142_15_fu_511_p1 = and_ln142_11_fu_504_p3;

assign zext_ln142_16_fu_522_p1 = and_ln142_12_fu_515_p3;

assign zext_ln142_17_fu_539_p1 = and_ln142_13_fu_532_p3;

assign zext_ln142_18_fu_550_p1 = and_ln142_14_fu_543_p3;

assign zext_ln142_19_fu_1067_p1 = and_ln142_15_fu_1060_p3;

assign zext_ln142_1_fu_316_p1 = a_reg_1267;

assign zext_ln142_20_fu_838_p1 = and_ln142_16_fu_831_p3;

assign zext_ln142_22_fu_963_p1 = and_ln142_17_fu_956_p3;

assign zext_ln142_23_fu_974_p1 = and_ln142_18_fu_967_p3;

assign zext_ln142_24_fu_995_p1 = and_ln142_19_fu_988_p3;

assign zext_ln142_25_fu_596_p1 = and_ln142_20_fu_589_p3;

assign zext_ln142_26_fu_617_p1 = and_ln142_21_fu_610_p3;

assign zext_ln142_27_fu_346_p1 = and_ln142_22_fu_339_p3;

assign zext_ln142_28_fu_647_p1 = and_ln142_23_fu_640_p3;

assign zext_ln142_29_fu_658_p1 = and_ln142_24_fu_651_p3;

assign zext_ln142_2_fu_363_p1 = and_ln_fu_356_p3;

assign zext_ln142_30_fu_675_p1 = and_ln142_25_fu_668_p3;

assign zext_ln142_31_fu_692_p1 = and_ln142_26_fu_685_p3;

assign zext_ln142_32_fu_703_p1 = and_ln142_27_fu_696_p3;

assign zext_ln142_33_fu_865_p1 = and_ln142_28_fu_858_p3;

assign zext_ln142_35_fu_1040_p1 = and_ln142_29_fu_1033_p3;

assign zext_ln142_37_fu_384_p1 = tmp_10_reg_1290_pp0_iter3_reg;

assign zext_ln142_38_fu_387_p1 = tmp_12_reg_1299_pp0_iter3_reg;

assign zext_ln142_39_fu_407_p1 = tmp_14_reg_1309_pp0_iter3_reg;

assign zext_ln142_3_fu_374_p1 = and_ln142_1_fu_367_p3;

assign zext_ln142_41_fu_1057_p1 = tmp_17_reg_1317_pp0_iter6_reg;

assign zext_ln142_42_fu_438_p1 = tmp_21_reg_1326_pp0_iter3_reg;

assign zext_ln142_43_fu_781_p1 = tmp_23_reg_1334_pp0_iter4_reg;

assign zext_ln142_49_fu_461_p1 = tmp_28_reg_1349_pp0_iter3_reg;

assign zext_ln142_4_fu_739_p1 = and_ln142_2_fu_732_p3;

assign zext_ln142_5_fu_397_p1 = and_ln142_3_fu_390_p3;

assign zext_ln142_6_fu_417_p1 = and_ln142_4_fu_410_p3;

assign zext_ln142_7_fu_428_p1 = and_ln142_5_fu_421_p3;

assign zext_ln142_8_fu_753_p1 = and_ln142_6_fu_746_p3;

assign zext_ln142_9_fu_764_p1 = and_ln142_7_fu_757_p3;

assign zext_ln144_fu_928_p1 = and_ln142_10_fu_921_p3;

always @ (posedge ap_clk) begin
    zext_ln142_1_reg_1371[15:8] <= 8'b00000000;
    sub_ln142_11_reg_1407[1:0] <= 2'b00;
    sub_ln142_reg_1422[0] <= 1'b0;
    sub_ln142_13_reg_1463[0] <= 1'b0;
end

endmodule //predecoder_kernel_conv1x1_output_layer
