// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module predecoder_kernel_unpack_input (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s0_din,
        s0_num_data_valid,
        s0_fifo_cap,
        s0_full_n,
        s0_write,
        start_out,
        start_write,
        beat_read
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [95:0] s0_din;
input  [3:0] s0_num_data_valid;
input  [3:0] s0_fifo_cap;
input   s0_full_n;
output   s0_write;
output   start_out;
output   start_write;
input  [511:0] beat_read;

reg ap_idle;
reg s0_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln18_fu_125_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    s0_blk_n;
wire    ap_block_pp0_stage0;
reg   [511:0] beat_read_1_reg_399;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln19_fu_146_p2;
reg   [0:0] icmp_ln19_reg_408;
wire   [2:0] select_ln19_fu_190_p3;
reg   [2:0] select_ln19_reg_413;
wire   [2:0] select_ln19_1_fu_198_p3;
reg   [2:0] select_ln19_1_reg_418;
wire   [0:0] bit_select_i_i_fu_340_p3;
reg   [0:0] bit_select_i_i_reg_423;
reg   [2:0] x_fu_64;
wire   [2:0] x_1_fu_206_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_x_load;
reg   [2:0] y_fu_68;
reg   [2:0] ap_sig_allocacmp_y_load;
reg   [5:0] indvar_flatten_fu_72;
wire   [5:0] select_ln19_2_fu_218_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [2:0] t_fu_76;
wire   [2:0] select_ln18_1_fu_255_p3;
reg    ap_loop_init_pp0_iter1_reg;
reg   [2:0] ap_sig_allocacmp_t_load;
reg   [7:0] indvar_flatten12_fu_80;
wire   [7:0] add_ln18_fu_131_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten12_load;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln20_fu_166_p2;
wire   [0:0] xor_ln18_fu_160_p2;
wire   [2:0] select_ln18_fu_152_p3;
wire   [0:0] and_ln18_fu_172_p2;
wire   [0:0] or_ln19_fu_184_p2;
wire   [2:0] y_2_fu_178_p2;
wire   [5:0] add_ln19_1_fu_212_p2;
wire   [2:0] t_2_fu_249_p2;
wire   [5:0] p_shl_fu_262_p3;
wire   [3:0] p_shl1_fu_274_p3;
wire   [6:0] p_shl_cast_fu_270_p1;
wire   [6:0] p_shl1_cast_fu_282_p1;
wire   [6:0] mul_fu_286_p2;
wire   [6:0] zext_ln19_fu_292_p1;
wire   [6:0] add_fu_295_p2;
wire   [7:0] p_shl3_fu_309_p3;
wire   [9:0] p_shl2_fu_301_p3;
wire  signed [9:0] p_shl3_cast_fu_317_p1;
wire   [9:0] mul9_fu_321_p2;
wire   [9:0] zext_ln20_fu_327_p1;
wire   [9:0] idx_fu_330_p2;
wire  signed [31:0] sext_ln22_fu_336_p1;
wire   [1:0] or_ln_fu_352_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_109;
reg    ap_condition_135;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 x_fu_64 = 3'd0;
#0 y_fu_68 = 3'd0;
#0 indvar_flatten_fu_72 = 6'd0;
#0 t_fu_76 = 3'd0;
#0 indvar_flatten12_fu_80 = 8'd0;
end

predecoder_kernel_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_109)) begin
        if ((icmp_ln18_fu_125_p2 == 1'd0)) begin
            indvar_flatten12_fu_80 <= add_ln18_fu_131_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten12_fu_80 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_109)) begin
        if ((icmp_ln18_fu_125_p2 == 1'd0)) begin
            indvar_flatten_fu_72 <= select_ln19_2_fu_218_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_72 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_135)) begin
        t_fu_76 <= select_ln18_1_fu_255_p3;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_109)) begin
    if ((icmp_ln18_fu_125_p2 == 1'd0)) begin
        x_fu_64 <= x_1_fu_206_p2;
    end else if ((ap_loop_init == 1'b1)) begin
        x_fu_64 <= 3'd0;
    end
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_109)) begin
    if ((icmp_ln18_fu_125_p2 == 1'd0)) begin
        y_fu_68 <= select_ln19_1_fu_198_p3;
    end else if ((ap_loop_init == 1'b1)) begin
        y_fu_68 <= 3'd0;
    end
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        beat_read_1_reg_399 <= beat_read;
        bit_select_i_i_reg_423 <= bit_select_i_i_fu_340_p3;
        icmp_ln19_reg_408 <= icmp_ln19_fu_146_p2;
        select_ln19_1_reg_418 <= select_ln19_1_fu_198_p3;
        select_ln19_reg_413 <= select_ln19_fu_190_p3;
    end
end

always @ (*) begin
    if (((icmp_ln18_fu_125_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten12_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten12_load = indvar_flatten12_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        ap_sig_allocacmp_t_load = 3'd0;
    end else begin
        ap_sig_allocacmp_t_load = t_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x_load = 3'd0;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_y_load = 3'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_68;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        s0_blk_n = s0_full_n;
    end else begin
        s0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        s0_write = 1'b1;
    end else begin
        s0_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_fu_295_p2 = (mul_fu_286_p2 + zext_ln19_fu_292_p1);

assign add_ln18_fu_131_p2 = (ap_sig_allocacmp_indvar_flatten12_load + 8'd1);

assign add_ln19_1_fu_212_p2 = (ap_sig_allocacmp_indvar_flatten_load + 6'd1);

assign and_ln18_fu_172_p2 = (xor_ln18_fu_160_p2 & icmp_ln20_fu_166_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (s0_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_109 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_135 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign bit_select_i_i_fu_340_p3 = beat_read_1_reg_399[sext_ln22_fu_336_p1];

assign icmp_ln18_fu_125_p2 = ((ap_sig_allocacmp_indvar_flatten12_load == 8'd216) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_146_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 6'd36) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_166_p2 = ((ap_sig_allocacmp_x_load == 3'd6) ? 1'b1 : 1'b0);

assign idx_fu_330_p2 = (mul9_fu_321_p2 + zext_ln20_fu_327_p1);

assign mul9_fu_321_p2 = ($signed(p_shl2_fu_301_p3) - $signed(p_shl3_cast_fu_317_p1));

assign mul_fu_286_p2 = (p_shl_cast_fu_270_p1 - p_shl1_cast_fu_282_p1);

assign or_ln19_fu_184_p2 = (icmp_ln19_fu_146_p2 | and_ln18_fu_172_p2);

assign or_ln_fu_352_p3 = {{1'd0}, {bit_select_i_i_reg_423}};

assign p_shl1_cast_fu_282_p1 = p_shl1_fu_274_p3;

assign p_shl1_fu_274_p3 = {{select_ln18_1_fu_255_p3}, {1'd0}};

assign p_shl2_fu_301_p3 = {{add_fu_295_p2}, {3'd0}};

assign p_shl3_cast_fu_317_p1 = $signed(p_shl3_fu_309_p3);

assign p_shl3_fu_309_p3 = {{add_fu_295_p2}, {1'd0}};

assign p_shl_cast_fu_270_p1 = p_shl_fu_262_p3;

assign p_shl_fu_262_p3 = {{select_ln18_1_fu_255_p3}, {3'd0}};

assign s0_din = or_ln_fu_352_p3;

assign select_ln18_1_fu_255_p3 = ((icmp_ln19_reg_408[0:0] == 1'b1) ? t_2_fu_249_p2 : ap_sig_allocacmp_t_load);

assign select_ln18_fu_152_p3 = ((icmp_ln19_fu_146_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_y_load);

assign select_ln19_1_fu_198_p3 = ((and_ln18_fu_172_p2[0:0] == 1'b1) ? y_2_fu_178_p2 : select_ln18_fu_152_p3);

assign select_ln19_2_fu_218_p3 = ((icmp_ln19_fu_146_p2[0:0] == 1'b1) ? 6'd1 : add_ln19_1_fu_212_p2);

assign select_ln19_fu_190_p3 = ((or_ln19_fu_184_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_x_load);

assign sext_ln22_fu_336_p1 = $signed(idx_fu_330_p2);

assign start_out = real_start;

assign t_2_fu_249_p2 = (ap_sig_allocacmp_t_load + 3'd1);

assign x_1_fu_206_p2 = (select_ln19_fu_190_p3 + 3'd1);

assign xor_ln18_fu_160_p2 = (icmp_ln19_fu_146_p2 ^ 1'd1);

assign y_2_fu_178_p2 = (select_ln18_fu_152_p3 + 3'd1);

assign zext_ln19_fu_292_p1 = select_ln19_1_reg_418;

assign zext_ln20_fu_327_p1 = select_ln19_reg_413;

endmodule //predecoder_kernel_unpack_input
