# SPDX-FileCopyrightText: Copyright (c) 2026 Nasir Ali, C-DAC Noida
# SPDX-License-Identifier: Apache-2.0
"""Export a quantized (golden-layer) model to an HLS C++ header (constexpr
arrays) and a raw binary weight blob for the host path.

Layout, per layer i: flat (row-major) int8 weight array, int32 bias array,
float64 per-output-channel weight scale array, plus the layer's scalar
input/output activation scales. Weight and bias arrays for every layer are
concatenated (weights then biases, layer 0 first) into one binary blob;
weights.h documents each layer's offset and length into that blob. The
blob's SHA-256 is recorded in both the header comment and the returned
metadata (and from there, the metrics JSON), per the plan's requirement to
never hand-transcribe a number that should be machine-generated.
"""
from __future__ import annotations

import hashlib
from pathlib import Path
from typing import List

import numpy as np

from src.nn.golden import GoldenLayer

SPDX_HEADER = (
    "// SPDX-FileCopyrightText: Copyright (c) 2026 Nasir Ali, C-DAC Noida\n"
    "// SPDX-License-Identifier: Apache-2.0\n"
)


def _format_c_array(name: str, dtype: str, values: np.ndarray) -> str:
    flat = values.flatten()
    if dtype == "double":
        # repr() round-trips exactly back to the same float64 (Python's
        # float repr is the shortest string that reparses losslessly).
        values_str = ", ".join(repr(float(v)) for v in flat)
    else:
        values_str = ", ".join(str(int(v)) for v in flat)
    # Wrap at a reasonable line length for readability, not required for compilation.
    wrapped_lines = []
    line = "    "
    for token in values_str.split(", "):
        if len(line) + len(token) + 2 > 100:
            wrapped_lines.append(line.rstrip())
            line = "    "
        line += token + ", "
    wrapped_lines.append(line.rstrip().rstrip(","))
    body = "\n".join(wrapped_lines)
    return f"constexpr {dtype} {name}[{flat.size}] = {{\n{body}\n}};"


def export_hls_header(layers: List[GoldenLayer], precision: str, R: int, output_dir: Path) -> dict:
    """Writes weights_{precision}.h and weights_{precision}.bin to
    output_dir. Returns metadata: sha256, num_layers, weight_bytes, paths.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    header_path = output_dir / f"weights_{precision}.h"
    bin_path = output_dir / f"weights_{precision}.bin"

    blob = bytearray()
    layer_sections = []
    for i, layer in enumerate(layers):
        w_flat = layer.weight_int.astype(np.int8).flatten()
        w_offset = len(blob)
        blob += w_flat.tobytes()
        w_length = len(w_flat)

        b_flat = layer.bias_int.astype(np.int32).flatten()
        b_offset = len(blob)
        blob += b_flat.tobytes()
        b_length = len(b_flat)

        layer_sections.append(
            {
                "index": i,
                "weight_offset": w_offset,
                "weight_length": w_length,
                "weight_shape": list(layer.weight_int.shape),
                "bias_offset": b_offset,
                "bias_length": b_length,
                "weight_scale": layer.weight_scale.tolist(),
                "bias_int": layer.bias_int.tolist(),
                "input_scale": layer.input_scale,
                "output_activation_scale": layer.output_activation_scale,
                "kernel_size": layer.kernel_size,
                "padding": layer.padding,
                "apply_relu": layer.apply_relu,
            }
        )

    sha256 = hashlib.sha256(bytes(blob)).hexdigest()

    lines = [
        SPDX_HEADER,
        "// Generated by src/model/export.py. Do not edit by hand.",
        f"// precision: {precision}",
        f"// R: {R}",
        f"// weight blob SHA-256: {sha256}",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace predecoder_weights {",
        "",
        f"constexpr int NUM_LAYERS = {len(layers)};",
        "",
    ]
    for sec in layer_sections:
        i = sec["index"]
        layer = layers[i]
        lines.append(f"// --- layer {i} ---")
        lines.append(f"constexpr int LAYER{i}_OUT_C = {layer.weight_int.shape[0]};")
        lines.append(f"constexpr int LAYER{i}_IN_C = {layer.weight_int.shape[1]};")
        lines.append(f"constexpr int LAYER{i}_K = {layer.kernel_size};")
        lines.append(f"constexpr int LAYER{i}_PADDING = {layer.padding};")
        lines.append(f"constexpr bool LAYER{i}_APPLY_RELU = {'true' if layer.apply_relu else 'false'};")
        lines.append(_format_c_array(f"LAYER{i}_WEIGHT", "int8_t", layer.weight_int))
        lines.append(_format_c_array(f"LAYER{i}_BIAS", "int32_t", layer.bias_int))
        lines.append(_format_c_array(f"LAYER{i}_WEIGHT_SCALE", "double", layer.weight_scale))
        lines.append(f"constexpr double LAYER{i}_INPUT_SCALE = {layer.input_scale!r};")
        if layer.output_activation_scale is not None:
            lines.append(f"constexpr double LAYER{i}_OUTPUT_SCALE = {layer.output_activation_scale!r};")
            # Per-channel requantization multiplier (weight_scale * input_scale /
            # output_scale), consumed by the HLS kernel as a fixed-point
            # (ap_fixed<48,4>) constant: true_value/output_scale ==
            # acc_int * requant_scale, avoiding floating-point hardware in the
            # actual datapath while staying within golden.py's own tolerance
            # (see docs/DECISIONS.md, 2026-08-17 "fixed-point requant multiplier").
            requant_scale = layer.weight_scale * layer.input_scale / layer.output_activation_scale
            lines.append(_format_c_array(f"LAYER{i}_REQUANT_SCALE", "double", requant_scale))
        lines.append("")

    lines.append("} // namespace predecoder_weights")
    header_path.write_text("\n".join(lines) + "\n")
    bin_path.write_bytes(bytes(blob))

    return {
        "sha256": sha256,
        "num_layers": len(layers),
        "weight_bytes": len(blob),
        "header_path": str(header_path),
        "bin_path": str(bin_path),
        "layers": layer_sections,
    }
