// SPDX-FileCopyrightText: Copyright (c) 2026 Nasir Ali, C-DAC Noida
// SPDX-License-Identifier: Apache-2.0
//
// Reads committed test vectors (tests/vectors/vectors_int8.txt, generated by
// scripts/export_test_vectors.py from src/model/golden.py) and asserts
// bit-equality between predecoder_kernel()'s output and the golden model.
#include "predecoder_kernel.h"

#include <cstdio>
#include <cstdlib>
#include <string>

static bool read_vector_line(FILE* f, ap_uint<512>& syndrome_beat, ap_uint<216>& expected_correction,
                              ap_uint<1>& expected_parity) {
    char syn[217], corr[217], par[4];
    int n = fscanf(f, "%216s %216s %3s", syn, corr, par);
    if (n != 3) return false;

    syndrome_beat = 0;
    expected_correction = 0;
    for (int i = 0; i < 216; i++) {
        if (syn[i] == '1') syndrome_beat[i] = 1;
        if (corr[i] == '1') expected_correction[i] = 1;
    }
    expected_parity = (par[0] == '1') ? 1 : 0;
    return true;
}

int main() {
    const char* candidates[] = {
        "tests/vectors/vectors_int8.txt",              // standalone g++, cwd = repo root: full 200-vector set
        "../../../../tests/vectors/vectors_int8.txt",  // vitis_hls csim working dir when hls/ is at the repo root
        "../../../../../../tests/vectors/vectors_int8.txt",  // same, but with the kernel under hw/hls/
        "../vectors_int8_small.txt",                    // vitis_hls: add_files -tb copies it alongside the tb source
        "vectors_int8_small.txt",
        "../vectors_int8.txt",
        "vectors_int8.txt",
    };
    const char* path = nullptr;
    FILE* f = nullptr;
    for (const char* c : candidates) {
        f = fopen(c, "r");
        if (f) { path = c; break; }
    }
    if (!f) {
        printf("FAIL: could not open test vectors file\n");
        return 1;
    }

    int total = 0, errors = 0;
    ap_uint<512> syndrome_beat;
    ap_uint<216> expected_correction;
    ap_uint<1> expected_parity;

    while (read_vector_line(f, syndrome_beat, expected_correction, expected_parity)) {
        total++;
        ap_uint<512> correction_beat;
        predecoder_kernel(&syndrome_beat, &correction_beat);

        ap_uint<216> actual_correction = 0;
        for (int i = 0; i < 216; i++) actual_correction[i] = correction_beat[i];
        ap_uint<1> actual_parity = correction_beat[216];

        if (actual_correction != expected_correction) {
            errors++;
            printf("shot %d: correction MISMATCH\n", total);
        }
        if (actual_parity != expected_parity) {
            errors++;
            printf("shot %d: obs_parity MISMATCH: got %d expected %d\n", total, (int)actual_parity,
                   (int)expected_parity);
        }
    }
    fclose(f);

    if (errors == 0) {
        printf("PASS: %d/%d shots bit-exact\n", total, total);
        return 0;
    }
    printf("FAIL: %d errors across %d shots\n", errors, total);
    return 1;
}
