# SPDX-FileCopyrightText: Copyright (c) 2026 Nasir Ali, C-DAC Noida
# SPDX-License-Identifier: Apache-2.0
"""Exports hls/kernel_config.h: edge-offset catalog and the observable-parity
lookup table for a FIXED distance (see docs/DECISIONS.md, 2026-08-17
"HLS kernel scoped to a fixed distance"). Distance-independent quantities
(the CNN datapath itself) live in hls/weights_{precision}.h instead.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import torch

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.qec.circuits import NoiseModel, build_rotated_surface_code_circuit, detector_coords_to_grid_index
from src.qec.dem import build_channel_observable_map


def main() -> None:
    import argparse

    ap = argparse.ArgumentParser()
    ap.add_argument("--checkpoint", type=Path,
                    default=REPO_ROOT / "models" / "predecoder_R5_int8.pt")
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "hw" / "hls" / "kernel_config.h")
    ap.add_argument("--eval-p", type=float, default=0.003)
    args = ap.parse_args()

    ckpt = torch.load(args.checkpoint, map_location="cpu", weights_only=False)
    R = ckpt["R"]
    basis = ckpt["basis"]
    edge_offsets = ckpt["edge_offsets"]
    num_channels = ckpt["out_channels"]
    eval_p = args.eval_p

    circuit = build_rotated_surface_code_circuit(R, R, basis, NoiseModel.uniform_depolarizing(eval_p))
    obs_map = build_channel_observable_map(circuit, edge_offsets)  # (num_channels, num_detectors)
    grid_index = detector_coords_to_grid_index(circuit)  # (num_detectors, 3) -> (t,row,col)

    T = H = W = R + 1
    lut = np.zeros((num_channels, T, H, W), dtype=np.uint8)
    for det in range(grid_index.shape[0]):
        t, row, col = grid_index[det]
        lut[:, t, row, col] = obs_map[:, det]

    lines = [
        "// SPDX-FileCopyrightText: Copyright (c) 2026 Nasir Ali, C-DAC Noida",
        "// SPDX-License-Identifier: Apache-2.0",
        "",
        "// Generated by scripts/export_kernel_config.py. Do not edit by hand.",
        f"// Scoped to a fixed distance: R={R}, basis={basis}, eval_p={eval_p}",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace predecoder_kernel_config {",
        "",
        f"constexpr int T = {T};",
        f"constexpr int H = {H};",
        f"constexpr int W = {W};",
        f"constexpr int NUM_CHANNELS = {num_channels};",
        f"constexpr int NUM_EDGE_OFFSETS = {len(edge_offsets)};",
        "",
        "// Hidden-layer channel width. The kernel sizes its activation vectors",
        "// and unroll factors from this, so a narrower model synthesises as a",
        "// genuinely smaller design rather than a padded wide one.",
        f"constexpr int WIDTH = {ckpt['width']};",
        "",
        "// channel 0 is the singleton (weight-1 local error); channels 1..NUM_EDGE_OFFSETS",
        "// correspond to EDGE_OFFSETS[0..NUM_EDGE_OFFSETS-1] (dt, dy, dx).",
        f"constexpr int EDGE_OFFSETS[{len(edge_offsets)}][3] = {{",
    ]
    for dt, dy, dx in edge_offsets:
        lines.append(f"    {{{dt}, {dy}, {dx}}},")
    lines.append("};")
    lines.append("")

    lut_flat = lut.flatten()
    lines.append("// OBS_PARITY_LUT[channel][t][y][x], flattened row-major; index via")
    lines.append("// ((c*T + t)*H + y)*W + x.")
    lines.append(f"constexpr uint8_t OBS_PARITY_LUT[{lut_flat.size}] = {{")
    values_str = ", ".join(str(int(v)) for v in lut_flat)
    line = "    "
    wrapped = []
    for token in values_str.split(", "):
        if len(line) + len(token) + 2 > 100:
            wrapped.append(line.rstrip())
            line = "    "
        line += token + ", "
    wrapped.append(line.rstrip().rstrip(","))
    lines.append("\n".join(wrapped))
    lines.append("};")
    lines.append("")
    lines.append("} // namespace predecoder_kernel_config")

    out_path = args.out  # was hardcoded to the predecessor's hls/ layout
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path}: NUM_CHANNELS={num_channels} T=H=W={T} "
          f"obs_parity nonzero={int(lut.sum())} edge_offsets={len(edge_offsets)}")


if __name__ == "__main__":
    main()
