#!/usr/bin/env python
# SPDX-FileCopyrightText: Copyright (c) 2026 Nasir Ali, C-DAC Noida
# SPDX-License-Identifier: Apache-2.0
"""Emit paper/generated_numbers.tex: every number the manuscript may quote.

The manuscript cites \\newcommand macros defined here and never types a
numeric literal in its results prose. That makes it structurally impossible
for the text and the data to drift apart: if a result changes, the macro
changes with it, and if a macro is missing, LaTeX fails loudly instead of
letting a stale figure stand.

Each macro carries a comment naming the result file it came from and the
provenance tier, so any value in the paper can be traced back to the JSON
that produced it.
"""
from __future__ import annotations

import argparse
import glob
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
PAPER_DIR = REPO_ROOT / "paper"


class Numbers:
    def __init__(self) -> None:
        self.rows: List[Tuple[str, str, str]] = []   # (macro, value, provenance)
        self._seen: Dict[str, str] = {}

    def add(self, macro: str, value: str, provenance: str) -> None:
        if macro in self._seen:
            raise ValueError(f"duplicate macro \\{macro}")
        if not macro.isalpha():
            # \newcommand{\fooTwo} is valid; \newcommand{\foo2} is not, and
            # LaTeX reports it far from the generator that produced it.
            raise ValueError(
                f"macro name {macro!r} must be letters only: LaTeX control "
                f"sequences cannot contain digits or punctuation"
            )
        self._seen[macro] = value
        self.rows.append((macro, value, provenance))

    def render(self) -> str:
        out = [
            "% Generated by scripts/make_numbers.py -- do not edit by hand.",
            "% Every macro below is derived from a file under results/.",
            "% The manuscript must cite these macros rather than typing literals.",
            f"% Macros: {len(self.rows)}",
            "",
        ]
        width = max((len(m) for m, _, _ in self.rows), default=0)
        for macro, value, prov in self.rows:
            out.append(f"\\newcommand{{\\{macro}}}{{{value}}}%{' ' * max(1, width - len(macro))}% {prov}")
        return "\n".join(out) + "\n"


def fmt(x: float, sig: int = 3) -> str:
    """Format for prose at `sig` significant figures.

    Significant figures, not fixed decimals: a fixed-decimal rule renders a
    threshold of 0.0069462 as "0.69462" percent, which claims five digits of
    precision the bootstrap interval does not support.
    """
    if x == 0:
        return "0"
    import math

    ax = abs(x)
    if ax >= 1000:
        return f"{x:,.0f}"
    # Decimals needed to show `sig` significant figures at this magnitude.
    decimals = max(0, sig - 1 - int(math.floor(math.log10(ax))))
    if ax >= 1e-3:
        return _trim(f"{x:.{decimals}f}")
    mant, exp = f"{x:.{sig - 1}e}".split("e")
    return f"{_trim(mant)} \\times 10^{{{int(exp)}}}"


def _trim(s: str) -> str:
    """Drop trailing fractional zeros only.

    A bare .rstrip("0") turns "300" into "3", which silently corrupted the
    clock frequency macro. Trailing zeros are only insignificant to the right
    of a decimal point.
    """
    if "." not in s:
        return s
    return s.rstrip("0").rstrip(".")


def pct(x: float, sig: int = 3) -> str:
    return fmt(x * 100.0, sig)


def load(path: Path) -> Optional[dict]:
    return json.loads(path.read_text()) if path.exists() else None


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=PAPER_DIR / "generated_numbers.tex")
    args = ap.parse_args()

    n = Numbers()

    # ---- environment ------------------------------------------------------
    env = load(REPO_ROOT / "results" / "env.json")
    if env:
        n.add("envCPU", env["host"]["cpu"], "results/env.json")
        n.add("envCores", str(env["host"]["logical_cpus"]), "results/env.json")
        n.add("envGPU", env["host"]["gpu"]["name"], "results/env.json")
        n.add("envVitis", env["fpga_toolchain"]["vitis"], "results/env.json")
        n.add("envXRT", env["fpga_toolchain"]["xrt"]["version"], "results/env.json")
        n.add("envStim", env["software"]["stim"], "results/env.json")
        n.add("envPyMatching", env["software"]["pymatching"], "results/env.json")
        n.add("envSinter", env["software"]["sinter"], "results/env.json")

    # ---- device -----------------------------------------------------------
    dev = load(REPO_ROOT / "results" / "device.json")
    if dev:
        r = dev["resources"]
        n.add("devPart", dev["part"].replace("_", r"\_"), "results/device.json, T1")
        n.add("devLUT", f"{r['lut']:,}", "results/device.json, T1")
        n.add("devFF", f"{r['ff']:,}", "results/device.json, T1")
        n.add("devDSP", f"{r['dsp']:,}", "results/device.json, T1")
        n.add("devBRAM", f"{r['bram']:,}", "results/device.json, T1")
        n.add("devURAM", f"{r['uram']:,}", "results/device.json, T1")
        n.add("devSLR", str(r["slr"]), "results/device.json, T1")
        n.add("devHBMGB", str(dev["memory"]["total_hbm_gb"]), "results/device.json, T1")
        n.add("devHBMChannels", str(dev["memory"]["pseudo_channels_reported"]),
              "results/device.json, T1")
        n.add("devMaxPower", str(dev["power"]["max_power_watts"]), "results/device.json, T1")
        n.add("devIdlePower", fmt(dev["power"]["idle_power_watts_measured"], 4),
              "results/device.json, T1 (xbutil, board idle)")

    # ---- baseline threshold ----------------------------------------------
    thr = load(REPO_ROOT / "results" / "threshold_fit_pymatching_baseline.json")
    if thr:
        f = thr["fit"]
        n.add("pth", pct(f["p_th"]), "results/threshold_fit_pymatching_baseline.json, T4")
        n.add("pthCIlow", pct(f["p_th_ci_low"]), "same, bootstrap 95% CI")
        n.add("pthCIhigh", pct(f["p_th_ci_high"]), "same, bootstrap 95% CI")
        n.add("pthNu", fmt(f["nu"]), "same")
        spread = thr.get("p_th_window_spread", {})
        if spread:
            n.add("pthWindowLow", pct(spread["min"]), "same, fitting-window systematic")
            n.add("pthWindowHigh", pct(spread["max"]), "same, fitting-window systematic")
        n.add("pthBootstrap", str(f["n_bootstrap_converged"]), "same, converged bootstrap fits")

    # ---- baseline grid size ----------------------------------------------
    base_files = sorted(glob.glob(str(REPO_ROOT / "results" / "baselines" / "*.json")))
    if base_files:
        recs = [json.load(open(p)) for p in base_files]
        shots = sum(r["metrics"]["shots"] for r in recs)
        errors = sum(r["metrics"]["errors"] for r in recs)
        ds = sorted({r["config"]["distance"] for r in recs})
        n.add("baselineCells", str(len(recs)), "results/baselines/*.json, T4")
        n.add("baselineShots", f"{shots:,}", "results/baselines/*.json, T4")
        n.add("baselineErrors", f"{errors:,}", "results/baselines/*.json, T4")
        n.add("baselineDistances", ", ".join(str(d) for d in ds), "results/baselines/*.json")

    # ---- roofline ---------------------------------------------------------
    rf = load(REPO_ROOT / "results" / "roofline_R5_w64.json")
    if rf:
        cfg = rf["config"]
        n.add("archMACs", f"{cfg['macs_per_shot']:,}", "results/roofline_R5_w64.json, T4")
        n.add("archWidth", str(cfg["width"]), "same")
        n.add("archDepth", str(cfg["depth"]), "same")
        n.add("rooflineClock", fmt(cfg["clock_mhz"]), "same")
        n.add("roundBudget", fmt(cfg["round_period_us"]), "same")
        for row in rf["roofline"]:
            if row["precision"] == "int8" and row["dsp_utilisation"] == 1.0:
                n.add("rooflineIntEightLatency", fmt(row["min_shot_latency_us"]),
                      "same, INT8 @100% DSP, T4 bound")
                n.add("rooflineIntEightQubits", fmt(row["logical_qubits_per_card"]),
                      "same, INT8 @100% DSP, T4 bound")
            if row["precision"] == "int8" and row["dsp_utilisation"] == 0.5:
                n.add("rooflineIntEightLatencyHalf", fmt(row["min_shot_latency_us"]),
                      "same, INT8 @50% DSP, T4 bound")
                n.add("rooflineIntEightQubitsHalf", fmt(row["logical_qubits_per_card"]),
                      "same, INT8 @50% DSP, T4 bound")
        # LaTeX control sequences may contain letters only, so the qubit count
        # is spelled out rather than embedded as a digit.
        number_words = {1: "One", 2: "Two", 4: "Four", 8: "Eight", 16: "Sixteen",
                        32: "ThirtyTwo", 64: "SixtyFour"}
        for inv in rf.get("required_width", []):
            mf = inv.get("max_feasible")
            if mf:
                count = int(inv["target_qubits"])
                word = number_words.get(count)
                if word is None:
                    continue
                n.add(f"widthForQubits{word}", str(mf["width"]),
                      f"same, max width serving {count} logical qubit(s), INT8 @50% DSP")
        mc = rf.get("measured_comparison", {})
        if mc:
            lo, hi = mc["predecessor_measured_latency_ms"]
            n.add("priorLatencyLo", fmt(lo), "fpga-neural-predecoder hw_build_int8.json, T1")
            n.add("priorLatencyHi", fmt(hi), "same, T1")
            n.add("priorDSP", str(mc["predecessor_dsp_used"]), "same, T2 post-route")
            n.add("priorClock", str(mc["predecessor_kernel_clock_mhz"]), "same, T2")

    # ---- hierarchical decoder --------------------------------------------
    hier_files = sorted(glob.glob(str(REPO_ROOT / "results" / "hierarchical" / "*scale500m.json")))
    for path in hier_files:
        rec = json.load(open(path))
        cfg = rec["config"]
        d, p = cfg["distance"], cfg["p"]
        if abs(p - 0.003) > 1e-12 or d != 5:
            continue   # the reference operating point quoted in the prose
        sweep = rec["tau_sweep"]
        n.add("hierBaselineLER", fmt(sweep[0]["ler_baseline"], 4), f"{Path(path).name}, T4")
        n.add("hierPreOnlyLER", fmt(sweep[0]["ler_predecoder_only"], 4), "same")
        n.add("hierPreOnlyRatio", fmt(sweep[0]["ler_predecoder_only"] / sweep[0]["ler_baseline"]),
              "same, unconditional pre-decoder vs baseline")
        orc = rec["oracle"]
        n.add("hierOracleLER", fmt(orc["ler_oracle"], 4), "same, best over all gates")
        n.add("hierOracleRatio", fmt(orc["ler_oracle"] / orc["ler_baseline"]), "same")
        n.add("hierSaves", str(orc["n_predecoder_saves"]), "same")
        n.add("hierBreaks", str(orc["n_predecoder_breaks"]), "same")
        n.add("hierECE", fmt(rec["reliability"]["expected_calibration_error"], 3), "same")
        n.add("hierTestShots", f"{cfg['shots_test']:,}", "same")
        n.add("hierTrainShots", f"{cfg['shots_trained']:,}", "same, GPU training budget")
        # The tau at which the sweep first reaches the baseline exactly.
        for r in sweep:
            if r["escalation_rate"] >= 1.0:
                n.add("hierTauFullEscalation", fmt(r["tau"], 4), "same")
                break

    # ---- width sweep ------------------------------------------------------
    import re as _re

    width_rows = []
    for path in sorted(glob.glob(str(REPO_ROOT / "results" / "hierarchical" / "*_hierarchical_w*.json"))):
        rec = json.load(open(path))
        m = _re.search(r"_w(\d+)\.pt$", str(rec["config"].get("checkpoint", "")))
        if not m:
            continue
        sweep = rec["tau_sweep"]
        base = sweep[0]["ler_baseline"]
        width_rows.append({
            "width": int(m.group(1)),
            "ratio": sweep[0]["ler_predecoder_only"] / base if base else float("nan"),
        })
    if width_rows:
        width_rows.sort(key=lambda r: r["width"])
        lo, hi = width_rows[0], width_rows[-1]
        n.add("widthSweepMin", str(lo["width"]), "results/hierarchical/*_w*.json, T4")
        n.add("widthSweepMax", str(hi["width"]), "same")
        n.add("widthSweepMinRatio", fmt(lo["ratio"]), "same, narrowest model vs baseline")
        n.add("widthSweepMaxRatio", fmt(hi["ratio"]), "same, widest model vs baseline")
        n.add("widthSweepCount", str(len(width_rows)), "same")
        spread = max(r["ratio"] for r in width_rows) - min(r["ratio"] for r in width_rows)
        n.add("widthSweepSpread", fmt(spread, 2), "same, range of LER ratio across widths")

    # ---- training ---------------------------------------------------------
    tr = load(REPO_ROOT / "results" / "training" / "train_R5_scale500m.json")
    if tr and tr.get("history"):
        h = tr["history"]
        n.add("trainParams", f"{tr['n_params']:,}", "results/training/train_R5_scale500m.json")
        n.add("trainShots", f"{h[-1]['shots']:,}", "same")
        n.add("trainFinalLoss", fmt(h[-1]["loss"], 4), "same")
        n.add("trainRate", f"{h[-1]['shots_per_s']:,.0f}", "same, measured on the A4000")
        n.add("trainMinutes", fmt(h[-1]["elapsed_s"] / 60.0), "same")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(n.render())
    print(f"wrote {args.out} with {len(n.rows)} macros")
    for macro, value, prov in n.rows:
        print(f"  \\{macro:<28} = {value:<28} [{prov}]")


if __name__ == "__main__":
    main()
