-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity predecoder_kernel_conv3d_hidden_layer_12_s_layer1_mult_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 33; 
             AddressWidth     : integer := 4; 
             AddressRange    : integer := 12
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of predecoder_kernel_conv3d_hidden_layer_12_s_layer1_mult_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "100100101111000001001011010100110", 1 => "000000111101110101010100011000111", 2 => "000000111100011011000100101010110", 3 => "011000000111110001111111000010100", 
    4 => "010110111100111100000101000101011", 5 => "011001111100001100010011001110100", 6 => "000000111000110010001101111101100", 7 => "010100110100110010000001000100100", 
    8 => "101000101000000010110101101010100", 9 => "101000001100001011111110010110000", 10 => "000000111000011100110100001011100", 11 => "000000111000101101001110010000000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

