-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity predecoder_kernel_conv3d_hidden_layer_1_Pipeline_RESET_VITIS_LOOP_40_1_VITIS_LOOP_41_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    fb_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_ce0 : OUT STD_LOGIC;
    fb_0_we0 : OUT STD_LOGIC;
    fb_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_1_ce0 : OUT STD_LOGIC;
    fb_0_1_we0 : OUT STD_LOGIC;
    fb_0_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_2_ce0 : OUT STD_LOGIC;
    fb_0_2_we0 : OUT STD_LOGIC;
    fb_0_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_3_ce0 : OUT STD_LOGIC;
    fb_0_3_we0 : OUT STD_LOGIC;
    fb_0_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_4_ce0 : OUT STD_LOGIC;
    fb_0_4_we0 : OUT STD_LOGIC;
    fb_0_4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_5_ce0 : OUT STD_LOGIC;
    fb_0_5_we0 : OUT STD_LOGIC;
    fb_0_5_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_6_ce0 : OUT STD_LOGIC;
    fb_0_6_we0 : OUT STD_LOGIC;
    fb_0_6_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_7_ce0 : OUT STD_LOGIC;
    fb_0_7_we0 : OUT STD_LOGIC;
    fb_0_7_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_8_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_8_ce0 : OUT STD_LOGIC;
    fb_0_8_we0 : OUT STD_LOGIC;
    fb_0_8_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_9_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_9_ce0 : OUT STD_LOGIC;
    fb_0_9_we0 : OUT STD_LOGIC;
    fb_0_9_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_10_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_10_ce0 : OUT STD_LOGIC;
    fb_0_10_we0 : OUT STD_LOGIC;
    fb_0_10_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_11_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_11_ce0 : OUT STD_LOGIC;
    fb_0_11_we0 : OUT STD_LOGIC;
    fb_0_11_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_12_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_12_ce0 : OUT STD_LOGIC;
    fb_0_12_we0 : OUT STD_LOGIC;
    fb_0_12_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_13_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_13_ce0 : OUT STD_LOGIC;
    fb_0_13_we0 : OUT STD_LOGIC;
    fb_0_13_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_14_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_14_ce0 : OUT STD_LOGIC;
    fb_0_14_we0 : OUT STD_LOGIC;
    fb_0_14_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_15_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_15_ce0 : OUT STD_LOGIC;
    fb_0_15_we0 : OUT STD_LOGIC;
    fb_0_15_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_16_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_16_ce0 : OUT STD_LOGIC;
    fb_0_16_we0 : OUT STD_LOGIC;
    fb_0_16_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    fb_0_17_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    fb_0_17_ce0 : OUT STD_LOGIC;
    fb_0_17_we0 : OUT STD_LOGIC;
    fb_0_17_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of predecoder_kernel_conv3d_hidden_layer_1_Pipeline_RESET_VITIS_LOOP_40_1_VITIS_LOOP_41_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv7_6C : STD_LOGIC_VECTOR (6 downto 0) := "1101100";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv6_24 : STD_LOGIC_VECTOR (5 downto 0) := "100100";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln39_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal select_ln39_1_fu_450_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln39_1_reg_590 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln40_fu_470_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln40_reg_594 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln40_1_fu_478_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln40_1_reg_598 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln40_fu_531_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal x_fu_88 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln41_fu_486_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_load : STD_LOGIC_VECTOR (2 downto 0);
    signal y_fu_92 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal ap_sig_allocacmp_y_load : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten_fu_96 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln40_2_fu_498_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (5 downto 0);
    signal s_fu_100 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sig_allocacmp_s_load : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten11_fu_104 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln39_1_fu_397_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_indvar_flatten11_load : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln40_fu_418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln41_fu_438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln39_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln39_fu_412_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln39_fu_424_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal and_ln39_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln40_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln40_fu_458_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln40_1_fu_492_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component predecoder_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component predecoder_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten11_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln39_fu_391_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten11_fu_104 <= add_ln39_1_fu_397_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten11_fu_104 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln39_fu_391_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_96 <= select_ln40_2_fu_498_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_96 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    s_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln39_fu_391_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    s_fu_100 <= select_ln39_1_fu_450_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    s_fu_100 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    x_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln39_fu_391_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    x_fu_88 <= add_ln41_fu_486_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_88 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    y_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln39_fu_391_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    y_fu_92 <= select_ln40_1_fu_478_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    y_fu_92 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln39_1_reg_590 <= select_ln39_1_fu_450_p3;
                select_ln40_1_reg_598 <= select_ln40_1_fu_478_p3;
                select_ln40_reg_594 <= select_ln40_fu_470_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln39_1_fu_397_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten11_load) + unsigned(ap_const_lv7_1));
    add_ln39_fu_412_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_s_load) + unsigned(ap_const_lv2_1));
    add_ln40_1_fu_492_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv6_1));
    add_ln40_fu_458_p2 <= std_logic_vector(unsigned(select_ln39_fu_424_p3) + unsigned(ap_const_lv3_1));
    add_ln41_fu_486_p2 <= std_logic_vector(unsigned(select_ln40_fu_470_p3) + unsigned(ap_const_lv3_1));
    and_ln39_fu_444_p2 <= (xor_ln39_fu_432_p2 and icmp_ln41_fu_438_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln39_fu_391_p2)
    begin
        if (((icmp_ln39_fu_391_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten11_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten11_fu_104)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten11_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_indvar_flatten11_load <= indvar_flatten11_fu_104;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_96)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_96;
        end if; 
    end process;


    ap_sig_allocacmp_s_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, s_fu_100)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_s_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_s_load <= s_fu_100;
        end if; 
    end process;


    ap_sig_allocacmp_x_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_fu_88, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_x_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_x_load <= x_fu_88;
        end if; 
    end process;


    ap_sig_allocacmp_y_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, y_fu_92)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_y_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_y_load <= y_fu_92;
        end if; 
    end process;

    fb_0_10_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_10_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_10_ce0 <= ap_const_logic_1;
        else 
            fb_0_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_10_d0 <= ap_const_lv8_0;

    fb_0_10_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln40_reg_594 = ap_const_lv3_4) and (select_ln39_1_reg_590 = ap_const_lv2_1))) then 
            fb_0_10_we0 <= ap_const_logic_1;
        else 
            fb_0_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_11_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_11_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_11_ce0 <= ap_const_logic_1;
        else 
            fb_0_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_11_d0 <= ap_const_lv8_0;

    fb_0_11_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if ((not((select_ln40_reg_594 = ap_const_lv3_0)) and not((select_ln40_reg_594 = ap_const_lv3_1)) and not((select_ln40_reg_594 = ap_const_lv3_2)) and not((select_ln40_reg_594 = ap_const_lv3_3)) and not((select_ln40_reg_594 = ap_const_lv3_4)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln39_1_reg_590 = ap_const_lv2_1))) then 
            fb_0_11_we0 <= ap_const_logic_1;
        else 
            fb_0_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_12_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_12_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_12_ce0 <= ap_const_logic_1;
        else 
            fb_0_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_12_d0 <= ap_const_lv8_0;

    fb_0_12_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if ((not((select_ln39_1_reg_590 = ap_const_lv2_0)) and not((select_ln39_1_reg_590 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln40_reg_594 = ap_const_lv3_0))) then 
            fb_0_12_we0 <= ap_const_logic_1;
        else 
            fb_0_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_13_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_13_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_13_ce0 <= ap_const_logic_1;
        else 
            fb_0_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_13_d0 <= ap_const_lv8_0;

    fb_0_13_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if ((not((select_ln39_1_reg_590 = ap_const_lv2_0)) and not((select_ln39_1_reg_590 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln40_reg_594 = ap_const_lv3_1))) then 
            fb_0_13_we0 <= ap_const_logic_1;
        else 
            fb_0_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_14_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_14_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_14_ce0 <= ap_const_logic_1;
        else 
            fb_0_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_14_d0 <= ap_const_lv8_0;

    fb_0_14_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if ((not((select_ln39_1_reg_590 = ap_const_lv2_0)) and not((select_ln39_1_reg_590 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln40_reg_594 = ap_const_lv3_2))) then 
            fb_0_14_we0 <= ap_const_logic_1;
        else 
            fb_0_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_15_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_15_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_15_ce0 <= ap_const_logic_1;
        else 
            fb_0_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_15_d0 <= ap_const_lv8_0;

    fb_0_15_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if ((not((select_ln39_1_reg_590 = ap_const_lv2_0)) and not((select_ln39_1_reg_590 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln40_reg_594 = ap_const_lv3_3))) then 
            fb_0_15_we0 <= ap_const_logic_1;
        else 
            fb_0_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_16_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_16_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_16_ce0 <= ap_const_logic_1;
        else 
            fb_0_16_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_16_d0 <= ap_const_lv8_0;

    fb_0_16_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if ((not((select_ln39_1_reg_590 = ap_const_lv2_0)) and not((select_ln39_1_reg_590 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln40_reg_594 = ap_const_lv3_4))) then 
            fb_0_16_we0 <= ap_const_logic_1;
        else 
            fb_0_16_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_17_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_17_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_17_ce0 <= ap_const_logic_1;
        else 
            fb_0_17_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_17_d0 <= ap_const_lv8_0;

    fb_0_17_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if ((not((select_ln39_1_reg_590 = ap_const_lv2_0)) and not((select_ln40_reg_594 = ap_const_lv3_0)) and not((select_ln40_reg_594 = ap_const_lv3_1)) and not((select_ln40_reg_594 = ap_const_lv3_2)) and not((select_ln40_reg_594 = ap_const_lv3_3)) and not((select_ln40_reg_594 = ap_const_lv3_4)) and not((select_ln39_1_reg_590 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_17_we0 <= ap_const_logic_1;
        else 
            fb_0_17_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_1_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_1_ce0 <= ap_const_logic_1;
        else 
            fb_0_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_1_d0 <= ap_const_lv8_0;

    fb_0_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln40_reg_594 = ap_const_lv3_1) and (select_ln39_1_reg_590 = ap_const_lv2_0))) then 
            fb_0_1_we0 <= ap_const_logic_1;
        else 
            fb_0_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_2_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_2_ce0 <= ap_const_logic_1;
        else 
            fb_0_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_2_d0 <= ap_const_lv8_0;

    fb_0_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln40_reg_594 = ap_const_lv3_2) and (select_ln39_1_reg_590 = ap_const_lv2_0))) then 
            fb_0_2_we0 <= ap_const_logic_1;
        else 
            fb_0_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_3_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_3_ce0 <= ap_const_logic_1;
        else 
            fb_0_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_3_d0 <= ap_const_lv8_0;

    fb_0_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln40_reg_594 = ap_const_lv3_3) and (select_ln39_1_reg_590 = ap_const_lv2_0))) then 
            fb_0_3_we0 <= ap_const_logic_1;
        else 
            fb_0_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_4_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_4_ce0 <= ap_const_logic_1;
        else 
            fb_0_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_4_d0 <= ap_const_lv8_0;

    fb_0_4_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln40_reg_594 = ap_const_lv3_4) and (select_ln39_1_reg_590 = ap_const_lv2_0))) then 
            fb_0_4_we0 <= ap_const_logic_1;
        else 
            fb_0_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_5_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_5_ce0 <= ap_const_logic_1;
        else 
            fb_0_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_5_d0 <= ap_const_lv8_0;

    fb_0_5_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if ((not((select_ln40_reg_594 = ap_const_lv3_0)) and not((select_ln40_reg_594 = ap_const_lv3_1)) and not((select_ln40_reg_594 = ap_const_lv3_2)) and not((select_ln40_reg_594 = ap_const_lv3_3)) and not((select_ln40_reg_594 = ap_const_lv3_4)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln39_1_reg_590 = ap_const_lv2_0))) then 
            fb_0_5_we0 <= ap_const_logic_1;
        else 
            fb_0_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_6_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_6_ce0 <= ap_const_logic_1;
        else 
            fb_0_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_6_d0 <= ap_const_lv8_0;

    fb_0_6_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln40_reg_594 = ap_const_lv3_0) and (select_ln39_1_reg_590 = ap_const_lv2_1))) then 
            fb_0_6_we0 <= ap_const_logic_1;
        else 
            fb_0_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_7_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_7_ce0 <= ap_const_logic_1;
        else 
            fb_0_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_7_d0 <= ap_const_lv8_0;

    fb_0_7_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln40_reg_594 = ap_const_lv3_1) and (select_ln39_1_reg_590 = ap_const_lv2_1))) then 
            fb_0_7_we0 <= ap_const_logic_1;
        else 
            fb_0_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_8_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_8_ce0 <= ap_const_logic_1;
        else 
            fb_0_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_8_d0 <= ap_const_lv8_0;

    fb_0_8_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln40_reg_594 = ap_const_lv3_2) and (select_ln39_1_reg_590 = ap_const_lv2_1))) then 
            fb_0_8_we0 <= ap_const_logic_1;
        else 
            fb_0_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_9_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_9_ce0 <= ap_const_logic_1;
        else 
            fb_0_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_9_d0 <= ap_const_lv8_0;

    fb_0_9_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln40_reg_594 = ap_const_lv3_3) and (select_ln39_1_reg_590 = ap_const_lv2_1))) then 
            fb_0_9_we0 <= ap_const_logic_1;
        else 
            fb_0_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_address0 <= zext_ln40_fu_531_p1(3 - 1 downto 0);

    fb_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            fb_0_ce0 <= ap_const_logic_1;
        else 
            fb_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    fb_0_d0 <= ap_const_lv8_0;

    fb_0_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, select_ln39_1_reg_590, ap_block_pp0_stage0_11001, select_ln40_reg_594)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (select_ln40_reg_594 = ap_const_lv3_0) and (select_ln39_1_reg_590 = ap_const_lv2_0))) then 
            fb_0_we0 <= ap_const_logic_1;
        else 
            fb_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln39_fu_391_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten11_load = ap_const_lv7_6C) else "0";
    icmp_ln40_fu_418_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv6_24) else "0";
    icmp_ln41_fu_438_p2 <= "1" when (ap_sig_allocacmp_x_load = ap_const_lv3_6) else "0";
    or_ln40_fu_464_p2 <= (icmp_ln40_fu_418_p2 or and_ln39_fu_444_p2);
    select_ln39_1_fu_450_p3 <= 
        add_ln39_fu_412_p2 when (icmp_ln40_fu_418_p2(0) = '1') else 
        ap_sig_allocacmp_s_load;
    select_ln39_fu_424_p3 <= 
        ap_const_lv3_0 when (icmp_ln40_fu_418_p2(0) = '1') else 
        ap_sig_allocacmp_y_load;
    select_ln40_1_fu_478_p3 <= 
        add_ln40_fu_458_p2 when (and_ln39_fu_444_p2(0) = '1') else 
        select_ln39_fu_424_p3;
    select_ln40_2_fu_498_p3 <= 
        ap_const_lv6_1 when (icmp_ln40_fu_418_p2(0) = '1') else 
        add_ln40_1_fu_492_p2;
    select_ln40_fu_470_p3 <= 
        ap_const_lv3_0 when (or_ln40_fu_464_p2(0) = '1') else 
        ap_sig_allocacmp_x_load;
    xor_ln39_fu_432_p2 <= (icmp_ln40_fu_418_p2 xor ap_const_lv1_1);
    zext_ln40_fu_531_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln40_1_reg_598),64));
end behav;
